### ISSUE TITLE
Ajustar para NT 2023.004 - prazo 06/05/2024

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-nfe#1012]
[Nota Técnica 2023.004 -v.1.00 - Publicada em 11/12/2023](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=/BmhvTh1gRI=)
Criação de Evento de Conciliação Financeira, além de inclusão e alteração de outros campos e regras de validação

> Vários campos alterados e adicionados ao XML
> Novos eventos adicionados Conciliação Financeira e Cancelamento da Conciliação Financeira
> **Com novo campo indDeduzDeson pode causar alteração na totalização, verificar !!**

# Ainda faltam os XSD do novos eventos !!!! Aguardar

# Campos adicionais inclusos dev-master

## tagDI()
Modificado:

I23d CNPJ passa a ser CNPJ/CPF - tagDI() - nome de campo estranho !! aguardar xsd para confirmar

## tagICMS()

Incluso:

N28b indDeduzDeson- tagICMS() - opções:
-  0 Valor do ICMS desonerado (vICMSDeson) não deduz do valor do item (vProd) / total da NF-e.
- 1 Valor do ICMS desonerado (vICMSDeson) deduz do valor do item (vProd) / total da NF-e.

## tagdetPag() 

Inclusos:

YA03b CNPJPag

YA03c UFPag

YA10 CNPJReceb

YA11 idTermPag

**Comment by SuportecTL** [comment]
Produção ficou para 06/05/2024.

**Comment by robmachado** [comment]
Faltam ainda os XSD para o evento de Conciliação Financeira

**Comment by bnsouza** [comment]
Boa tarde! Tudo bem?

@robmachado - Posso em ajudar de alguma forma? Vi que entrou em produção agora dia 01/07/2024 a regra sobre a tag `indDeduzDeson`

Se quiser que eu veja isso, só me chamar, ok?
