### ISSUE TITLE
Ajustar para NT 2023.005 - prazo 24/06/2024

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-nfe#1015]
[Nota Técnica 2023.005 - v1.00 - Publicada em 20/12/2023](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=DyTMNOYLDgE=)
**Evento Insucesso na Entrega da NF-e**

Esta Nota Técnica disponibiliza os novos eventos de Insucesso na Entrega da NF-e e Cancelamento do evento de Insucesso na Entrega da NF-e, conforme disposto no Ajuste SINIEF 58/2022 de 09 de dezembro de 2022.

Quando a entrega da mercadoria não envolver um Conhecimento de Transporte Eletrônico (CT-e), mas estiver relacionado direto com a NF-e, criam-se os eventos abaixo:
- Insucesso na Entrega da NF-e (tpEvento= 110192);
- Cancelamento do Insucesso na Entrega da NF-e (tpEvento= 110193).

O novo evento fiscal da NF-e visa registrar as operações de transporte que ocorreram, mas que por algum motivo (recusa do destinatário ou a sua não localização, por exemplo), não foi possível a conclusão do serviço com a efetivação da entrega da  mercadoria ao recebedor.

**Comment by guicalabria** [comment]
Boa tarde,

   Sabe se esse evento vai permitir o cancelamento da NFe depois das 24
horas? Ou não muda nada sobre isso?

Em qui., 25 de jan. de 2024 às 11:01, Roberto L. Machado <
***@***.***> escreveu:

**Comment by robmachado** [comment]
Guilherme, a NT não trata diretamente sobre o cancelamento da NFe, mas ao que me parece, o evento de de "Insucesso na entrega" poderá fazer parte do processo de cancelamento. 
**O texto se refere apenas ao casos onde a transportadora ter que registrar no verso da DANFE, a não possibilidade da entrega, tornando esse processo eletrônico, sem a necessidade de registrar no verso da DANFE.**

**Comment by robmachado** [comment]
Evento já disponível para testes em homologação em 13/05/2024.

**Comment by wcarmesini** [comment]
@robmachado, tem webservice de distribuição das NFC-e? ou ao menos para listagem das chaves de acesso?

**Comment by SuportecTL** [comment]
Não, em alguns estados tem a opção de baixar os XMLs emitidos por algum portal. Mas a grande maioria não.

**Comment by robmachado** [comment]
@wcarmesini Como o João já disse, alguns estados tem a consulta pela chave via pagina web.
Mas não existe nenhum serviço (nem mesmo pago como os do SERPRO) que permita procurar/baixar NFCe via webservice.
E não teria nenhuma lógica fazer isso pois NFCe é para consumidor final e não tem uso posterior.
**Mas não use as ISSUES para esse tipo de questão, use o FORUM e com um assunto correlato !!!**

**Comment by wcarmesini** [comment]
@robmachado e @SuportecTL, muito obrigado pelo esclarecimento! No entanto, discordo em relação a não fazer sentido ter um webservice para as NFC-e, ao menos para os contadores vinculados à SEFAZ de cada estado. Estou procurando uma forma de obter as notas emitidas para realizar a apuração dos impostos dos nossos clientes do escritório contábil, como são muitos, a morosidade no envio por parte deles dificulta e atrapalha a rotina contábil. Com as NFe modelo 55, como já tem o webservice, é uma maravilha. 

Peço desculpas por usar este issue, nos próximos usarei o fórum.

**Comment by SuportecTL** [comment]
No caso de documentos emitidos, o contribuinte tem a obrigação de manter os documentos emitidos. Tem estado com GO que permite  download, aqui no MS já não permite. Tem soluções para armazenamento dos documentos que podem ser integrados aos sistemas de emissão para facilitar essa questão. Nós, por exemplo, enviamos os XMLs na virada do mês para o contador, além de disponibilizar esses arquivos em um portal. Depende de cada solução, mas na questão legal, o contribuinte é obrigado a manter esses arquivos.

**Comment by robmachado** [comment]
Sim João, isso vale para as EMISSÕES e não para os destinatários como deseja o @wcarmesini.
Os destinatários de NFCe recebem o danfce ou ticket do caixa com o QRCode para verificar a autenticidade, e alguns estados como o RS e aqueles que usam o RS para emissão desse documento, tem a pagina que permite o download manual do xml da NFCe pela chave de acesso. Mas os outros estados não dispõe desse recurso.
**Por favor , fim desse assunto aqui !**
