### ISSUE TITLE
Atualização de URL para RJ 2024

### ISSUE THREAD

**Issue by wprime2018** [nfephp-org/sped-nfe#1031]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [ x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
Atualização de URL para Consulta através do QR code deve ser atualizada até setembro/2024 para a URL; https://consultadfe.fazenda.rj.gov.br/consultaNFCe/QRCode

## Comportamento Atual
<! --- Diga-nos o que acontecer em vez do comportamento esperado ->

## Solução possível
<! --- Não é obrigatório, mas sugere uma correção / razão para o bug, ->

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Pode me informar onde está está informação ? qual é a URL da SEFAZ RJ que estabelece isso

**Comment by robmachado** [comment]
Esta url já está sendo usada para RJ https://consultadfe.fazenda.rj.gov.br/consultaNFCe/QRCode desde 25/01/20024

**Comment by wprime2018** [comment]
https://portal.fazenda.rj.gov.br/dfe/

Em seg., 8 de abr. de 2024, 16:40, Roberto L. Machado <
***@***.***> escreveu:
