### ISSUE TITLE
Ajustar Make para NT 2024.001 - prazo 02/09/2024

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-nfe#1036]
Essa NT 2024.001versão 1.00 estabelece:

1. Uso do CRT = 4 para MEI
2. Limita os CFOPS que podem ser usados pelas MEI
3. Permite que não seja declarada a origem do produto (origem poderá ser null), caso do CRT = 4 e CSOSN=102, 103, 300 ou 400 ou CSOSN = 900
4. Em caso de emissão pelo MEI (CRT=4) e operação interna (idDest=1), o NCM pode ser preenchido de forma facultativa (AJ 33/2022). Podendo ser informado o código “00000000”
5. Se CRT (id:C21) igual 4 com finalidade de devolução de mercadoria (tag:finNFe=4), somente serão aceitos CFOP 1.202, 1.553, 2.202, 2.553, 5.202 e 6.202

**Comment by lidani** [comment]
wip
