### ISSUE TITLE
SEFAZ unificou o SVAN e o SVC-AN de homologação

### ISSUE THREAD

**Issue by Emerson-Gabriel** [nfephp-org/sped-nfe#1040]
* **Estou enviando uma requisição de funcionalidade.

## Comportamento esperado
Conforme [este](https://www.nfe.fazenda.gov.br/portal/informe.aspx?ehCTG=false&Informe=olEbvvOwBjQ=)  aviso da sefaz, ocorrerá a Unificação da SVAN e SVC-AN de HOMOLOGAÇÃO. 
As novas URLs estão descritas em seu portal conforme print:
![image](https://github.com/nfephp-org/sped-nfe/assets/18463395/8013f319-4748-4db4-b2a7-b7b8d47f4a36)

Conforme a sefaz notificou, os usuários devem atualizar seus sistemas de HOMOLOGAÇÂO, até 15/07/2024.

Referências:
https://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=OUC/YVNWZfo=&AspxAutoDetectCookieSupport=1
https://hom.nfe.fazenda.gov.br/PORTAL/informe.aspx?ehCTG=false&page=0&pagesize=3

## Comportamento Atual
--

## Solução possível
Foi criado [este](https://github.com/nfephp-org/sped-nfe/pull/1039) pull alterando as URLs informadas.

## Possível implementação
https://github.com/nfephp-org/sped-nfe/pull/1039

Testes realizados:
Foram realizados testes de consulta de status da sefaz, usando a nova URL.
Também foi feito a transmissão de uma NF-e em ambiente de homologação utilizando a nova URL
Cancelamento de uma NF-e em homologação usando a nova URL.

**Comment by robmachado** [comment]
Já alterado no dev-master
