### ISSUE TITLE
DANFCEPos para o pix com código 20

### ISSUE THREAD

**Issue by wprime2018** [nfephp-org/sped-nfe#1066]
Bom dia, 

Favor alterar no arquivo do DANFCePOS esta linha para identificar o pix no código 20 conforme alteração da NT que foi efetivada no da 01/07/2024

    private function tipoPag($tPag)
    {
        $aPag = [
            '01' => 'Dinheiro',
            '02' => 'Cheque',
            '03' => 'Cartao de Credito',
            '04' => 'Cartao de Debito',
            '05' => 'Credito Loja',
            '10' => 'Vale Alimentacao',
            '11' => 'Vale Refeicao',
            '12' => 'Vale Presente',
            '13' => 'Vale Combustivel',
            '17' => 'PIX',
           ----->  '20' => 'PIX',
            '99' => 'Outros',
        ];
        if (array_key_exists($tPag, $aPag)) {
            return $aPag[$tPag];
        }
        return '';
    }

**Comment by robmachado** [comment]
Esta biblioteca não tem a classe DANFCePOS ela está em outra biblioteca sped-pos
