### ISSUE TITLE
Dataset SEFAZ

### ISSUE THREAD

**Issue by ppKrauss** [nfephp-org/sped-nfe#125]
Reparei que listou [certs/autorizadores.list](https://github.com/nfephp-org/sped-nfe/blob/master/certs/cacerts/autorizadores.list)... Tem alguma mais como um CSV completo com as características de cada SEFAZ específico?

Na [OKBr](https://br.okfn.org/sobre/) temos  interesse em ajudar a publicar esse  tipo de dataset.

**Comment by robmachado** [comment]
De que características você fala ?

**Comment by ppKrauss** [comment]
Pelo que entendi cada SEFAZ faz sua "regras", algumas se repetem para todos, outras são mais "características".

**Comment by robmachado** [comment]
No caso do NFe, CTe, e MDFe, as diferenças que ainda existem estão sendo removidas aos poucos. A única SEFAZ que ainda tem "estranhezas" é a de GO no ambiente de homologação que exige a cadeia de certificação, junto com o certificado do emitente. De resto as diferenças estão nas URL dos webservices que cada SEFAZ obviamente tem a sua, e o provedor do serviço de Contingência que ora e SVC-RS, ora é SVC-AN e ainda pode ter o SVC-SP (para CTe).

**Comment by ppKrauss** [comment]
Obrigado @robmachado (!), agora está mais claro. 
Bom, ainda acho que a listagem é uma ótima candidata a ponto de partida, para a construção de um importante *dataset* no [datasets-br](https://github.com/datasets-br).

[**Aqui está um primeiro rascunho**](https://docs.google.com/spreadsheets/d/1MP4XBulr_mBn6LaEYIh5KCfpOXnxCKg5m3rmnoptulg/edit?usp=sharing), transcrevi os dados e a suas dicas para lá. 
Liberei para qualquer um editar, o Google-docs tem "dedo duro" das edições, pode alterar a vontade... Por favor avalie se interpretei corretamente, repare que tem também duas tabelas de "glossário" sobre autoridades e finalidades.

**Comment by robmachado** [comment]
Bem, são coisas diferentes:
**a lista de autorizadores**, indica o DOMÍNIO do autorizador de algum serviço ON-LINE relativo ao projeto SPED e tem como finalidade o download do Certificado desse domínio para incrementar o CACert do S.O., se esses certificados forem baixados poderão ser usados nas comunicações SOAP para garantir a autenticidade do HOST.

**os webservices**, são as URLS e outras informações necessárias para permitir que os sistemas saibam as condições minimas para permitir o acesso a esses serviços, usando um nome de referencia único. O que pode mudar nesses casos é o nome do serviço, do método, versão, e URL. Cada qual tem seu lugar na hora de realizar uma chamada.

**as contingências** são um conjunto próprio de de endereços. Por exemplo SP usa SVC-AN e BA usa SVC-RS. Esta é a lista de contingencias SVC.
$list = array(
            'AC'=>'SVCAN',
            'AL'=>'SVCAN',
            'AM'=>'SVCAN',
            'AP'=>'SVCRS',
            'BA'=>'SVCRS',
            'CE'=>'SVCRS',
            'DF'=>'SVCAN',
            'ES'=>'SVCRS',
            'GO'=>'SVCRS',
            'MA'=>'SVCRS',
            'MG'=>'SVCAN',
            'MS'=>'SVCRS',
            'MT'=>'SVCRS',
            'PA'=>'SVCRS',
            'PB'=>'SVCAN',
            'PE'=>'SVCRS',
            'PI'=>'SVCRS',
            'PR'=>'SVCRS',
            'RJ'=>'SVCAN',
            'RN'=>'SVCRS',
            'RO'=>'SVCAN',
            'RR'=>'SVCAN',
            'RS'=>'SVCAN',
            'SC'=>'SVCAN',
            'SE'=>'SVCAN',
            'SP'=>'SVCAN',
            'TO'=>'SVCAN');
