### ISSUE TITLE
A chave da NFe indicada [] não pertence a [DF]. Consultando notas destinadas

### ISSUE THREAD

**Issue by tiagocardosos** [nfephp-org/sped-nfe#127]
@robmachado, estou testando o método sefazConsultaChave de uma nota destinada para o meu CNPJ. 

Porém, existe uma validação com o método validKeyByUF. Neste caso, vai me retornar que a NFe não pertence ao meu estado.

O correto não seria pegar apenas a UF da chave? Ex:
$uf = UFList::getUFByCode(substr($chave, 0, 2))

**Comment by robmachado** [comment]
@tiagocardosos Você está CERTISSIMO !!! Obrigado ... estou fazendo a correção. :+1:

**Comment by tiagocardosos** [comment]
@robmachado, você já subiu essa correção?

**Comment by robmachado** [comment]
Sim em principio acredito que não irá dar problema

**Comment by robmachado** [comment]
E essa ISSUE já havia sido fechada em 20 de maio
