### ISSUE TITLE
Teste homologação NFCe (65)  Sefaz GO wsnfe_3.10_mod65.xml

### ISSUE THREAD

**Issue by gitonline** [nfephp-org/sped-nfe#138]
Incluir o (S) do https em  wsnfe_3.10_mod65.xml para sefaz GO:

  <UF>
    <sigla>GO</sigla>
    <homologacao>
<NfeConsultaQR method="QR-CODE" operation="NfeConsultaQR" version="100">https://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe</NfeConsultaQR>

**Comment by robmachado** [comment]
Você mesmo pode fazer isso meu amigo, corrija o que estiver errado e faça um pull request.
Me avise caso não tenha conhecimento para usar o Git e o GitHub que eu mesmo farei essa correção.
Grato pelo auxilio :+1:

**Comment by robmachado** [comment]
Corrigido o endereço (URL) do QRCode de GO
