### ISSUE TITLE
O método environment() parece não ser utilizado

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#163]
https://github.com/nfephp-org/sped-nfe/blob/510fde8b596bfe1de2a187ee48e644840a8ff211/src/Common/Tools.php#L268

Este método parece não ser utilizado, e ao mesmo tempo já existe o método setEnvironment() utilizado no construtor, então acredito que environment() possa ser excluído?

**Comment by robmachado** [comment]
Vou ver isso esta semana OBRIGADO Fernando !
