### ISSUE TITLE
Estrutura de pastas producao/homologacao?

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#164]
https://github.com/nfephp-org/sped-nfe/blob/510fde8b596bfe1de2a187ee48e644840a8ff211/src/Tools.php#L28

Boa tarde, a versão antiga da API já criava no construtor da classe Tools, a estrutura de pastas produção/homologação e suas subpastas de entradas, assinadas, validadas, etc...

Fiz um find por todo o código por "mkdir" e olhei os métodos e não encontrei mais nada...

A API não faz mais nenhuma operação de sistema de arquivos gravando os retornos dos webservices?

**Comment by robmachado** [comment]
Fernando;
A partir desta versão, a API não mais irá acessar o disco. Você poderá manter seus dados TODOS (inclusive os certificados) em base de dados ou manter da forma e no local que desejar.
Quanto especificado e habilitado apenas os LOGS e dados de DEBUG serão gravados, em principio na pasta TEMP.

**Comment by robmachado** [comment]
Veja os documentos na pasta DOCS ainda estão incompletos mas pode ajudar
