### ISSUE TITLE
Tempo de exclusão do certificado no dir TMP

### ISSUE THREAD

**Issue by tiagocardosos** [nfephp-org/sped-nfe#165]
@robmachado, lembro-me que você fez uma alteração no tempo de exclusão do certificado criado no dir tmp. Você acha que seria possível adicionarmos um novo parametro no config para que esse tempo de exclusão seja controlado por lá?

**Comment by robmachado** [comment]
A exclusão é feita em tempo de execução, ao sair da classe os arquivos são removidos. Além disso a cada recarga do S.O. a pasta TMP é limpa também.
Qual é a intensão por traz da sua colocação ??

**Comment by tiagocardosos** [comment]
Em alguns casos, quando utilizamos o método de busca com o NSU zerado o processo não passa de 13min. Verificamos que o certificado está sendo excluído. Porém, acabei de abrir o método responsável por essa exclusão e vi que o ```$this->waitingTime``` já está setado default 45min.

```
/**
     * Delete all files in folder
     */
    public function removeTemporarilyFiles()
    {
        $contents = $this->filesystem->listContents($this->certsdir, true);
        //define um limite de $waitingTime min, ou seja qualquer arquivo criado a mais
        //de $waitingTime min será removido
        //NOTA: quando ocorre algum erro interno na execução do script, alguns
        //arquivos temporários podem permanecer
        //NOTA: O tempo default é de 45 minutos e pode ser alterado diretamente nas
        //propriedades da classe, esse tempo entre 5 a 45 min é recomendável pois
        //podem haver processos concorrentes para um mesmo usuário. Esses processos
        //como o DFe podem ser mais longos, dependendo a forma que o aplicativo
        //utilize a API. Outra solução para remover arquivos "perdidos" pode ser
        //encontrada oportunamente.
        $dt = new \DateTime();
        $tint = new \DateInterval("PT".$this->waitingTime."M");
        $tint->invert = true;
        $tsLimit = $dt->add($tint)->getTimestamp();
        foreach ($contents as $item) {
            if ($item['type'] == 'file') {
                if ($item['path'] == $this->prifile
                    || $item['path'] == $this->pubfile
                    || $item['path'] == $this->certfile
                ) {
                    $this->filesystem->delete($item['path']);
                    continue;
                }
                $timestamp = $this->filesystem->getTimestamp($item['path']);
                if ($timestamp < $tsLimit) {
                    //remove arquivos criados a mais de 45 min
                    $this->filesystem->delete($item['path']);
                }
            }
        }
    }
```
Acho que estamos com um problema no timezone.

**Comment by robmachado** [comment]
Você tem ajustar o tempo de execução das configurações do seu ambiente PHP senão não adianta nada. O seu S.O. irá parar a execução

**Comment by tiagocardosos** [comment]
@robmachado, realmente o nosso problema era com o timezone. A ideia de colocar ```$this->waitingTime``` no config seria para ter controle no tempo de exclusão do certificado. Como nosso timezone foi corrigido, acredito que 45 minutos esteja de bom tamanho!
