### ISSUE TITLE
Sugestão na class NFe\Common\ValidTXT

### ISSUE THREAD

**Issue by weguri** [nfephp-org/sped-nfe#175]
No método isValid a variável $row poderia ser utilizar um trim,  pois quando vai processar cada linha esta dando este erro "_ERRO: Todas as linhas devem terminar com 'pipe'_", quando da um explode esta ficando um espaço no inicio da linha e no fim " A|3.10|NFe|| "
[_A.txt](https://github.com/nfephp-org/sped-nfe/files/1287836/_A.txt)

**Comment by robmachado** [comment]
Vou levar isso em consideração, mas é responsabilidade do seu sistema gerar o arquivo nas condições corretas.

**Comment by weguri** [comment]
Concordo com vc.
Só não entendi porque fica um espaço, apos dar um explode, sendo que txt não tem este espaços.

Fico muito grato pela sua atenção

**Comment by robmachado** [comment]
Bom, agora você me deu outra informação, esta dizendo que a API está colocando um espaço no final da linha. Isso é muito estranho. Temos que investigar, as vezes pode ser o efeito da borboleta amarela batendo assas no deserto de Gobi ou os raios cósmicos. Temos que lembrar que computação tem um que de bruxaria envolvida :-)

**Comment by weguri** [comment]
Creio que o problema seria \r

**Comment by robmachado** [comment]
Isso também é verdade, estou fazendo alguns ajustes para remover os CR e outras tranqueiras antes de validar. Não é realmente minha vontade faze-lo mas isso está ficando muito comum em função do uso do Ruindows. Devo subir as correções desse validador ainda amanhã.
