### ISSUE TITLE
Complements::toAuthorize EnvEvento cStats diferente de 135

### ISSUE THREAD

**Issue by eduardokum** [nfephp-org/sped-nfe#178]
Bom dia,
Tenho a seguinte dúvida, não sei se isso é um problema por isso estou fazendo esse issue.

Nesse arquivo https://github.com/nfephp-org/sped-nfe/blob/v5.0/src/Complements.php#L297

Quando enviamos uma CCe ou Cancelamento por exemplo, teriamos que criar um arquivo com a requisição e o protocolo do evento, esse arquivo deve ser criado somente se o cStat for 135? se for 155 por exemplo não geramos esse arquivo?

Por que a classe joga uma exceção no caso de 155 homologado fora do prazo por exemplo... 

Ou quando for cancelamento não deve criar esse protocolo de evento e somente usar Complements::cancelRegister?

**Comment by robmachado** [comment]
Edu; ainda podem e existem falhas cabe a nós achar esses UGS e propor correções hoje não posso ver isso mas amanhã dou uma analisada.

**Comment by eduardokum** [comment]
Entendo, so não mandei PR pois não sabia se era erro na forma em que eu estava tratando o retorno dos eventos... 

Vou mandar um PR então
