### ISSUE TITLE
Busca de status para notas emitidas no Piaui

### ISSUE THREAD

**Issue by thmarra** [nfephp-org/sped-nfe#220]
Bom dia,
Tenho uma dúvida em questão ao serviço NfeConsulta2, que busca o status da NFe.
Quando envio a requisição de uma NFe que foi emitida no Piaui recebo no xml de resposta que a UF informada não é atendida pelo webservice. 
Fiz umas pesquisas aqui sobre o erro e encontrei o seguinte informativo:
http://www.sefaz.pi.gov.br/index.php/informacoes/imprensa/noticias/noticias-em-destaque/atencao-contribuintes-para-a-mudanca-mudanca-na-autorizacao-da-nf-e
Em resumo, mudaram os serviços do Piauí para o ambiente do RS (SVRS).
Achei um arquivo de autorizadores olhando a API e no Piauí ainda está SVAN. Quando mudei para SVRS o serviço NfeConsulta2 funcionou. 
Será que se atualizar esse arquivo o problema do NfeConsulta2 é resolvido sem afetar os outros?

**Comment by robmachado** [comment]
Ola @thmarra 
Houve algum erro de digitação na ora de identificar os autorizadores e PI estava direcionado para SVAN e não para SVRS.
Essa configuração fica em storage/autorizadores.json, já corrigi na branch marster e farei uma correção de release !!
Obrigado, sempre que tiver algo do tipo e puder e souber como fazer uma PR eu agradeço
Abraço

**Comment by robmachado** [comment]
Atualizado ! em master e no último release !
