### ISSUE TITLE
Refatoração Código

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/sped-nfe#23]
Roberto, eu andei vendo as classes e fiz uns testes, o que acha de por exemplo trocar os ifs e switchs por abordagens com funções.

Atualmente a função, e recebe tantos parâmetros
`tagIMCSSN`

Pode ser:
```
$produto->imposto()
->ICMSSN101(0, 1,25, 4.00)
```

o que acha?

Eu fiz uns testes aqui mais básicos como:

```
$this->{tagasermontada}(parametrosdatag);
```
e ficou muito bom, no caso da função não existir emite um erro.

**Comment by lpj145** [comment]
```
//Manipula o imposto quando CST for 101
    protected function CSOSN101(&$nItem, &$totalTributos, &$impostos)
    {
        $this->nfe->tagICMSSN($nItem, 0, 101, '', '', '', '', '', $impostos['aliquota'], $impostos['cred']);
    }

```

**Comment by robmachado** [comment]
@lpj145  Estou animado a tornar as coisas um pouco diferentes, mas ainda estou analisando o que fazer. Você já viu o sped-console ?? Pois bem a ideia (ainda não definitiva) é:
- usar o sped-console para gerar as classes php da NFe, CTe, etc. a partir do XSD
- usar o sped-serializer (ainda não funcional) para pegar o xml e carregar essas classes geradas com o sped-console
- usar o sped-serializer (ainda não funcional) para criar o xml a partir das classes modelo

Por que essa complicação ?, você pode perguntar ! Em principio para tornar mais "facil" manter as classes modelo quando os xsd são atualizados. Estou tentando marcar um hangout sobre isso com o Jansen e com o Antonio se você quiser participar será muito bem vindo.

**Comment by lpj145** [comment]
Quando é que vai ser?

**Comment by robmachado** [comment]
Olha sua sugestão reduziria os Switchs, porém iria aumentar o numero de métodos e muito. Por hora vamos descartar essa alteração. Mas não estou ignorando sua sugestão, ela é boa !!
