### ISSUE TITLE
Geração de Certificado para testes em Homologação

### ISSUE THREAD

**Issue by lucascampelo** [nfephp-org/sped-nfe#252]
Olá senhores,

Pesquisando a respeito dos certificados, encontrei 2 links na página to Tesouro Nacional explicando como gerar um certificado A1 para ser utilizado em ambiente de Homologação:
* http://www.tesouro.fazenda.gov.br/-/certificado-digital-de-homologacao
* http://www.tesouro.fazenda.gov.br/-/como-gerar-um-certificado-de-homologacao-windows-keystore-explorer-5-0-1-

Estes certificados gerados como explicados nos links podem ser utilizados para geração de NF-e ou outros documentos eletrônicos ?

**Comment by robmachado** [comment]
Lucas;
Eu desconheço a possibilidade de uso de certificados desse tipo nas operações com as SEFAZ, mesmo em homologação. Nunca tentei usar algo como isso portanto não tenho ideia se irá ou  não funcionar e em que condições.

**Comment by clebersantos** [comment]
Olá @robmachado é possível gerar um certificado auto gerido para desenvolvimento e homologação? 

@lucascampelo esses certificados deram certo?

**Comment by robmachado** [comment]
Não para testes reais !!

**Comment by fmertins** [comment]
Boa tarde, eu consigo emitir NF-e apenas em homologação, e apenas na SEFAZ/RS, porque tenho um certificado A1 válido emitido por AC da cadeia nacional etc
~e~ adicionalmente a SEFAZ RS me cadastrou com uma Inscrição Estadual fictícia, apenas em homologação.
Assim funciona, consigo fazer testes sem ter que usar os certificados de clientes...
Mas exemplo, quero testar contingencia no Ambiente Nacional? Não funciona...

**Comment by mileo** [comment]
@fmertins em qual url vc emitiu esse certificado?

**Comment by fmertins** [comment]
> @fmertins em qual url vc emitiu esse certificado?

Olá, emite o A1 valido do seu CNPJ em qualquer certificadora, e depois fala com a SEFAZ/RS para te habilitarem no ambiente de homologacao.

**Comment by RobKMuller** [comment]
Referente aos links apresentados pelo @lucascampelo, não funcionam para realizar homologação das NFe ou NFCe.

Realizei todos os procedimentos listados, e o tesouro me respondeu um e-mail informando que os certificados disponibilizados nao sao destinados a NF.

Ainda estou a procura de um certificado para homologação, afim de baixar os WS no C#.

**Comment by tmendesilva** [comment]
Saberiam me dizer se o certificado(valido) e-CPNJ pode ser utilizado com essa API?

**Comment by robmachado** [comment]
Claro que sim eCNPJ tipo A1 (em arquivo pfx) funciona normalmente (é inclusive o mais usado).

**Comment by tmendesilva** [comment]
> Claro que sim eCNPJ tipo A1 (em arquivo pfx) funciona normalmente (é inclusive o mais usado).

Estou perguntando pois no README do projeto tem uma lista com esses: "NFe (modelo 55), NFCe (modelo 65)
,NFe com eCPF (emissor pessoa física)". Achei q fosse possível somente com NF-e do tipo A1, mas vou comprar um e-CPNJ mesmo pra desenvolver, pois esta mais em conta, obrigado pela atenção.

**Comment by robmachado** [comment]
Pode ser usado também o certificado eNFe (um tipo de eCNPJ) emitido por algumas certificadoras, mas esse tem aplicação mais limitada que o eCNPJ. Mas funciona para NFe/NFCe sem problema.
Recomendo os certificados da Certsign, dão menos problemas com as SEFAZ, mas poder ser de qualquer certificadora do ICP Brasil
