### ISSUE TITLE
Erro ao emitir nota

### ISSUE THREAD

**Issue by devolus** [nfephp-org/sped-nfe#259]
An error occurred while trying to communication via soap, [https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx] Unable to handle request without a valid action parameter. Please supply a valid soap action.

Hoje meu sistema amanheceu com este erro ao tentar emitir uma nota.
A url foi alterada ou algo assim?
Podem me ajudar ?
Desde já agradeço.

**Comment by robmachado** [comment]
Há algum equivoco ai !!! o sped-nfe não ACESSA a prefeitura

**Comment by devolus** [comment]
sped-nfse/src/Models/Prodam/Tools.php
$action = ""http://www.prefeitura.sp.gov.br/nfe/ws/". lcfirst($this->method) .""";

**Comment by robmachado** [comment]
ISSO pertence a outro pacote sped-nfse que está paralizado por falta de interessados

**Comment by devolus** [comment]
tem uma URL válida ou tenho que utilizar outro pacote ? Qual seria melhor ?

**Comment by robmachado** [comment]
o sped-nfe é para as NFe mode 55 e 65 das SEFAZ e não NFSe que são das prefeituras

**Comment by devolus** [comment]
Consegui resolver.
Replace all SOAP_1_2 para SOAP_1_1
Resolveu meu problema.
Espero que possa ajudar alguém
