### ISSUE TITLE
leiaute 4.0

### ISSUE THREAD

**Issue by GlauberF** [nfephp-org/sped-nfe#262]
Olá,
Onde consigo o manual de orientação para leiaute compatível com a NF-e 4.0 ?
se tiveres o link para download, agradeço.

**Comment by andrezipf94** [comment]
Todas as NT de alterações de layout estão disponíveis em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=tW+YMyk/50s=

Não é publicado todo o schema a cada revisão, apenas as partes onde houveram alterações.

Recomendo que questões que não tenham relação direta ao pacote sped-nfe sejam feitas nos fóruns pertinentes, como por exemplo o Google Groups https://groups.google.com/forum/#!forum/nfephp.
