### ISSUE TITLE
Avaliação de custo

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/sped-nfe#271]
https://github.com/nfephp-org/sped-nfe/blob/5134d392bef873fa000eec371046db8177f58af4/src/Make.php#L6988

@robmachado meu caro tudo bem ? espero que sim, grande abraço pra vocês, apesar de ser chato, queria questionar o custo de tal operação inserido nesse contexto, para avaliar melhor temos cerca de 12 ou mais nós com essa função, é certo ter o objeto limpo com o que realmente é importante para o nó, porém há uma falha nessa lógica, nós passamos a utilizar standard objects para população das notas, se o usuário de alguma maneira aloca mais informação nesse objeto, ela não afetará o funcionamento da função tag especifica, haja visto que todos os objetos são requeridos por índices e muito bens sinalizados como vemos no código, então vejo eu o filtro do objeto como uma dosagem maior no custo da operação, se os referidos usuários não se importam com o que realmente é necessário para tag, não deveria ser esse o trabalho da api, estou correto ? por favor, estou a fazer a implantação do sped-nfe aqui, nessa semana acho que soltos alguns pr's com clean code e melhorias possíveis ( dentro dos meus limites). Obrigado pelo ótimo trabalho, vocês são fera!

Adição*: e pensando melhor agora, analisando a possibilidade do usuário colocar somente os dados necessários, teríamos custos sem necessidade, porque passaremos por esse laço sem objetivo.

**Comment by lpj145** [comment]
Podíamos marcar algum dia para um hangout ?

**Comment by robmachado** [comment]
@lpj145 
Sim Marcos podemos marcar um hangout estarei on line e um pouco disponível quinta, sexta e sábado depois na outra semana quase toda. Não irei viajar. Quanto a classe Make estou refatorando de forma a deixar cada TAG em uma trait reduzindo e separando essas operações de forma a ficar muito mais fácil a correção e ajuste pois os arquivos ficarão sensivelmente menores. Quero mostrar para você o que já está feito e o que tem que ainda fazer.

**Comment by lpj145** [comment]
Que bom que esta na ativa por ai, traits acredito eu não ser uma boa saída para essa situação, apesar de termos a possibilidade de herança horizontal, a chave da questão seria estender o máximo que der, também roberto, queria discutir com você a possibilidade de sairmos do Dom de vez, acho que é desgastante termos de escrever algo que existem bibliotecas mantidas e muito bem firmadas na comunidade para tal propósito, não desmerecendo seu trabalho, de modo algum... mas por que trabalhamos mais com vias de regras do que outra coisa, e se algo tende a mudar, isso com certeza será uma regra, mudanças de layouts não foram tão drásticas da versão 3.10 para a 4, isso me faz ver que provavelmente o modelo nfe é encarado como uma estrutura bem definida e madura, o que faz perder o medo de começarmos uma adoção a entidades, a propósito, já falamos sobre padrões para o projeto, pensei em criarmos um repositório e juntar os membros mais ativos de todos os documentos e numa mini maratona começar a definir aquilo que poderemos chamar de contratos para o escopo global do projeto. No mais meu caro, abraços, felicidades a família.

**Comment by lpj145** [comment]
ps* não quero ser entro metido, acredito que se focarmos cada vez mais na importância do que realmente fazemos, teremos maior apoio, melhores noites de sono, e um projeto cada vez mais simples e funcional. porém desde já desculpem a minha ignorância nos assuntos.
