### ISSUE TITLE
Chave Nfe inconsistente.

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/sped-nfe#288]
https://github.com/nfephp-org/sped-nfe/blob/358420e7876640c889f97e8fd132a5cf7d02f458/src/Make.php#L432

Vie uma inconsistência no código, eu defino uma chave com a string 'NFe' no inicio, mas depois o código remove e então concatena de novo ?? eu to errado ?

**Comment by robmachado** [comment]
A chave não é removida e sim substituída, este comando acima remove o "NFe..." no inicio do atributo Id.
a chave se passada deve estar presente sempre !! e será alterada se necessário após a chamada do método $make->monta();
