### ISSUE TITLE
Make::tagdetExport não inclui "exportInd" na tag "detExport"

### ISSUE THREAD

**Issue by ogabrielsantos** [nfephp-org/sped-nfe#30]
["exportInd" está definido na documentação](https://github.com/nfephp-org/sped-nfe/blob/master/src/Make.php#L1841-L1848) mas não possui variável correspondente nem inclusão na tag "detExport" (conforme leiauteNFe_v3.10.xsd). Foi documentado mas não vai ser implementado ou vai ser implementado no futuro?

**Comment by ogabrielsantos** [comment]
Adicionalmente, ["nRE" está sendo usado em "exportInd",](https://github.com/nfephp-org/sped-nfe/blob/master/src/Make.php#L1865-L1872) incorretamente.

**Comment by robmachado** [comment]
O único erro que identifiquei nesse caso está no grupo de documentação do método tagdetExport(), que indica um parâmetro não existente * @param  string $exportInd

O nRE está de acordo com o descrito no manual da Sefaz, não encontrei nenhuma incoerência.

**Comment by ogabrielsantos** [comment]
@robmachado certo! Então a documentação do método e a chamada em [examples/testaMakeNFe.php#L306-L313](https://github.com/nfephp-org/sped-nfe/blob/master/examples/testaMakeNFe.php#L306-L313) precisam ser corrigidas.

**Comment by ogabrielsantos** [comment]
Parece que alguns outros métodos tem documentação definida sem que fosse necessário, posso dar uma olhada e criar uma issue com tais locais e depois mato a issue com um PR ou matar direto com um PR, sem criar issue.
