### ISSUE TITLE
Tag pag para NFCe versão 3.10

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-nfe#300]
Gurizada estou tendo dificuldade para emitir uma NFCe dentro do RS na versão 3.10

Estou recebendo o seguinte retorno na lib “O argumento passado não é um XML válido.”

Analisando descobri que o problema está na tag de pag do XML, hoje atualmente está assim
```xml
<pag>
    <detPag>
        <tPag>01</tPag>
        <vPag>42.34</vPag>
    </detPag>
</pag>
```
Fiz algumas experiências no XML alterando o para:
```xml
<pag>
    <tPag>01</tPag>
    <vPag>42.34</vPag>
</pag>
```
Assim ele passou na validação.

Gostaria de saber se eu estou fazendo alguma coisa de errado, ou se não seria o caso de adicionar esses dois elementos “ tPag”, “ vPag” no método:
```php
$make->tagpag($std);
```
Da classe Make.

**Comment by dbemfica** [comment]
Obrigado pelo retorno

**Comment by robmachado** [comment]
Deve estar funcional agora !

**Comment by dbemfica** [comment]
Funcionou sim, muito obrigado.

Vou fechar a issue
