### ISSUE TITLE
SAT

### ISSUE THREAD

**Issue by mateuspaulo** [nfephp-org/sped-nfe#305]
Olá pessoal. Por favor me tirem uma dúvida.
O sped-nfe tem integração com o SAT? Ou gera cupons fiscais? 
Se não podem me indicar algum que tenha essa opção. Obrigado.

**Comment by robmachado** [comment]
Não Mateus;
O SAT é um equipamento com conexão USB e a API é para uso em servidor.
Para usar o SAT seria necessário um programa em DESKTOP para fazer essa conexão, ou existir um mini-servidor LOCAL com o SAT a ele conectado , mas isso não existe no momento (os SAT tem limitações de bases de conexão e não existe muita documentação sobre a sua comunicação SERIAL USB que permita a criação de uma interface). Os fabricantes querem vender os aplicativos deles !

**Comment by mateuspaulo** [comment]
robmachado Muito obrigado pela ajuda. 
Abraço!

**Comment by robmachado** [comment]
Podem ser criadas alternativas porem a ideia do SAT é rodar mesmo SEM a conexão com a INTERNET.
Nos estados em que o SAT é obrigatório, você terá de criar algo que funcione LOCALMENTE sem a necessidade de acesso via INTERNET pois o SAT é o único sistema de contingência nesses estados. Uma opção é criar um aplicativo "POS" usando por exemplo o ELECTRON e deixar uma base de dados LOCAL, suficiente para realizar as operações básicas de vendas mesmo sem a internet (uso em contingência) .

**Comment by robmachado** [comment]
E fazer um sistema que sincronize a base remota com a LOCAL quando a conexão com a INTERNET for restabelecida.

**Comment by robmachado** [comment]
Esse tipo de recurso você obterá com o ACBR (Delphi) ou algo do tipo apenas em PHP isso não existe.

**Comment by mateuspaulo** [comment]
Entendi. Eu comecei a fazer um sistema em Java  que seguia esse modelo de Ponto de venda.  Porém a mão de obra é grande de mais. Usava a aplicação em java para se comunicar com as dlls do SAT. Vi o ACBR, acho que talvez seja a melhor alternativa para meu problema mesmo.

**Comment by robmachado** [comment]
Alguns fabricantes indicaram fazer um SAT que operasse em rede (mas isso aparentemente morreu) se fizessem algo do tipo iria facilitar em muito pois com um "gadget" desses permitiria um acesso muito facilitado a  qualquer aplicativo LOCAL. Mas iria reduzir os LUCROS deles então acho que foi por isso que desistiram da empreitada.

**Comment by lukinhaspm** [comment]
Olá @mateuspaulo ,
Você quer para uso próprio? Tenho um amigo que tem a solução e ele comercializa o SAT e o Retaguarda em PHP.
Me chame no Skype para falarmos, Lucas Augusto Milanes

@robmachado 
Você pode usar um aparelho SAT para mais de uma maquina com Software PDV no mesmo estabelecimento, se não me engano, a recomendação é usar até 3 pontos de venda no mesmo aparelho SAT - para não criar muita fila de envio.

Abs

**Comment by robmachado** [comment]
Sim eu sei, mas esse numero de Pontos de Vendas (POS) depende do movimento. Se houver muito movimento vai criar muita fila, mesmo com apenas 3 pontos.
Alguns fabricantes disponibilizam algumas soluções para essa concentração de POS em um único SAT. Mas anteriormente, eu me referia a um equipamento mais robusto com uma interface RESTFUL via ethernet, que alguns fabricantes cogitaram fazer a algum (muito) tempo atras.

**Comment by mateuspaulo** [comment]
@lukinhaspm é para a empresa que eu trabalho. Temos um software veterinário que precisa emitir cupons fiscais. Nosso sistema é totalmente web, o que dificulta um pouco a geração de cupons. Por isso estávamos a procura de uma ferramenta que pudesse nos auxiliar. Mas vou passar seu contato para meu gestor e ele entrará em contato com você em breve. 
Obrigado a todos pela força!
