### ISSUE TITLE
NFe 4.00: erro ao consultar chave quando emissor SVRS

### ISSUE THREAD

**Issue by rafaelbeecker** [nfephp-org/sped-nfe#315]
Ao utilizar o método `sefazConsultaChave($chave, $tpAmb)` da classe Tools, considerando tpAmb como 1 e emissor SVRS, tenho identificado um erro com o seguinte resposta/descrição de falha:

_Unable to handle request. The action 'http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsulta4/nfeConsultaNF' was not recognized._

A rotina volta a funcionar normalmente caso, no arquivo _wsnfe_4.00_mod55.xml_,  o atributo _operation_ da entrada _NfeConsultaProtocolo_ for modificado de _NFeConsulta4_ para _NFeConsultaProtocolo4_ (valor idêntico ao atribuido para o mesmo elemento quando em homologação)

**Comment by robmachado** [comment]
Beleza Rafael ! Agradeço a ajuda :+1:

**Comment by rafaelbeecker** [comment]
De nada @robmachado! estou feliz por conseguir contribuir.
