### ISSUE TITLE
Importar NF-e pela Chave

### ISSUE THREAD

**Issue by KaduAmaral** [nfephp-org/sped-nfe#321]
Já vi o seguinte recurso em um sistema, importação da NF-e através da Chave da NFe. Gostaria de saber se no projeto já existe esse recurso, ou se não, se alguém sabe de alguma documentação desse recurso na SEFAZ. Pois esse recurso me interessa muito e estou interessado em implementar essa funcionalidade na biblioteca caso ainda não exista.

**Comment by robmachado** [comment]
Isso existe usando o serviço de DFe da SEFAZ, por favor leia a documentação da SEFAZ sobre o 
assunto. Na API o método é sefazDownload($chave).
Só para esclarecer, Esse método NÃO permite baixar as suas NFe apenas as destinadas ao CNPJ do interessado (referente ao certificado usado).
