### ISSUE TITLE
Como autenticar um XML

### ISSUE THREAD

**Issue by batata004** [nfephp-org/sped-nfe#325]
Olá,

Essa biblioteca parece muito completa mas nao consegui encontrar como que autentico um XML.

Tenho um XML com o formato abaixo. Como que eu gero a assinatura digital dele usando meu certificado digital .p12?

```
				<xmlProcessamentoNfpse>
					
					<bairroTomador>XXX</bairroTomador>
					<baseCalculo>XXX</baseCalculo>
					<baseCalculoSubstituicao>XXX</baseCalculoSubstituicao>
					<cfps>XXX</cfps>

.....

....
```

**Comment by devcosta** [comment]
Amigo vc já viu o outro projeto sped-common? https://github.com/nfephp-org/sped-common
abrs
