### ISSUE TITLE
109 - Servico Paralisado sem Previsao

### ISSUE THREAD

**Issue by eberk9** [nfephp-org/sped-nfe#326]
Caros,

Desde a semana passada estou recebendo esse erro quando tento buscar documentos emitidos contra a empresa. Já liguei na SEFAZ de SP e no 0800 do site nfe.fazenda.gov.br e todo mundo fala que o servidor está operando sem problemas, mas, simplesmente não consigo baixar notas. Alguém tem algum dica ?

**Comment by robmachado** [comment]
O sistema está funcionando normalmente !
