### ISSUE TITLE
Número do destinatário com 2 digitos

### ISSUE THREAD

**Issue by cbonfa** [nfephp-org/sped-nfe#338]
Pessoal, peguei um caso peculiar.

No endereço do destinatário eu posso colocar números com 1 digito, 3, 4, etc... 
Quanto tento colocar um número de 2 digitos. por exemplo "75", me ocorre o seguinte erro:
`"Message: This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}nro': [facet 'pattern'] The value '75' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'. Element '{http://www.portalfiscal.inf.br/nfe}nro': '75' is not a valid value of the local atomic type. "`
Consigo contornar o problema facilmente adicionando um zero na frente. por exemplo 075. Mas a questão é.. isso é correto? Devo seguir esse caminho mesmo?

Abraços,

**Comment by robmachado** [comment]
A mais de 8 anos, isso é recorrentemente questionado no forum !! 
Esse REGEX não é reconhecido pelo PHP, e tem que ser alterado para funcionar, está no arquivo tiposBasico_vxx.xsd

E tem que ser alterado manualmente para '[!-ÿ]{1}[ -ÿ]*[!-ÿ]{1}|[!-ÿ]{1}'

**Comment by robmachado** [comment]
Não sei exatamente qual o ponto que está isso pois é diferente dos REGEX contidos nos XSD da NFe

Um REGES idêntico a esse que você menciona é usado apenas no tiposDistDFe_v1.01.xsd e nada tem haver com a emissão de NFe.

**Comment by cbonfa** [comment]
Corrigido! Obrigado!
