### ISSUE TITLE
Exemplo Protocolar Carta de Correção no XML

### ISSUE THREAD

**Issue by guicouto** [nfephp-org/sped-nfe#339]
Pessoal,
boa tarde,

Ao tentar protocolar o XML de resposta da carta de correção, obtive a seguinte Exception: 
```
Este documento [NfeProc] não recebe protocolos. Confira a ordem dos parâmetros. (src/Exception/DocumentsException.php)
````
Utilizei da mesma forma que está no exemplo disponível em [CARTA DE CORREÇÃO - EXEMPLO](https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/CartaCorrecao.md)

Então no meu código, fiz da seguinte forma:

```
<?php
// Protocolar antes de guardar
$xml = Complements::toAuthorize($meuXml, $xmlResposta);
```

Estou utilizando o método certo?
Desde já agradeço.

**Comment by robmachado** [comment]
@guicouto Verifique o que você está fazendo !! 
Você deve protocolar a SOLICITAÇÃO de CCe e não uma NFe

**Comment by guicouto** [comment]
Certo. Mas então nesse procedimento, o que eu tenho que passar no primeiro parâmetro é o XML da minha NFe já autorizada anteriormente, e no segundo parâmetro, o XML de resposta do SEFAZ, correto?

**Comment by robmachado** [comment]
Não .... eu não disse isso ... falei exatamente outra coisa 

O primeiro parametro é a CCe enviada e NUNCA a NFe

**Comment by robmachado** [comment]
Você deve protocolar nesse caso o EVENTO e nunca a NFe

**Comment by guicouto** [comment]
Entendido @robmachado. Inclusive já testei e funcionou perfeitamente. 
Muito obrigado!
