### ISSUE TITLE
Erro ao tentar incluir caracteres não numéricos na tag IE e IM do Emitente e Destinatário

### ISSUE THREAD

**Issue by thalfm** [nfephp-org/sped-nfe#340]
Segundo o manual da SEFAZ estes campos devem ser formatados quando informados os números, porém pode ser informado  um literal "ISENTO" para o IE por exemplo.

**Comment by robmachado** [comment]
Há anos não deve ser informado ISENTO no campo IE

**Comment by robmachado** [comment]
Mas vou dar uma olhada no código assim que possível.
