### ISSUE TITLE
Tutorial passo a passo

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-nfe#341]
Bom dia Roberto

Não sei se isso chega a ser uma issue, mas senti falta de um tutorial na biblioteca.
Um arquivo markdown com um passo a passos para quem nunca emitir um nota antes.
Exemplo: Para quem nunca emitiu uma nota pode não saber que o processo para emissão é 
1) Criar XML
2) Assinar XML
3) Enviar Lote
4) Consultar lote
4) Adicionar no XML o protocolo da consulta

Ai gostaria de saber se posso escrever esse tutorial para colocarmos na pasta docs ou em outro lugar?

Você gosta da ideia?

**Comment by robmachado** [comment]
@dbemfica 
Diogo, esse é um projeto Open Source, e como tal recebe (e adora receber) contribuições de qualquer tipo, sua ajuda será muito bem vinda !!!

**Comment by marceloch2** [comment]
@dbemfica Para mim por exemplo seria muito útil, creio que nos próximos meses terei que começar a integração e com certeza seu tutorial vai me ajudar. 
+1

**Comment by dbemfica** [comment]
Ok, vou preparar o tutorial e fazer a PR

**Comment by mateuspaulo** [comment]
@dbemfica  Muito bom! Parabéns!
