### ISSUE TITLE
Motivo: 878 - Rejeição: Endereço do site da UF da Consulta por chave de acesso diverge do previsto.

### ISSUE THREAD

**Issue by gitonline** [nfephp-org/sped-nfe#345]
A URL que deve ser informada na consulta é a mesma do QR-CODE, e não o da consulta por chave

1)  Separar o arquivo uri_consulta_nfce.json por tAmb (Ambiente)
 
a) Ambiente Produção (uri_consulta_nfce_amb1.json)

b) Ambiente Homologação (uri_consulta_nfce_amb2.json)

2) Alterar a função  getURIConsultaNFCe($uf)

  protected function getURIConsultaNFCe($uf)
    {
        if ($this->versao < '4.00') {
            return '';
        }
        //existe no XML apenas para layout >= 4.x
        //os URI estão em storage/uri_consulta_nfce.json
        $uri_consulta_nfce='uri_consulta_nfce_amb'.$this->tpAmb.'.json';
         $std = json_decode(
            file_get_contents(
                $this->pathwsfiles."$uri_consulta_nfce"
            )
        );
     
        return $std->$uf;
    }

Abs, 

Walber Sales
[NfePHP_issue.zip](https://github.com/nfephp-org/sped-nfe/files/1765634/NfePHP_issue.zip)

**Comment by robmachado** [comment]
Isso deve ter sido corrigido ! verifique por favor

**Comment by gitonline** [comment]
Olá Mestre,

Sim perfeito!

Abs,

Walber

2018-02-28 10:30 GMT-03:00 Roberto L. Machado <notifications@github.com>:

**Comment by markintux** [comment]
Estou com esse mesmo erro para o estado de SP, em ambiente de homologação utilizando NFC-e. Alguém sabe o que pode ser?

**Comment by robmachado** [comment]
Esse erro é causado pelo endereço no arquivo
https://github.com/nfephp-org/sped-nfe/blob/master/storage/uri_consulta_nfce.json

**Comment by markintux** [comment]
Sim, amigo. Porém eu chequei o endereço de consulta no site: http://www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/URLWebServices.aspx

E ele está igual o deste arquivo. :/
