### ISSUE TITLE
NfeDownloadNF

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-nfe#354]
Alguém sabe dizer quando o serviço NfeDownloadNF vai voltar?

**Comment by robmachado** [comment]
Esse serviço foi DESCONTINUADO !! ou seja "Miou", "kaput", "foi", "morreu"
E foi substituído pelo NfeDistribuicaoDFe, que é usado pela API com o método sefazDownload()

**Comment by dbemfica** [comment]
Mas com serviço NfeDistribuicaoDFe da para pegar todo o XML(com itens e tudo) da Nfe?

Que nem fazemos quando baixamos o XML do site da própria receita.

**Comment by robmachado** [comment]
Apenas e tão somente os menos dados referentes as Notas emitidas CONTRA determinado CNPJ (NFe Destinadas). Por favor estude Nota técnica da SEFAZ a esse respeito.

**Comment by dbemfica** [comment]
ok

Obrigado pelo retorno
