### ISSUE TITLE
Duvida - Cancelamento

### ISSUE THREAD

**Issue by othogar** [nfephp-org/sped-nfe#355]
Bom dia,  Não sei se seria correto perguntar aqui, se não for desculpe.

   Quando eu chamo a function **sefazCancela()** a mesma me retorna o xml que foi retornonado da receita, teria como eu pegar o xml que foi enviado para a receita que gerou o retorno?

Desde já grato.

**Comment by robmachado** [comment]
@othogar Bem, realmente este não é o local correto para colocar DUVIDAS, o mais correto seria no [FORUM](https://groups.google.com/forum/#!forum/nfephp).

Mas vou responder para você. Sempre que fizer uma chama para a SEFAZ, o envio é gravado na variável "lastRequest" da Tools::class então após você receber o retorno da SEFAZ nessa variável você obtêm a ultima mensagem ENVIADA que é o que lhe interessa.
