### ISSUE TITLE
Servico não disponivel para UF

### ISSUE THREAD

**Issue by mrarticuno** [nfephp-org/sped-nfe#356]
Olá, quando tento transmitir a NFC-e para UF ES ele me retorna esse erro:

Este serviço [NfeConsultaQR] não está disponivel para esta unidade da federação [ES] ou para este modelo de Nota [65].

Alguma ideia do que devo fazer ?

Isso só acontece quando coloco a cUF 32 na tagide com modelo 65

**Comment by olavocneto** [comment]
@mrarticuno versão 3.10 ou 4.00? Não encontrei ES no https://github.com/nfephp-org/sped-nfe/blob/master/storage/wsnfe_3.10_mod65.xml ou https://github.com/nfephp-org/sped-nfe/blob/master/storage/wsnfe_4.00_mod65.xml do modelo 65. Dado http://internet.sefaz.es.gov.br/informacoes/nfe/consultar_disponibilidade.php acho que é o mesmo caso de BA (encontrei por aqui https://groups.google.com/forum/#!topic/nfephp/Vf4YrKorw8o) só criar um nó para ES somente com o serviço QR-CODE, doc; http://internet.sefaz.es.gov.br/informacoes/nfcEletronica/qrcode.php

**Comment by mrarticuno** [comment]
Primeiramente obrigado por se dispor a ajudar, entao criei um nó para transmissao no ES porem ele começa a rejeitar com esse codigo:

[450] Rejeicao: Modelo da NF-e diferente de 55

Porém os dados estao preenchidos para emissao em Modelo 65

`$std->cUF = 32;
        $std->cNF = '00099863';
        $std->natOp = 'VENDA';
        $std->mod = 65;
        $std->serie = 1;
        $std->nNF = 19468;
        $std->dhEmi = '2018-03-12T09:53:12-03:00';
        $std->dhSaiEnt = '2018-03-12T09:53:00-02:00';
        $std->tpNF = 1;
        $std->idDest = 1;
        $std->cMunFG = 3205309;
        $std->tpImp = 4;
        $std->tpEmis = 1;
        $std->cDV = 8;
        $std->tpAmb = 2; // Se deixar o tpAmb como 2 você emitirá a nota em ambiente de homologação(teste) e as notas fiscais aqui não tem valor fiscal
        $std->finNFe = 1;
        $std->indFinal = 1;
        $std->indPres = 1;
        $std->procEmi = '0';
        $std->verProc = '000';
        $this->nfe->tagide($std);`

**Comment by olavocneto** [comment]
Interessante você anexar aqui o envelope SOAP com a extensão .XML que a aplicação está gerando para analisarmos.

**Comment by mrarticuno** [comment]
@olavocneto 

Segue o XML consegui resolver essa rejeicao aplicando o setModel('65') antes de transmitir no tools porém agora esta rejeitando por causa da url do QR-Code

<?xml version="1.0" encoding="UTF-8"?>
<nfeProc versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
    <NFe xmlns="http://www.portalfiscal.inf.br/nfe" >
        <infNFe Id="NFe32180327837489000107650010000194681000998699" versao="4.00">
            <ide>
                <cUF>32</cUF>
                <cNF>00099863</cNF>
                <natOp>VENDA</natOp>
                <mod>65</mod>
                <serie>1</serie>
                <nNF>19468</nNF>
                <dhEmi>2018-03-12T12:08:12-03:00</dhEmi>
                <tpNF>1</tpNF>
                <idDest>1</idDest>
                <cMunFG>3205309</cMunFG>
                <tpImp>4</tpImp>
                <tpEmis>1</tpEmis>
                <cDV>8</cDV>
                <tpAmb>2</tpAmb>
                <finNFe>1</finNFe>
                <indFinal>1</indFinal>
                <indPres>1</indPres>
                <procEmi>0</procEmi>
                <verProc>000</verProc>
            </ide>
            <emit>
                <CNPJ>29999489000107</CNPJ>
                <xNome>Nome da Empresa</xNome>
                <enderEmit>
                    <xLgr>Rua Teste</xLgr>
                    <nro>203</nro>
                    <xBairro>Centro</xBairro>
                    <cMun>3205309</cMun>
                    <xMun>Vitoria</xMun>
                    <UF>ES</UF>
                    <CEP>29177050</CEP>
                    <cPais>1058</cPais>
                    <xPais>BRASIL</xPais>
                </enderEmit>
                <IE>083322078</IE>
                <CRT>1</CRT>
            </emit>
            <dest>
                <CNPJ>29159992000160</CNPJ>
                <xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
                <enderDest>
                    <xLgr>Rua Teste</xLgr>
                    <nro>203</nro>
                    <xBairro>Centro</xBairro>
                    <cMun>3205002</cMun>
                    <xMun>Porto Alegre</xMun>
                    <UF>ES</UF>
                    <CEP>29177050</CEP>
                    <cPais>1058</cPais>
                    <xPais>BRASIL</xPais>
                </enderDest>
                <indIEDest>9</indIEDest>
            </dest>
            <det nItem="1">
                <prod>
                    <cProd>5</cProd>
                    <cEAN/>
                    <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                    <NCM>20029010</NCM>
                    <CFOP>5102</CFOP>
                    <uCom>UN</uCom>
                    <qCom>1.0000</qCom>
                    <vUnCom>6.00</vUnCom>
                    <vProd>6.00</vProd>
                    <cEANTrib/>
                    <uTrib>UN</uTrib>
                    <qTrib>1.0000</qTrib>
                    <vUnTrib>6.00</vUnTrib>
                    <indTot>1</indTot>
                </prod>
                <imposto>
                    <vTotTrib>6</vTotTrib>
                    <ICMS>
                        <ICMSSN102>
                            <orig>0</orig>
                            <CSOSN>102</CSOSN>
                        </ICMSSN102>
                    </ICMS>
                </imposto>
            </det>
            <total>
                <ICMSTot>
                    <vBC>0.00</vBC>
                    <vICMS>0.00</vICMS>
                    <vICMSDeson>0.00</vICMSDeson>
                    <vFCP>0.00</vFCP>
                    <vBCST>0.00</vBCST>
                    <vST>0.00</vST>
                    <vFCPST>0.00</vFCPST>
                    <vFCPSTRet>0.00</vFCPSTRet>
                    <vProd>6.00</vProd>
                    <vFrete>0.00</vFrete>
                    <vSeg>0.00</vSeg>
                    <vDesc>0.00</vDesc>
                    <vII>0.00</vII>
                    <vIPI>0.00</vIPI>
                    <vIPIDevol>0.00</vIPIDevol>
                    <vPIS>0.00</vPIS>
                    <vCOFINS>0.00</vCOFINS>
                    <vOutro>0.00</vOutro>
                    <vNF>6.00</vNF>
                    <vTotTrib>6.00</vTotTrib>
                </ICMSTot>
            </total>
            <transp>
                <modFrete>9</modFrete>
            </transp>
            <pag>
                <detPag>
                    <tPag>01</tPag>
                    <vPag>6</vPag>
                </detPag>
            </pag>
        </infNFe>
        <infNFeSupl>
            <qrCode>
                <![CDATA[https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?chNFe=32180327837489000107650010000194681000998638&nVersao=100&tpAmb=2&cDest=29156152000160&dhEmi=323031382d30332d31325431323a30383a31322d30333a3030&vNF=6.00&vICMS=0.00&digVal=4b544d55713041696b356a4d6a5a516c6f665978426353537877343d&cIdToken=000001&cHashQRCode=B0432579049BC0963DBD55D7E61DC759899CF9CA]]>
            </qrCode>
            <urlChave>http://homologacao.sefaz.es.gov.br/ConsultaNFCe</urlChave>
        </infNFeSupl>
        <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <Reference URI="#NFe321803278374890001076500100001946810009xxxxxx">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <DigestValue>KTMUq0Aik5jMjZQlofYxBcSSxw4=</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>Ohaz+PUvWvucGb57WCsPPrg39cUwVsKuScWGrC4uaSBQ6KtV9HrWHZ4VJYU7pIzifoj1rxAFRmE+SCFFpZtypyh3uQ36G7SnE89EJmNjLkJTEkiVTWQbLISPrpS+XVXvbZQRxlvYDZXSxPbd82twiMjE9aAxBcCGYSHNoLvvk5uzsq/P5WbyKaTIAxHrMBTis5eA5B2rzzEN8kCvWGVzlMjAwXeKrze4YxU2/IfSfOIUg0gtmlH5iNHTnILT1yQxQscaE82W72M7Z0eTXS3+kGV/ZAG5ci8YBcV3yXf5M5TBGRB8CZUvPnNmYm84sf9jcr/Kx2v+LcKWkwTl1VcchA==</SignatureValue>
            <KeyInfo>
                <X509Data>
                    <X509Certificate>MIIIWTCCBkGgAwIBAgIQUV8Nd5zkDIKgZ2zHDgFonzANBgkqhkiG9w0BAQsFADCBgDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEkMCIGA1UEAxMbQUMgSW5zdGl0dXRvIEZlbmFjb24gUkZCIEczMB4XDTE4MDEwNDE0Mjg0MFoXDTE5MDEwNDE0Mjg0MFowggEGMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDELMAkGA1UECAwCRVMxDjAMBgNVBAcMBVNlcnJhMTYwNAYDVQQLDC1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsMDVJGQiBlLUNOUEogQTExLTArBgNVBAsMJEF1dGVudGljYWRvIHBvciBBUiBJbnN0aXR1dG8gRmVuYWNvbjFGMEQGA1UEAww9SlVMTFlDUklTVElBTiBEIERFIEFORFJBREUgUElOVE8gNDAgU0FCT1JFUyBNRToyNzgzNzQ4OTAwMDEwNzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKbpiJifQPguYuNWVucCLgoDwdtoZ7oMbTMVkckUqHLPSOVZNh1BK6BGHQ3PujhRNa9a8qHOinITf8RMCx7aJ1P9Qeux4bdrj2vqz+05LpttszQHfMdAxRBjohE77RDdlHi5ttVhWCxa+7WArBOTlDv63pPf8FLgFvPUOIOYJQNf6NJIDi0Vrqha9dVZKtmbt0buwJJ1UBlPkLSisdyFAyPVphTvDyMF3FADn0BBGmp6PQJKT9m4AN3JBrEOq2XJaK8D0atIPnUP9R7MlbMBZkkJb/gESMH1JL7ygkixirwjXcGCAFh+cs5XxdB7YugaNtzx/EcqaR7LimquMIdcy68CAwEAAaOCA0QwggNAMIHOBgNVHREEgcYwgcOgPgYFYEwBAwSgNQQzMjcwOTE5ODUwNTc1MjM1ODcwMTAwMDAwMDAwMDAwMDAwMDAwMDAyMDY4NzgxU1BUQ0VToC8GBWBMAQMCoCYEJEpVTExZQ1JJU1RJQU4gRFVUUkEgREUgQU5EUkFERSBQSU5UT6AZBgVgTAEDA6AQBA4yNzgzNzQ4OTAwMDEwN6AXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBHDQwc2Fib3Jlc2phY2FyYWlwZUBnbWFpbC5jb20wCQYDVR0TBAIwADAfBgNVHSMEGDAWgBQmx5Q9eod+f0t4ioc94M+1zqmw2jCBhgYDVR0gBH8wfTB7BgZgTAECASIwcTBvBggrBgEFBQcCARZjaHR0cDovL2ljcC1icmFzaWwuYWNmZW5hY29uLmNvbS5ici9yZXBvc2l0b3Jpby9kcGMvQUMtSW5zdGl0dXRvLUZlbmFjb24tUkZCL0RQQ19BQ19JRmVuYWNvbl9SRkIucGRmMIHKBgNVHR8EgcIwgb8wXqBcoFqGWGh0dHA6Ly9pY3AtYnJhc2lsLmFjZmVuYWNvbi5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL0FDSW5zdGl0dXRvRmVuYWNvblJGQkczL0xhdGVzdENSTC5jcmwwXaBboFmGV2h0dHA6Ly9pY3AtYnJhc2lsLm91dHJhbGNyLmNvbS5ici9yZXBvc2l0b3Jpby9sY3IvQUNJbnN0aXR1dG9GZW5hY29uUkZCRzMvTGF0ZXN0Q1JMLmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIG7BggrBgEFBQcBAQSBrjCBqzBmBggrBgEFBQcwAoZaaHR0cDovL2ljcC1icmFzaWwuYWNmZW5hY29uLmNvbS5ici9yZXBvc2l0b3Jpby9jZXJ0aWZpY2Fkb3MvQUNfSW5zdGl0dXRvX0ZlbmFjb25fUkZCRzMucDdjMEEGCCsGAQUFBzABhjVodHRwOi8vb2NzcC1hYy1pbnN0aXR1dG8tZmVuYWNvbi1yZmIuY2VydGlzaWduLmNvbS5icjANBgkqhkiG9w0BAQsFAAOCAgEANHK4aIPUz5iJ0RDHfsS4F66mDVUem4IWwc5Z+ctFEXuyXfHPsk9UMmHXplSHj9GF2LkLVScflM91jhz11HmzHiJ+fYhigTxjCzowLJaB/frXrhCDkfy6pFS+6b6r5GjVB9HweZKwcAKNvSWN8lMuuZCpVlaZKOxzHgZ3EmWK9PxfpLwCjJTeS+PohjN08+4spSSjuY/Jeomp3SlC8TO6stuych/D7bVoi6V0254eBFefzMIQI0CbRWgigS5yrpb9zE9Ybr53JzBPfpPSAbFw9l1Gr4uuwZhNhl3VzsDkwdqwZO1oHolbwYXSZw7LcrFOdOCFGneeR7liGiHFGFFnDrxC8Axair1ha+gyim/uzwA0zhl8j8o7XVuoZY0r9zBNltBvhB8O8Ed5I8zF2rCTcVfwYd3g4QhfzxxmiVaTbxSTlqeWMCurw2ZUGCZSk9GqnSNIHXfVv/tZjMuf7Ahem+P00hlMk8tHopsfPkQpR8jntxQ07jvBIYPgeZObZsBSSpt/jwmf5JFfl1WiwzM03aA+/HbVEN60SvOZrp04MQpHuX8G42Q7cP+27DBld6rx/HUVzPeUEWeVvqrshEOAviRuosfYIBDBGL1CfAMROaXXSrkzmm1tLQy6a/2XNwI78SEUTNYl7XxX0rFIJOfTVJ4MuA//lm58u3A2hBpLd+s=</X509Certificate>
                </X509Data>
            </KeyInfo>
        </Signature>
    </NFe>
    <protNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
        <infProt>
            <tpAmb>2</tpAmb>
            <verAplic>SVRSnfce201803061537</verAplic>
            <chNFe>32180327837489000107650010000194681000xxxxxx</chNFe>
            <dhRecbto>2018-03-12T12:09:33-03:00</dhRecbto>
            <digVal>KTMUq0Aik5jMjZQlofYxBcSSxw4=</digVal>
            <cStat>395</cStat>
            <xMotivo>Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto</xMotivo>
        </infProt>
    </protNFe>
</nfeProc>

**Comment by olavocneto** [comment]
tag infNFeSupl > qrCode está a URL domínio www.sefaz.rs.gov.br. Está certo? Não deveria ser a que está no doc http://internet.sefaz.es.gov.br/informacoes/nfcEletronica/qrcode.php (aqui já não tenho certeza, só tentando ajudar :smile: )

**Comment by robmachado** [comment]
A informação do endereço do QRCode deve estar localizado no arquivo 
https://github.com/nfephp-org/sped-nfe/blob/master/storage/wsnfe_3.10_mod65.xml
Veja que nesse arquivo NÃO CONSTA Espirito Santo, ou seja faltam dados nesse arquivo referente ao ES, portanto nunca irá funcionar

**Comment by mrarticuno** [comment]
#357 Enviei, um pull request para adicionar a versao 4.00 da nota as urls de QRCode, curioso que se eu nao informar a urlChave na taginfNFeSupl ele pega por padrao o link do SVRS

**Comment by joeltonsilva** [comment]
> 
> 
> A informação do endereço do QRCode deve estar localizado no arquivo
> https://github.com/nfephp-org/sped-nfe/blob/master/storage/wsnfe_3.10_mod65.xml
> Veja que nesse arquivo NÃO CONSTA Espirito Santo, ou seja faltam dados nesse arquivo referente ao ES, portanto nunca irá funcionar

Estou passando pelo mesmo problema, v4.0.. onde posso completar tais informações faltantes?

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-nfe/blob/master/storage/wsnfe_4.00_mod65.xml

ES está la !!
