### ISSUE TITLE
Envio de Evento em Lote

### ISSUE THREAD

**Issue by rgarnica** [nfephp-org/sped-nfe#361]
A manifestação do destinatário permite enviar até 20 eventos em um mesmo lote, repetindo o grupo evento.

**Cenário Atual:**
A classe Tools permite apenas enviar um evento de manifestação por vez, através do método `sefazManifesta `que recebe a string com a chave da nota fiscal.

**Cenário Proposto:**
Implementar os métodos `sefazManifestaLote ` e `sefazEventoLote` que recebem um `array `de chaves para realizar o manifesto.

**Comment by robmachado** [comment]
@rgarnica 
Sua sugestão não é incompatível, com os procedimentos da SEFAZ. Mas até o momento, não vi a necessidade REAL de prover tal recurso. Em geral as manifestações de destinatário devem ser feitas UMA a UMA, pois deve haver intervenção HUMANA na grande maioria dos casos. O mesmo se refere aos outros EVENTOS como cancelamento ou carta de correção. Um outro  fator se deve a forma de retorno desses eventos, que retornariam em LOTE também, dificultando um pouco a leitura do retorno. Mas se você tiver casos em que isso DEVA ser enviado em LOTE sou todo OUVIDOS.

**Comment by rgarnica** [comment]
Sim, este é um método que não deve ser utilizado automaticamente e necessita de uma intervenção humana. Porém, em empresas com grande fluxo de notas fiscais de compra o processo de envio em lote facilita muito a operação do usuário e é mais consistente do que enviar várias requests para o web service da sefaz com os eventos separados.

**Comment by cbragato** [comment]
@robmachado concordo com o @rgarnica, citando um nicho de mercado que teria alta utilidade para esta demanda é o de Mercado Varejista, onde o volume médio de um mercado pequeno chega à 3000 nfs por mês. Estes mecanismos poderiam atender à uma fila de requisições. Tenho conhecimento inclusive de um escritório de contabilidade que faria uso frequente deste mecanismo.

**Comment by robmachado** [comment]
Está em fase de estruturação. Em breve disponível.

**Comment by cbragato** [comment]
Obrigado! Desculpe minha falta de experiência com este mecanismo do github.

**Comment by robmachado** [comment]
Adicionado método para envio de manifestação em LOTE

```php
$std = new stdClass();
    $std->evento[0] =  new stdClass();
    $std->evento[0]->chNFe = '02345678901234567890123456789012345678901234';
    $std->evento[0]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[0]->xJust = null;
    $std->evento[0]->nSeqEvento = 1;
    
    $std->evento[1] =  new stdClass();
    $std->evento[1]->chNFe = '12345678901234567890123456789012345678901234';
    $std->evento[1]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[1]->xJust = null;
    $std->evento[1]->nSeqEvento = 1;
    
    $std->evento[2] =  new stdClass();
    $std->evento[2]->chNFe = '22345678901234567890123456789012345678901234';
    $std->evento[2]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[2]->xJust = null;
    $std->evento[2]->nSeqEvento = 1;
    
    $std->evento[3] =  new stdClass();
    $std->evento[3]->chNFe = '32345678901234567890123456789012345678901234';
    $std->evento[3]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[3]->xJust = null;
    $std->evento[3]->nSeqEvento = 1;
    
    $std->evento[4] =  new stdClass();
    $std->evento[4]->chNFe = '42345678901234567890123456789012345678901234';
    $std->evento[4]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[4]->xJust = null;
    $std->evento[4]->nSeqEvento = 1;
    
    $std->evento[5] =  new stdClass();
    $std->evento[5]->chNFe = '52345678901234567890123456789012345678901234';
    $std->evento[5]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[5]->xJust = null;
    $std->evento[5]->nSeqEvento = 1;
    
    $std->evento[6] =  new stdClass();
    $std->evento[6]->chNFe = '62345678901234567890123456789012345678901234';
    $std->evento[6]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[6]->xJust = null;
    $std->evento[6]->nSeqEvento = 1;    
    
    $std->evento[7] =  new stdClass();
    $std->evento[7]->chNFe = '72345678901234567890123456789012345678901234';
    $std->evento[7]->tpEvento = 210210; //evento ciencia da operação
    $std->evento[7]->xJust = null;
    $std->evento[7]->nSeqEvento = 1;
    
    $std->evento[8] =  new stdClass();
    $std->evento[8]->chNFe = '72345678901234567890123456789012345678901234';
    $std->evento[8]->tpEvento = 210240; //evento não realizada
    $std->evento[8]->xJust = 'Entrega de produto não solicitado.';
    $std->evento[8]->nSeqEvento = 2;
    
    $std->evento[9] =  new stdClass();
    $std->evento[9]->chNFe = '82345678901234567890123456789012345678901234';
    $std->evento[9]->tpEvento = 210200; //evento confirmação
    $std->evento[9]->xJust = null;
    $std->evento[9]->nSeqEvento = 1;        
       

    $response = $tools->sefazManifestaLote($std);
```

**Comment by robmachado** [comment]
O limite são 20 manifestações por chamada ! se mais de 20 forem enviadas haverá uma Exception. 
Eu somente colocarei isso em STABLE após vocês testarem !!!

**Comment by cbragato** [comment]
Vou efetuar o teste na segunda feira! Tenho muitas notas a serem manifestadas para fazer este teste. Obrigado!

**Comment by robmachado** [comment]
Terá de usar o branch master para isso pois eu não subi uma release

**Comment by cbragato** [comment]
Sem problemas! Minha aplicação ainda está em fase de desenvolvimento! Dá pra testar numa boa!

**Comment by rgarnica** [comment]
Bom dia. Testado em homologação e funcionou perfeitamente. Muito obrigado.
