### ISSUE TITLE
Liga/desliga montar o QR Code?

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#362]
https://github.com/nfephp-org/sped-nfe/blob/aea8c7b1fcdb7585ce2a049723731dd975905c65/src/Common/Tools.php#L342

Bom dia, estou analisando a classe, entendi que ela monta automaticamente a tag *qrCode* dentro das informações suplementares. Mas... o código cliente da API já é responsável por montar o XML, então se este elemento já foi montado?

Em outras palavras, penso que poderíamos colocar um parâmetro/opção se ao assinar XML de NF-e modelo 65, queremos que a API monte ou não automaticamente o elemento do qrCode.

O que acham?

**Comment by robmachado** [comment]
Fernando;
O problema é que a assinatura deve ser feita antes da colocação do QRCode, mas podemos fazer com que se existir o QRCode ele não tente recriar, apenas adote o que já está lá.

**Comment by fmertins** [comment]
Olá, hum, entendi... Estou verificando aqui ainda, obrigado por enquanto!

**Comment by robmachado** [comment]
Mas sua colocação é válida ! 
Antes do fim de semana vou avaliar essa parte do código e prover uma alteração disso.
Uma pergunta você está passando o XML já ASSINADO também ?

**Comment by fmertins** [comment]
Pois é, estou passando o XML não assinado... Na prática, eu montei todo o XML, modelo 65, e com o campo ZX02 qrCode já populado, então chamei a API para assinar o XML. Como não passei no config JSON da API os dois parametros de CSC, deu erro. Daí fui ver o método sign da Tools e quando é modelo 65 já adiciona a tag, mas pensei, pq...? Se eu que monto todo o XML... :-)

**Comment by fmertins** [comment]
Roberto, não seria apenas o caso de refatorar o método sigNFe($xml) colocando um segundo parâmetro bool se quero que adicione o qrCode sim/não?

**Comment by robmachado** [comment]
Não ! o mais indicado é verificar a existência do QRCode se existir usa o que foi passado (certo ou errado)

**Comment by robmachado** [comment]
Mas é facil fazer isso !!! Vou providenciar  !!

**Comment by fmertins** [comment]
Olá, posso tentar fazer um PR, quer ajuda?

**Comment by robmachado** [comment]
Demorou ! :+1:

**Comment by robmachado** [comment]
Eu fiz já uma correção! Sobre isso ...
Se existir a tag <infNFeSupl>, ela será deixada e não haverá tentativa de recriar o QRCode.
Apenas fique atento pois NÃO será corrigido o QRCode para a nova versão inclusive.

**Comment by robmachado** [comment]
@fmertins Gostaria que você fizesse alguns testes com essa alteração.

**Comment by fmertins** [comment]
Boa tarde, ok obrigado, estou testando aqui :+1: Também fiz mais um PR com melhorias simples.

**Comment by robmachado** [comment]
Opa Fernando ! Toda ajuda será sempre muito bem vinda Grato !!
