### ISSUE TITLE
Erro na validação ao emitir NF-e com informações de DI + Pedido de Compra

### ISSUE THREAD

**Issue by avandrevitor** [nfephp-org/sped-nfe#366]
**Problema :** Ao tentar emitir uma NF-e com uma Declaração de Importação e informar os dados do Pedido de Compra o seguinte erro é retornado : 

````
validator exception:This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}DI': This element is not expected. Expected is one of ( {http://www.portalfiscal.inf.br/nfe}nFCI, {http://www.portalfiscal.inf.br/nfe}rastro, {http://www.portalfiscal.inf.br/nfe}veicProd, {http://www.portalfiscal.inf.br/nfe}med, {http://www.portalfiscal.inf.br/nfe}comb, {http://www.portalfiscal.inf.br/nfe}nRECOPI, {http://www.portalfiscal.inf.br/nfe}arma ).  
````

**Como reproduzir o erro :** 
- Instancie a Classe NFePHP\NFe\Tools
- Instancie a Classe NFePHP\NFe\Make
- Faça as atribuições e crie as tags para Capa da NFe
- Faça as atribuições e crie as tags para os Itens da NFe
-- Neste ponto, ao criar a **tag prod** informe também os dados de **pedido** e **item do pedido**, exemplo:

````php
<?php
//...
$std = new stdClass();
$std->item = 1; //item da NFe
$std->cProd;
$std->cEAN;
$std->xProd;
$std->NCM;
$std->cBenef;
$std->EXTIPI;
$std->CFOP;
$std->uCom;
$std->qCom;
$std->vUnCom;
$std->vProd;
$std->cEANTrib;
$std->uTrib;
$std->qTrib;
$std->vUnTrib;
$std->vFrete;
$std->vSeg;
$std->vDesc;
$std->vOutro;
$std->indTot;
$std->xPed = "201803100123";
$std->nItemPed = 1;
$std->nFCI;
$elem = $nfe->tagprod($std);
//...
````
-- Crie também a **tag DI** com os valores correspondentes: 
````php
<?php
//...
$std = new stdClass();
$std->item = 1; //item da NFe
$std->nDI;
$std->dDI;
$std->xLocDesemb;
$std->UFDesemb;
$std->dDesemb;
$std->tpViaTransp;
$std->vAFRMM;
$std->tpIntermedio;
$std->CNPJ;
$std->UFTerceiro;
$std->cExportador;
$elem = $nfe->tagDI($std);
//...
````
- continue com o processo de emissão chamando o método **signNFe**  passando o xml gerado : 

````php
<?php
// .... 
$tools = new Tools($configJson, Certificate::readPfx($content, $password));
$nfe = new NFePHP\NFe\Make();
// ... código que cria as tags da Capa da NFe
// ... código que cria as tags dos Itens da capa, incluindo as tags de produto e di.
$tools->signNFe($nfe->getXML());
````
**Análise do Problema** : Inicialmente acreditei que os dados da Tag DI foram informados erroneamente, porém após uma série de testes e comparativos com outras notas já emitidas em produção por outro sistema de emissão, percebi que os dados e a tag estão corretos.

Continuando com o debug obtive os seguintes códigos com o sistema utilizando **sped-nfe** e o outro sistema de emissão de notas.

Exemplo de XML gerado com o sistema **utilizando a sped-nfe**:

````xml 
...
<prod>
    <cProd>A7654321</cProd>
    <cEAN>SEM GTIN</cEAN>
    <xProd>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</xProd>
    <NCM>32089010</NCM>
    <CFOP>3556</CFOP>
    <uCom>KGl</uCom>
    <qCom>30.0000</qCom>
    <vUnCom>738.0096667</vUnCom>
    <vProd>22140.29</vProd>
    <cEANTrib>SEM GTIN</cEANTrib>
    <uTrib>KGl</uTrib>
    <qTrib>30.0000</qTrib>
    <vUnTrib>738.0096667</vUnTrib>
    <vOutro>123.12</vOutro>
    <indTot>1</indTot>
    <xPed>201803100123</xPed>
    <nItemPed>1</nItemPed>
    <DI>
        <nDI>21800123123</nDI>
        <dDI>2018-01-16</dDI>
        <xLocDesemb>VOLTA REDONDA</xLocDesemb>
        <UFDesemb>RJ</UFDesemb>
        <dDesemb>2018-01-16</dDesemb>
        <tpViaTransp>4</tpViaTransp>
        <vAFRMM>0.00</vAFRMM>
        <tpIntermedio>1</tpIntermedio>
        <cExportador>123475</cExportador>
        <adi>
            <nAdicao>1</nAdicao>
            <nSeqAdic>1</nSeqAdic>
            <cFabricante>A123456</cFabricante>
        </adi>
    </DI>
</prod>
...
````
Exemplo de XML gerado com o sistema **sem a utilização da sped-nfe**:

````xml 
...
<prod>
    <cProd>A7654321</cProd>
    <cEAN>SEM GTIN</cEAN>
    <xProd>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</xProd>
    <NCM>32089010</NCM>
    <CFOP>3556</CFOP>
    <uCom>KGl</uCom>
    <qCom>30.0000</qCom>
    <vUnCom>738.0096667</vUnCom>
    <vProd>22140.29</vProd>
    <cEANTrib>SEM GTIN</cEANTrib>
    <uTrib>KGl</uTrib>
    <qTrib>30.0000</qTrib>
    <vUnTrib>738.0096667</vUnTrib>
    <vOutro>123.12</vOutro>
    <indTot>1</indTot>
    <DI>
        <nDI>21800123123</nDI>
        <dDI>2018-01-16</dDI>
        <xLocDesemb>VOLTA REDONDA</xLocDesemb>
        <UFDesemb>RJ</UFDesemb>
        <dDesemb>2018-01-16</dDesemb>
        <tpViaTransp>4</tpViaTransp>
        <vAFRMM>0.00</vAFRMM>
        <tpIntermedio>1</tpIntermedio>
        <cExportador>123475</cExportador>
        <adi>
            <nAdicao>1</nAdicao>
            <nSeqAdic>1</nSeqAdic>
            <cFabricante>A123456</cFabricante>
        </adi>
    </DI>
    <xPed>201803100123</xPed>
    <nItemPed>1</nItemPed>
</prod>
...
````
Analisando o método **isValid** da classe **NFePHP\NFe\Common\Tools**, percebi que em um determinado momento ele chama o arquivo *leiauteNFe_v3.10.xsd* ou *leiauteNFe_v4.00.xsd* dependendo da versão da nota.

Olhando para o trecho responsável pela validação da **tag prod** podemos perceber nos dois arquivos, o uso de **xs:complexType** + **xs:sequence**  o que obriga a sequência das tags geradas seguir uma ordem especifica, que seria essa: 

![trecho do xsd](https://i.imgur.com/CNspkSM.png)

Desse jeito ao tentar construir uma NF-e com uma Declaração de Importação e informar os dados do Pedido de Compra ocorre o erro citado no início, conforme o exemplo do XML gerado **utilizando a sped-nfe** onde a **tag DI** e a **tag detExport** não são corretamente construidas na sequência exigida pelo XSD.

**Comment by avandrevitor** [comment]
@robmachado poderia dar uma ajuda com isso ?

**Comment by robmachado** [comment]
Claro meu amigo ! Esse parece ser um BUG vou ver isso hoje

**Comment by robmachado** [comment]
Evander;
Eu fiz o teste aqui gerando o DI e ele foi colocado e validado corretamente com o XSD na posição correta conforme layout 3.10. Ao criar as TAGs é necessário passar os VALORES adequados a cada campo.

**Comment by srdavidsilva** [comment]
Ola, @robmachado , estou tendo os mesmos desafios, porém, com a API da WEBMania, estou considerando deixar de usar a API e implementar com a nfephp também.
Sua resposta não foi muito clara pra mim, você conseguiu gerar a nota de importação ai normalmente? 
Seria então um problema de coerência nos dados, no caso do Envader?

**Comment by robmachado** [comment]
Sim a NFe versão 3.10 foi gerada corretamente usando a versão atual da classe Make, as tags na posição correta e validadas com o XSD

**Comment by avandrevitor** [comment]
@robmachado eu aprofundei os testes que utilizei para criar está issue e acredito ter entendido melhor o que está ocorrendo.

**Asserções:** 
- [x] Se você preencher os dados da tag prod, DI, Pedido e Item Pedido, você terá um XML **válido**.
- [x] Se você preencher os dados da tag prod, Pedido e Item Pedido e não preencher a DI,você terá um XML  **válido**.
- [x] Se você preencher os dados da tag prod, preencher a DI e não preencher os dados de Pedido e Item pedido terá uma XML  **válido**.
- [x] Se você preencher os dados da tag prod, preencher a DI, não preencher o *Número do Pedido*, mas preencher o número do *Item Pedido*, você terá um XML **inválido**.

Inválido por não apresentar as tags na sequência certa, não por causa de sintaxe.

Encontrei esse trecho na classe NFePHP\NFe\Make ( ~ linha 6806 ) que acredito que seja o responsável por este comportamento.
````php
<?php
//...
        //insere DI
        foreach ($this->aDI as $nItem => $aDI) {
            $prod = $this->aProd[$nItem];
            foreach ($aDI as $child) {
                $node = $prod->getElementsByTagName("xPed")->item(0);
                if (!empty($node)) {
                    $prod->insertBefore($child, $node);
                } else {
                    $this->dom->appChild($prod, $child, "Inclusão do node DI");
                }
            }
            $this->aProd[$nItem] = $prod;
        }
//...
````
Estou analisando o motivo agora da minha integração trazer nestes casos, aonde o número do pedido é vazio ou nulo. Porém eu acredito que poderia haver alguma tratativa nesta parte para evitar esse tipo de erro ou apresentar uma mensagem mais coerente com o que ocorreu. 

Lendo a documentação Técnica da NFe, não existe ( apesar dos nomes dos campos ) relação, eu poderia até passar o número do Item do Pedido, sem o Pedido ( apensar de isso não fazer nenhum sentido ).

Enfim minha preocupação agora é mais a de que nenhum outro desenvolvedor demore tanto tempo quanto o que eu levei para achar essa agulha no palheiro.

**Comment by avandrevitor** [comment]
Outra coisa que não entendi foi o esse **Envader** que você @robmachado  e o @srdavidsilva estão falando.

**Comment by robmachado** [comment]
hehehe !!! foi pressa ao ler seu ID no git @avandrevitor  !!!

Me desculpe por isso ANDRÉ :+1:

**Comment by robmachado** [comment]
Acredito que essa falha já foi resolvida!
