### ISSUE TITLE
Conflitos Composer Laravel 4.2

### ISSUE THREAD

**Issue by sr2ds** [nfephp-org/sped-nfe#368]
Ao rodar o `composer require nfephp-org/sped-nfe` estou tendo a seguinte saída.
Sei que não haverão facades pro Laravel, porém, (talvez eu esteja errado) a instalação deve rolar normalmente, certo?

`
Problem 1
    - Conclusion: don't install nfephp-org/sped-nfe v5.0.41
    - Conclusion: remove symfony/console v2.7.43
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.7.43].
    - symfony/yaml v3.4.1 conflicts with symfony/console[v2.7.43].
    - symfony/yaml v3.4.2 conflicts with symfony/console[v2.7.43].
    - symfony/yaml v3.4.3 conflicts with symfony/console[v2.7.43].
    - symfony/yaml v3.4.4 conflicts with symfony/console[v2.7.43].
    - symfony/yaml v3.4.5 conflicts with symfony/console[v2.7.43].
    - symfony/yaml v3.4.6 conflicts with symfony/console[v2.7.43].
    - Installation request for symfony/console (installed at v2.7.43) -> satisfiable by symfony/console[v2.7.43].

    - Conclusion: remove symfony/yaml v2.4.10|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6
    - Installation request for symfony/yaml (installed at v2.4.10) -> satisfiable by symfony/yaml[v2.4.10].
    - Installation request for nfephp-org/sped-nfe ^5.0 -> satisfiable by nfephp-org/sped-nfe[v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.16, v5.0.17, v5.0.18, v5.0.19, v5.0.2, v5.0.20, v5.0.21, v5.0.22, v5.0.23, v5.0.24, v5.0.25, v5.0.26, v5.0.27, v5.0.28, v5.0.29, v5.0.3, v5.0.30, v5.0.31, v5.0.32, v5.0.33, v5.0.34, v5.0.35, v5.0.36, v5.0.37, v5.0.38, v5.0.39, v5.0.4, v5.0.40, v5.0.41, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].
`

**Comment by robmachado** [comment]
Bom ai começa a ficar problemático !!!
Não dá para satisfazer o SEU composer com o LARAVEL 4.x e de outros com o LARAVEL 5.x  !!!

**Comment by srdavidsilva** [comment]
@robmachado perdão, não me expressei bem.
Sei que não o recurso não deva satisfazer tudo, mas você tem alguma ideia de como eu possa resolver isso?

**Comment by robmachado** [comment]
Pode haver alguma solução mas ela depende de coisas manuais, como fazer um FORK do projeto sped-nfe e alterar o composer do SEU fork e remover o symfony-yml dele. E usar o SEU fork ao invés do repositório principal. 
Mas eu vou ver uma outra forma. AGUARDE!

**Comment by robmachado** [comment]
Provavelmente a melhor solução será alterar seu composer para tentar satisfazer esses conflitos e isso não é algo facil para fazer , mas estou removendo as chamadas ao synfony/yaml dos meus pacotes. Tendo em vista que praticamente não são usados e isso deverá resolver o seu problema.

**Comment by robmachado** [comment]
O release sped-nfe:v5.0.44  não contêm mais o synfony/yaml e portanto não devem ocorrer esses conflitos com o Laravel. Meu conselho é remover a pasta "vendor" da sua aplicação e usar o composer install para instalar novamente as dependências.
