### ISSUE TITLE
Propriedade para link de consulta da nota

### ISSUE THREAD

**Issue by mrarticuno** [nfephp-org/sped-nfe#373]
Alguem pode me informar se existe alguma propriedade na montagem da nota que eu consulto o link para enviar o cliente direto para o site de consulta de nfce da receita ? tipo ao que tem na tag do XML

Procurei na documentacao e nas propriedades mas em lugar nenhum encontei esse link e não queria ter que pegar no xml porque teria que fazer uma gambiarra danada.

**Comment by robmachado** [comment]
Hãã ????? O que ??? 

Tem uma lista de paginas de consultas 
https://github.com/nfephp-org/sped-nfe/blob/master/storage/uri_consulta_nfce.json

**Comment by mrarticuno** [comment]
@robmachado Desculpe se não me fiz claro, após a assinatura do XML o link de consulta da nota ja esta disponível na tag qrCode, porém quando tento acessar a propriedade ele me retorna NULL, teria alguma forma de acessar essa URL de consulta direta da nota que esta disponivel na tag qrCode sem ter que fazer o parse no XML.

**Comment by robmachado** [comment]
Você teria de reconstruir a tag do QRCode !!! mas para isso são necessários os dados da NFCe.
É imensamente mais fácil e simples, LER essa informação do XML usando o DOM

**Comment by mrarticuno** [comment]
@robmachado Entendi, pensei que houvesse alguma propriedade que guardava essa informação obrigado pela elucidação. 👍
