### ISSUE TITLE
Desoneração de ICMS nos valores totais

### ISSUE THREAD

**Issue by jsalmeida1101** [nfephp-org/sped-nfe#374]
Boa tarde! 
Estou gravando uma nota, e para a tag ICMSTot estava deixando que os valores fossem gerados diretamente pela API. 
Mas aí me deparei com o seguinte problema: tenho um item que está gerando com Desoneração do ICMS, segundo o manual de preenchimento, o valor total da NF deve diminuir desoneração, porém a API não faz isso no momento. Aí fica a sugestão de alteração, ou posso fazer um Pull request.

Obs.: não sei se aqui era o melhor lugar para falar isso, peço desculpas pela "noobice" no git.

Att,
Jeferson Almeida

**Comment by robmachado** [comment]
Vou ver o que é possível fazer nesse caso para tentar automatizar.

**Comment by jsalmeida1101** [comment]
O que fiz localmente aqui foi incluir  `- $this->stdTot->vICMSDeson` na linha 6933 da classe Make e passou

**Comment by avandrevitor** [comment]
@jsalmeida1101 passei por questões semelhantes, mas acredito que a sped-nfe deveria ser apenas um integrador com a plataforma da Sefaz. O problema que você questionou deveria ser resolvido por uma segunda lib que teria como contexto o domínio de negócio da NF-e.

**Comment by jsalmeida1101** [comment]
@robmachado, dei uma olhada no manual aqui e percebi que mais alguns valores não estão sendo somados atualmente. Segue link do print da última NT [http://prntscr.com/j1cy60](http://prntscr.com/j1cy60).

@avandrevitor, a API oferece duas possibilidades, informar um stdClass com os valores manuados ou gerar automaticamente, no momento to informando manualmente os dados, mas só comuniquei o problema em questão, para aqueles usam o método automático da API.

**Comment by avandrevitor** [comment]
@jsalmeida1101 ficou claro, apenas quis pontuar que essa de funcionalidade caberia melhor a uma outra solução, como expliquei anteriormente. Achei que seria uma boa oportunidade para discutir isso.
