### ISSUE TITLE
Método sefazConsultaChave da NF-e MG retorna erro 403 Forbidden

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-nfe#375]
Bom dia!

Mais uma vez, gostaria de parabenizar a todos os envolvidos no projeto! Excelente trabalho e de alto nível!

Como é a manutenção do arquivo \sped-nfe-master\storage\wsnfe_4.00_mod55.xml?

Estamos com um erro sendo retornado no método sefazConsultaChave para MG:

_An error occurred while trying to communication via soap, [https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsulta4]HTTP/1.1 403 Forbidden Date: Tue, 03 Apr 2018 09:53:15 GMT Server: Apache/2.2.32 (Unix) mod_ssl/2.2.32 OpenSSL/1.0.2k DAV/2 mod_jk/1.2.41 Content-Length: 228 Content-Type: text/html; charset=iso-8859-1_

Isso é corrigido alterando de NFeConsulta4 para NFeConsultaProtocolo4

DE:
<NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsulta4" version="4.00">https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsulta4</NfeConsultaProtocolo>
PARA
<NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsultaProtocolo4" version="4.00">https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4</NfeConsultaProtocolo>

DE:
<NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsultaProtocolo4" version="4.00">https://nfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4</NfeConsultaProtocolo>
PARA:
<NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsultaProtocolo4" version="4.00">https://nfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4</NfeConsultaProtocolo>

Segue o novo portal NF-e de MG com os caminhos corretos: http://www.sped.fazenda.mg.gov.br/spedmg/nfe/webservices/

Obrigado!
Ramon Loureiro

**Comment by robmachado** [comment]
Obrigado pela ajuda. Assim que der faço a alteração

**Comment by robmachado** [comment]
Corrigido !
