### ISSUE TITLE
Validação do XML

### ISSUE THREAD

**Issue by maiconkamiya** [nfephp-org/sped-nfe#394]
Estou tendo problema com a validação do xml, esta apresentando esses erros.

Interessante é que quando estou rodando a aplicação no servidor local "minha maquina" ele não apresenta este erro, porem ao rodar a aplicação no servidor de hospedagem já apresenta este erro.

Alguém consegue me ajudar1

Usando layout 4.00 schemas nfe_v4.00.xsd

Element '{http://www.portalfiscal.inf.br/nfe}uCom': [facet 'pattern'] The value 'SR' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}uCom': 'SR' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}uTrib': [facet 'pattern'] The value 'SR' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}uTrib': 'SR' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}cCor': [facet 'pattern'] The value '02' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}cCor': '02' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}pot': [facet 'pattern'] The value 'NA' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}pot': 'NA' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}cilin': [facet 'pattern'] The value 'NA' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}cilin': 'NA' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}nMotor': [facet 'pattern'] The value 'NA' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}nMotor': 'NA' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}CMT': [facet 'pattern'] The value 'NA' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}CMT': 'NA' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}esp': [facet 'pattern'] The value 'SR' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}esp': 'SR' is not a valid value of the local atomic type.

**Comment by robmachado** [comment]
Provisóriamente localize 
schemas/PL_009_V4/tiposBasico.v4.00.xsd e substitua 
[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}
por
[!-ÿ]{1}[ -ÿ]*[!-ÿ]{1}|[!-ÿ]{1}

Esse pattern do original não funciona em todos as versões do PHP. Estou providenciando a correção no repositório.

**Comment by maiconkamiya** [comment]
Deu certo, Obrigado!

**Comment by avandrevitor** [comment]
Como disse o @robmachado , provisoriamente você pode incluir isso em seu composer.json na directiva de scripts:

````json
  "scripts": {
    "post-update-cmd": [
      "/usr/bin/find ./vendor/nfephp-org/sped-nfe/schemes/ -type f | xargs sed -i 's/\\]{0,}\\[/\\]*\\[/g' $1"
    ]
  }
````

**Comment by robmachado** [comment]
Boa André;

Resta saber se não irá quebrar alguma outra regra, pois você genericamente está substituindo o pedaço de string que dá o erro.
E esse comando somente iria funcionar em ambiente LINUX (ou OSx)
Talvez uma outra solução com uma outra diretiva pudesse funcionar melhor por exemplo antes de eu subir uma alteração. Vou pensar nisso !!!

**Comment by avandrevitor** [comment]
@robmachado sim, a substituição via sed está genérica, porém está testada, sem efeitos colaterais.

acho que poderiamos incluir uma docker ao projeto o que acha ?!

**Comment by robmachado** [comment]
André;
As duas opções são bem interessantes, porém acredito que um container DOCKER seja mais viável para um APP e não sei se seria viável, para a API a não ser para fins de desenvolvimento. 
Vamos fazer o seguinte, primeiro vamos incorporar o comando "post-update" no composer, isso já ajudaria a fazer esse processo. Pois a cada alteração de layout isso deve ser feito (nos novos XSD). 
Quanto ao DOCKER ainda estou em duvida mas podemos continuar a falar e testar isso, nada tenho contra (muito pelo contrário sou um fâ e usuário do DOCKER).

**Comment by cleitonsoares** [comment]
Olá, gostaria de fazer um adendo a operação de consulta no arquivo **wsnfe_4.00_mod55**.xml, constatado que o serviço **NfeConsultaProtocolo** deve ter a operação **NFeConsultaProtocolo4** no lugar de apenas **NFeConsulta4**;

**Comment by robmachado** [comment]
@cleitonsoares, por favor abra esse tipo de discussão, de um assunto diferente em um ISSUE diferente.
E indique melhor ONDE ? está o problema, se já tiver alterado e TESTADO pode fazer um PR
