### ISSUE TITLE
Erro ao gerar DANFE, $tPagNome indefinida

### ISSUE THREAD

**Issue by clodoaldobragatolopes** [nfephp-org/sped-nfe#398]
Ao atualizar o projeto, deparei com a mensagem de que a variável em questão não estava definida. Isto ocorreu no arquivo nfephp-org/sped-da/src/Legacy/Common.php na linha 535. Localmente fiz a correção declarando a variável no topo da função, antes do Switch Case.

**Comment by robmachado** [comment]
Isso não pertence a esse repositório e sim ao sped-da
