### ISSUE TITLE
install

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-nfe#399]
Hoje estou na branche v4.1 , ja estamos na 4.0 na nfe qual devo seguir porque a que eu puxei agora não tem um install e nem um make de como vai ficar para passar os parametros para gerar o xml tentei mexer mas parece que esta incompleta essa verão master ou estou errado , ja da para usar essa nova versão disponibilizada vai ter um install ?

**Comment by robmachado** [comment]
Não Cacio use o composer a RELEASE atual é 5.0.44 !!!
A versão antiga não está mais sendo mantida .. e isso faz tempo
