### ISSUE TITLE
Ao consultar uma NF as vezes não retorna o atributo protNFe

### ISSUE THREAD

**Issue by mprandot** [nfephp-org/sped-nfe#409]
* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4

## Comportamento esperado
O retorno da consulta deveria ser igual ao abaixo:
{#7775 ▼
  +"attributes": {#7774 ▶}
  +"tpAmb": "2"
  +"verAplic": "RS201805250750"
  +"nRec": "431002194435102"
  +"cStat": "104"
  +"xMotivo": "Lote processado"
  +"cUF": "43"
  +"dhRecbto": "2018-06-01T09:03:11-03:00"
  +"protNFe": {#7777 ▼
    +"attributes": {#7776 ▼
      +"versao": "4.00"
    }
    +"infProt": {#7778 ▼
      +"tpAmb": "2"
      +"verAplic": "RS201805250750"
      +"chNFe": "43180620606410000198550750000006621000006628"
      +"dhRecbto": "2018-06-01T09:03:11-03:00"
      +"nProt": "143180004348767"
      +"digVal": "XVXb2vROT2UbKuUUI5uBvvP2XCs="
      +"cStat": "100"
      +"xMotivo": "Autorizado o uso da NF-e"
    }
  }
}

## Comportamento Atual
As vezes a consulta não retorna o atributo **protNFe**
+"attributes": {#7774 ▶}
  +"tpAmb": "2"
  +"verAplic": "RS201805250750"
  +"nRec": "431002194435102"
  +"cStat": "104"
  +"xMotivo": "Lote processado"
  +"cUF": "43"
  +"dhRecbto": "2018-06-01T09:03:11-03:00"

## Passos para reproduzir
Isso acontece de forma totalmente aleatória.

## Contexto (Ambiente)

Estou realizando o envio de uma NF-e, faço a consulta para pegar informações sobre seu envio.

**variável $retornoConsulta é o objeto que deveria possuir o protNFe**

$idLote = $idLote = str_pad($serie->numero, 15, '0', STR_PAD_LEFT);
$retorno = $nfeTools->sefazEnviaLote([$xmlAssinado], $idLote);
$standardize = new Standardize();
$std = $standardize->toStd($retorno);
 ...   
$recibo = $std->infRec->nRec;
$protocolo = $nfeTools->sefazConsultaRecibo($recibo);
$retornoConsulta = $standardize->toStd($protocolo);
$codResposta = $retornoConsulta->protNFe->infProt->cStat;
... 
throw new \Exception($codResposta . ' - ' . $retornoConsulta->protNFe->infProt->xMotivo, $codResposta);

**Comment by robmachado** [comment]
Bom para começar isso não é um BUG 

104|Lote processado: Provavelmente o web service de notas fiscais esta congestionado ou por algum outro motivo, a nota foi recebida mais esta aguardando o protocolo de autorização, após aguardar e o erro persistir consulte se a mesma já não se encontra emitida, caso já estiver emitida entrar em contato com seu suporte para ajustar o status da nota no sistema;

**Comment by robmachado** [comment]
Isso é normalmente causado pela carga no servidor da SEFAZ, por isso essa aleatoriedade.
Ponha essa consultas em uma FILA e refaça a requisição depois de alguns segundos.
Um erro muito comum que muitos cometem é enviar e logo em seguida tentar pegar o protocolo, como existe um tempo para esse processamento e que NÃO DEPENDE de nós, não podemos fazer desse jeito.

**Comment by mprandot** [comment]
Ótimo, não sabia se era um bug ou se podia ser colocado como, mas enfim... Muito obrigado, vamos corrigir.

**Comment by robmachado** [comment]
@mprandot 
Aparentemente você está usando um framework (talvez Laravel) , use os recursos do framework para trabalhar com filas e repetições.

**Comment by mprandot** [comment]
Sim, é Laravel, vou utilizar. Obrigado.

**Comment by robmachado** [comment]
De qualquer forma eu gostei muito da forma que apresentou ou problema muito claro e direto e isso ajuda bastante a identificar a causa. Gostaria que todos que criam ISSUES fossem como você
Abraço

**Comment by mprandot** [comment]
Só segui o script kkkk Abraço @robmachado e novamente, obrigado!
