### ISSUE TITLE
Automatizar a geração da chave NFe e o digito verificador

### ISSUE THREAD

**Issue by JulianoAmaralChaves** [nfephp-org/sped-nfe#412]
requisição de funcionalidade  

- Versão do leiaute: 3.1 e 4.0

Alterar a função tagide(stdClass $std) para não solicitar o campo cDV e a própria função tagide(stdClass $std)  pegar o valor através do id informado na função taginfNFe(stdClass $std), caso o id não tenha sido informado na função taginfNFe(stdClass $std) então deve gerar o id com os dados informado na função tagide(stdClass $std) e calcular o digito verificador para atribuir ao campo cDV, feito isso caso o id não tenha sido informado anteriormente na função  taginfNFe(stdClass $std), então deve-se atribuir o id gerado pela função tagide(stdClass $std), desta forma fica mais automatizado e evita que seja necessário ter que montar a chave e calcular o digito verificador

**Comment by robmachado** [comment]
Preparando !

**Comment by robmachado** [comment]
OK deve estar funcional
