### ISSUE TITLE
Aceitar série zerada para inutilização da nota fiscal

### ISSUE THREAD

**Issue by JorgeRamosLauand** [nfephp-org/sped-nfe#417]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [*] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.00

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado

Estamos tendo problemas para inutilizar uma nota fiscal mercantil com a série zerada. Vimos que no aplicativo Tools a verificação da variável quando se utiliza de zero é considerado verdadeiro saindo da função como erro.

<! --- Diga-nos o que deve acontecer ->
Aceitar a série zerada

## Comportamento Atual
Não aceita série zero

## Solução possível
Aplicativo Tools 

Linha 195 -> if ( **empty($nSerie)** || empty($nIni) || empty($nFin) || empty($xJust)) { era if (!empty($nSerie) || empty($nIni) || empty($nFin) || empty($xJust)) {

Sugerimos utilizar em vez de empty o comando isset()
## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Isso já foi corrigido no ultimo release !
