### ISSUE TITLE
[bug] Erro no campo modBC do ICMSSN900 

### ISSUE THREAD

**Issue by fgeraldi91** [nfephp-org/sped-nfe#423]
Estou aqui para avisar que achei um erro no campo modBC do ICMSSN900, o campo não estava aceitando o valor "0"(Margem Valor Agregado (%)). Aparentemente o erro está na linha 4230 do Make.php, troquei FALSE por TRUE no meu código e funcionou.

**Comment by robmachado** [comment]
Indique qual é essa TAG ??

**Comment by robmachado** [comment]
Sim .. já identifiquei o erro como essa tag faz parte de um grupo opcional a classe está marcada como false, porem se for passado um dado, mesmo que seja ZERO ela deve ser inclusa. Correção em andamento ...

**Comment by robmachado** [comment]
Corrigido com o release v5.0.53
