### ISSUE TITLE
Prévisualização DANFE

### ISSUE THREAD

**Issue by thiagoreri** [nfephp-org/sped-nfe#425]
Não encontrei a possibilidade de prévisualização de DANFE.

**Comment by robmachado** [comment]
hããã !!!! É só gerar o PDF, funciona com a NFe protocolada ou não

**Comment by thiagoreri** [comment]
Certo, mas vem com a marca d'agua sem Valor Fiscal?

**Comment by robmachado** [comment]
É claro que SIM ... não tem o protocolo de autorização então NÃO TEM VALOR FISCAL
