### ISSUE TITLE
Retorno [450 - Modelo da NF-e diferente de 55] PARA NFC-e [Modelo 65]

### ISSUE THREAD

**Issue by brunowoisa** [nfephp-org/sped-nfe#430]
* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: NFC-e 4.00

## Comportamento esperado
RETORNO ESPERADO NO MOMENTO DA CONSULTA (sefazConsultaRecibo): 100 - Autorizado o uso da NF-e.

## Comportamento Atual
RETORNO NO MOMENTO DA CONSULTA (sefazConsultaRecibo): 450 - Modelo da NF-e diferente de 55.

## Solução possível
Segundo o arquivo cStat contido no docs, diz-se que: "A chave de acesso é de outra autorizadora".

## Passos para reproduzir
1 Gerar um xml válido para uma NFC-e mod 65
2 Enviar o xml, e obter o retorno "103 - Lote recebido com sucesso"
3 Consultar o recibo $protocolo = $tools->sefazConsultaRecibo($recibo);
4 Obtém-se o retorno mencionado: 450 - Modelo da NF-e diferente de 55 (obviamente, pois trata-se de uma NFC-e - mod 65)

## Contexto (Ambiente)
Estado PR
Ambiente HOMOLOGAÇÃO

NÃO TESTEI EM PRODUÇÃO, VISTO QUE NÃO ERA O COMPORTAMENTO ESPERADO EM HOMOLOGAÇÃO,

**Comment by rafanake** [comment]
Mesmo problema aqui, porém utilizando o estado de SP, alguma solução?

**Comment by robmachado** [comment]
Vocês setaram o modelo na classe tools, antes de tentar o envio ?

$tools>model(65);

**Comment by rafanake** [comment]
Era exatamente este o problema, muito obrigado @robmachado !
Como o modelo estava setado direto no XML não pensei que fosse necessário adicionar algo no Tools... 
Não seria possível pegar o valor direto da XML ou até mesmo remover o valor padrão de 55, desta maneira os usuários saberiam da necessidade de informar o modelo no Tools!

De qualquer forma, muito obrigado!

**Comment by robmachado** [comment]
Infelizmente isso não é possível pois outras operações iriam requer essa informação que nem sempre está disponivel com a consulta do recibo por exemplo. Além disso poderia levar a outros erros. 
Mas é possível fazer algumas verificações e disparar uma Exception em caso de divergencia
