### ISSUE TITLE
Erro de Comunicação NF-e 4.0 no serviço de consulta de nota fiscal por chave (Consulta de protocolo)

### ISSUE THREAD

**Issue by KelwinMello** [nfephp-org/sped-nfe#442]
## SITUAÇÃO
Quando realizo a operação de consulta de uma NFC-e utilizando o método **Tools->sefazConsultaChave** tenho como resposta erro 500.

## PROBLEMA
Descobri que o problema é que o método para consulta ( operation ) está errado, está consultando com **NFeConsulta4** quando deveria ser **NFeConsultaProtocolo4**.

Estou utilizando o sefaz virtual, porque sou do estado do Rio, mas acredito que o problema esteja acontecendo ao tentar consultar pela chave em todos os servidores virtuais. Como pode ver nos links abaixo, tanto em homologação, quanto em produção, o método para consulta em todos é **NFeConsultaProtocolo4**:
http://nfce.encat.org/desenvolvedor/webservices-p/
http://nfce.encat.org/desenvolvedor/webservices-h/

## SOLUÇÃO
A correção pode ser feita por alterar o arquivo **wsnfe_4.00_mod65.xml** e **wsnfe_4.00_mod55.xml** alterando operation **NFeConsulta4** por **NFeConsultaProtocolo4** para cada servidor.

No lugar de 
`operation="NFeProtocolo4"` utilizar `operation="NFeConsultaProtocolo4"`

**Comment by robmachado** [comment]
Acredito que esteja corrigido esse caso
