### ISSUE TITLE
Schema PL_009_V4 desatualizado

### ISSUE THREAD

**Issue by KelwinMello** [nfephp-org/sped-nfe#443]
## SITUAÇÃO/PROBLEMA
O XML da nota não passa na validação do schema indicando erro na tag **cobr -> fat -> vDesc** quando o informo o valor **0.00**.

A sefaz não aceita mais o campo **vDesc** sem valor, se ele ficar vazio a sefaz retorna:
**Rejeição 905: Campos do grupo Fatura não informados**

## SOLUÇÃO

O schema mais recente permite **cobr -> fat -> vDesc** com valor **0.00**.

Atualizar o schema PL_009_V4 para o mais atual, que se encontra disponível na sefaz para download:
http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=

**Comment by victorvilella** [comment]
Pode atualizar o projeto pois os schemas já foram atualizados.

**Comment by feinfo** [comment]
Bom dia, Atualizei apenas o schema como sugerido, mas começou a dar erro no campo uCom e uTrib quando eu envio "PC", e pelo que vi na tabela de Unidade comercial está correto. Em fim, consegui mandar a tag vDesc 0.00 mas continua dando o mesmo erro. 
![image](https://user-images.githubusercontent.com/23355487/42326076-76870252-803e-11e8-9ee5-71f65aee5db4.png)

**Comment by CristianoCricas** [comment]
Pessoal, ontem depois de quebrar muito a cabeça percebemos que os servidores de SP e RJ de Produção, aparentemente estão desatualizados (ou então, perfeitamente atualizados com a NT 2016.002 v1.60)

O caso é o seguinte:
No manual da NFe consta a tag <vDesc> do grupo de faturas como Opcional, porém os XSDs disponibilizados em 02/07/2018 não estão validando este campo corretamente (os anteriores acusavam preenchimento incorreto quando <vDesc> era 0.00). 

No ambiente de **Produção** de SP/RJ ao tentar enviar com essa tag preenchida como 0.00, da FALHA DE SCHEMA mesmo o arquivo constando como válido quando validados utilizando os XSDs atualizados. Mas no ambiente de Homologação (tanto para SP, RJ, RS e DF que foram os principais testes que fizemos) se esta tag não for informada pelo menos como 0.00, da a Rejeição _"Campos do grupo de Fatura não informados"_ e esta mesma Rejeição pode ocorrer nas UFs que "obrigam" preencher esta Tag.

**Solução provisória que tivemos que fazer:**
Ao gerar o XML damos a opção ao usuário para gerar ou não a tag <vDesc> do grupo de faturas zerada.  Se enviamos para SP/RJ em produção, da Falha no Schema, ai é só reenviar e não gerar a Tag zerada. Nas demais UFs que ja estamos rodando (RS e DF principalmente), se não enviar pelo menos zerada, da a rejeição acusando falta de campos no grupo Fatura.
