### ISSUE TITLE
Ignorar erros de digest value ao dar merge da autorização de uso com a NF-e

### ISSUE THREAD

**Issue by victorvilella** [nfephp-org/sped-nfe#447]
* **Estou enviando um ...**
  - [x] bug
  - [x] requisição de funcionalidade

* PHP 7.2
* Windows Server 2008 R2 em um EC2 na AWS

## Comportamento esperado
Conseguir ignorar a divergência de digest value do nó de assinatura da NF-e com o digest value do nó de autorização de uso.

## Comportamento Atual
Ao receber um digest value divergente, a aplicação lança uma exceção. Em todos os casos, me certifiquei que o XML gerado não foi mexido em tempo de execução, fazendo pensar que foi a SEFAZ (especialmente a do RS) que gerou um digest diferente.

## Solução possível
Assim como o projeto ACBr, poderíamos parametrizar se o método `Complements::toAuthorize()` lançará exceção caso esta divergência venha a acontecer. 

Eu cheguei a gerar uma PR mas vi que deveria mexer em outros pontos da classe `Complements`, fazendo com que eu tenha receio de mexer sem saber a opinião da comunidade.

**Comment by gersonfs** [comment]
Olá @victorvilella 

Já tive esse problema, e resolvi corrigindo a codificação para utf-8. Você verificou se não tem caracteres em outra codificação? E tentou remover todas as acentuações?

**Comment by robmachado** [comment]
Quanto ao EXCEPTION eu concordo com você ... promoverei a alteração para lançar esse EXCEPTION caso os digests sejam diferentes.

**Comment by robmachado** [comment]
Para checar sua afirmação sobre a SEFAZ RS alterar o digest, você pode usar a pagina de consulta da NFe e baixar a NFe que está lá com a SEFAZ e conferir o digest contido na NFe com essa cópia que você possui.

**Comment by victorvilella** [comment]
@robmachado Também achei muito estranho este artifício estar implementado em outras bibliotecas. Entendo que se trata de questões legais e tudo mais. Vou realizar proteções como o @gersonfs sugeriu pois de fato eu não faço nenhum tratamento com o XML antes de submetê-lo a SEFAZ. 

Acho que por agora não tem para onde fugir. Vou dar uma revisada na minha aplicação de qualquer forma.

Obrigado.

**Comment by robmachado** [comment]
Não se esqueça de confirmar o digest pegando a NFe na página de consulta da SEFAZ isso tirará suas duvidas

**Comment by victorvilella** [comment]
Como acredito se tratar de algum erro em minha aplicação, por agora, encerro esta issue.

Obrigado a todos.
