### ISSUE TITLE
Elementos X25A e X25B em local errado

### ISSUE THREAD

**Issue by rodolfodn** [nfephp-org/sped-nfe#458]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.0

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
Os elementos X25A e X25B (vagao e balsa) estão no manual com pai X01 (transp).

## Comportamento Atual
Os elementos X25A e X25B (vagao e balsa) estão na API com pai X22 (reboque).

## Solução possível
Mover os elementos X25A e X25 para a tagtransp;

## Possível implementação

![manual sefaz](https://user-images.githubusercontent.com/5527054/42648513-8ffaa082-85dd-11e8-9d90-f26361ebd264.png)
![phpnfe](https://user-images.githubusercontent.com/5527054/42648518-93e213b0-85dd-11e8-9a50-d3a6d1cbffa5.png)

**Comment by robmachado** [comment]
Já corrigido em MASTER, se possível faça um teste para mim e me avise .. se estiver certo subo o release com essa correção. E obrigado :+1:

**Comment by rodolfodn** [comment]
Tive que voltar a versão pois o Make está dando erro:

Fatal error: Uncaught TypeError: Argument 1 passed to NFePHP\Common\DOMImproved::appChild() must be an instance of DOMElement, null given, called in vendor\nfephp-org\sped-nfe\src\Make.php on line 5788 and defined in vendor\nfephp-org\sped-common\src\DOMImproved.php:197 Stack trace: #0 vendor\nfephp-org\sped-nfe\src\Make.php(5788): NFePHP\Common\DOMImproved->appChild(NULL, Object(DOMElement), 'A tag transp de...') #1

**Comment by robmachado** [comment]
Vagão e Balsa não estão mais contidos em tagReboque()
agora tem tagvagao() e tagbalsa() em métodos separados

**Comment by robmachado** [comment]
OLha a documentação ou apropria classe !
