### ISSUE TITLE
Exemplos

### ISSUE THREAD

**Issue by andrescarceli** [nfephp-org/sped-nfe#461]
Preciso de exemplos para entender como funciona !!!

**Comment by robmachado** [comment]
Olha a documentação https://github.com/nfephp-org/sped-nfe/tree/master/docs

**Comment by robmachado** [comment]
Acho que é melhor você estudar um pouco mais sobre SOAP, meu amigo. 
A comunicação é feita com SOAP versão 1.2, mas isso nada tem haver com essa declaração de exemplo que você menciona.
tag para SOAP 1.1  
      soapenv:Envelop

tag para SOAP 1.2
     soap:Envelop

**Comment by GeekSilva97** [comment]
Tenho noção disso. Só perguntei por ter visto no **Manual do Contribuinte**.

**Comment by robmachado** [comment]
Sim nem sempre as informações nesses manuais estão completas a que tomar algum cuida ao ler. Isso é BRASIL meu amigo

**Comment by GeekSilva97** [comment]
Foi só uma pergunta mano.

**Comment by robmachado** [comment]
Sim e eu dei  apenas uma resposta

**Comment by franluz** [comment]
robmachado, nada a ver vc tratar as pessoas assim, em dado momento vc tmb aprendeu independente de quao rapida eh a sua curva de aprendizado. (meu teclado nao tem acentos)

**Comment by rabraga** [comment]
Robmachado sempre trata as pessoas com educação. Não vi nada demais na resposta dele. Foi do mesmo nivel "Preciso de exemplos para entender como funciona!!!"

Vejo muita gente pedir ajuda, no lugar errado, que nem sequer procurou no lugar certo.

**Comment by geeksilva97** [comment]
> Vejo muita gente pedir ajuda, no lugar errado, que nem sequer procurou no lugar certo.

É eu procurei no manual. Não sei se leio comentário aí. E o cara veio todo arisco. Ele pode ser educado, mas acho que esse não foi o melhor exemplo de educação e paciência.

**Comment by franluz** [comment]
rabraga boa tarde, tudo bem? Eu vejo que o geeksilva97, fez uma pergunta, e nao teria chego a esse post se ele nao estivesse procurando uma soluçao como vc mesmo disse 'tentando entender como funciona', ha pessoas que entendem lendo documentaçao, ha pessoas que entendem com exemplo, nao vejo nada de mais nisso, nao acho que Robmachado  foi mal educado, acredito simplismente que quando alguem busca ajuda, responder um 'va ler o manual' nao ajuda, e no meu ponto de vista muito ajuda quem nao atrapalha.
