### ISSUE TITLE
NFC-e 4.0 QRCode 2.0 São Paulo

### ISSUE THREAD

**Issue by jffiorotto** [nfephp-org/sped-nfe#471]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ X] bug
  - [x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:
4.0
<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
<! --- Diga-nos o que deve acontecer ->
Nota deveria ser autorizada.
## Comportamento Atual
<! --- Diga-nos o que acontecer em vez do comportamento esperado ->

## Solução possível
<! --- Não é obrigatório, mas sugere uma correção / razão para o bug, ->

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1 Criar XML Mod 65 para SP.
2 Enviar ao sefaz.
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->como não esta em produção não afetou em nada..

<! --- Forneça um resumo geral do problema no Título acima ->
Ao tentar autorizar a NFC-e com QRCode 2.0 em SP está retornando o erro 396  Rejeição: Parâmetro do QR-Code inexistente (chAcesso). ja tentei as orientações passadas no forum para alterar as URL's nos arquivos, porem sem sucesso.

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Bom para começar a entender é necessário que mande o XML que tem esse erro para mim.
Ai irei ver de que se trata

**Comment by robmachado** [comment]
Para resolver MOMENTANEAMENTE tente alterar APENAS a version do QRCode de 200 para 100 no storage/wsnfe_4.00_mod65.xml

**Comment by jffiorotto** [comment]
@robmachado consegui contato com a Sec. Da Fazenda, segue informação passada:

Prezado contribuinte/desenvolvedor, boa tarde. 
Tudo bem? 

A SEFAZ-SP ainda não disponibilizou a versão do QRcode 2.0 para a NFC-e no ambiente de homologação. A previsão é que ao longo dessa semana uma nova versão seja instalada em homologação contemplando tanto a nova versão do Quick Response (2.00) e quanto a antiga (1.00). 

Pedimos desculpas pelo transtorno gerado. 
Agradecemos a compreensão. 
Atenciosamente, 


Agradecemos seu contato no "Fale Conosco" da Secretaria da Fazenda.

Sua opinião é muito importante para nós. Por gentileza, clique no link abaixo e opine sobre este e-mail:

Pesquisa de Satisfação



Atenciosamente,

Secretaria da Fazenda do Estado de São Paulo

**Comment by robmachado** [comment]
Obrigado ! @jffiorotto
