### ISSUE TITLE
Preencher cEANTrib e cEAN com 'SEM GTIN'

### ISSUE THREAD

**Issue by AlvaroAlves** [nfephp-org/sped-nfe#472]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando uma **
  - [ ] requisição de funcionalidade
  
* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:
4.00
<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
Caso enviado o valor vazio ou null preencher com 'SEM GTIN', tive problemas no servidor do RS em homologação

## Comportamento Atual
no XML está preenchendo a tag vazia <cEAN />, a última NT diz que deve ser preenchido com 'SEM GTIN'
## Solução possível
class Make;
function tagprod

alterar as seguintes linhas:
$cean = !empty($std->cEAN) ? trim(strtoupper($std->cEAN)) : '';
$ceantrib = !empty($std->cEANTrib) ? trim(strtoupper($std->cEANTrib)) : '';
para:
$cean = !empty($std->cEAN) ? trim(strtoupper($std->cEAN)) : 'SEM GTIN';
$ceantrib = !empty($std->cEANTrib) ? trim(strtoupper($std->cEANTrib)) : 'SEM GTIN';

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Segundo o manual da SEFAZ o GTIN pode ser vazio ou SEM GTIN, quando não tem GTIN pelo menos por enquanto. Não é bem competência da classe fazer algo que você não indicou diretamente. Portando incluir a frase "SEM GTIN" na classe de forma automática é algo que não ira acontecer.

**Comment by AlvaroAlves** [comment]
você chegou a dar uma olhada na seguinte NT?
 http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=T7PfUOHhMD4=

**Comment by robmachado** [comment]
Sim o problema maior é que ainda está valida a 3.10

**Comment by AlvaroAlves** [comment]
Entendi o problema,  por um momento esqueci que ainda trabalhamos com a 3.10;
desculpe

**Comment by robmachado** [comment]
Nunca se desculpe por tomar uma iniciativa meu amigo. É de inciativa e participação que precisamos sempre. Na próxima semana voltamos a esse assunto.

**Comment by AlvaroAlves** [comment]
ok

**Comment by guicalabria** [comment]
Oi,
  Não sei se a classe deveria adicionar o SEM GTIN automaticamente, pois
talvez o programa não adicionou o valor ou por qualquer motivo, então
estaríamos alterando um dado que não é correto.

Em qua, 25 de jul de 2018 às 15:13, Alvaro L. Alves B. <
notifications@github.com> escreveu:

**Comment by robmachado** [comment]
É onde eu queria chegar Guilherme.
Substituir dados devido a ausência dele, é algo perigoso !

**Comment by danillo10** [comment]
Estou tendo esse erro após atualização hoje roberto
message\": \"Class 'NFePHP\\\\Gtin\\\\Gtin' not found\",

**Comment by guicalabria** [comment]
Roberto, da mesma forma a não permissão de caracteres especiais e acentos não deveria ser função do programa? Caso o cliente queira que vá com acentuação (e da possível negação do XML) por conta da SEFAZ?

**Comment by robmachado** [comment]
Em principio sim ! porém temos que tomar cuidado com essas acentuações pois somente são aceitas algumas que devem ser substituídas por equivalentes htmlencode e houve muitos casos no passado que foram colocados caracteres de controle e não utf-8. Eu passei por isso ! e quem queimou o dedo tem medo de fogo. Mas você está certo, podemos pensar em algo para melhorar.
NOTA: caso passe algo incorreto você receberá aquele erro ESTUPIDO de "falha de schema" que não diz nada !!

**Comment by NewtonMan** [comment]
Só para relatar.
Sempre deixei estes campos em branco e a partir do uso da 4.00 estava obtendo esse erro de falha do schema xml, virei tudo de cabeça para baixo, até que observei em uma NF-e "SEM GTIN" implementei isso (ao invés de vazio) e a NF-e passou (SEFAZ AN e SP).

**Comment by NewtonMan** [comment]
O último XSD publicado pela SEFAZ exige também que cEAN e cEANTrib estejam com "SEM GTIN" caso contrário invalida o documento.
