### ISSUE TITLE
Problemas de chave no taginfNFe

### ISSUE THREAD

**Issue by lukBarros** [nfephp-org/sped-nfe#475]
Estou tendo um BUG

  - Versão do leiaute: 4.000

## Comportamento esperado
Emissão de NF com o ID passado;

## Comportamento Atual
ao usar:

$std = new stdClass();
$std->versao = '4.00'; 
$std->Id = "27180711592537000104550010000014051111058793";
$std->pk_nItem = null; 
$elem = $nfe->taginfNFe($std);

a chave id da NF sai: 27180711592537000104550010000014061723994454

## Solução possível
Depurei o método taginfNFe e não entendi, ele realmente seta o valor passado em Id

**Comment by robmachado** [comment]
Muito bem!
Isso não é um BUG !!! o que ocorre é que se o ID passado estiver incorreto um NOVO id é CRIADO

**Comment by lukBarros** [comment]
@robmachado o que posso considerar incorreto, uso o 'mesmo' algoritimo usado quando na outra versão do PHPNFE usando o monta chave da outra biblioteca.

De toda forma, como a forma correta de gerar a chave hoje em dia para esse pacote atual?

Grato pela resposta!

**Comment by rafaelzuim** [comment]
@lukBarros 
Amigo, eu também deixei pra última hora a implementação e estou quase no mesmo ponto que você.

No meu caso eu não consigo assinar o XML, ele não valida, pois acredito que devo estar com alguma versão incorreta do repositório, impactando na validação correta do XML.

Reparei que o código que você postou é identico ao meu mas meu XML não valida, você poderia compartilhar comigo qual o o $config_json que você passou para o construtor NFePHP\NFe\Tools, eu gostaria de confirmar se o meu está certo.

De qualquer forma convido todos que forem perder este final de semana a se ajudar aqui, o prazo está logo ali.

Qualquer exemplo de utilização seria de ótima ajuda

**Comment by lukBarros** [comment]
@rafaelzuim eu ja enviei, cancelei e inutulizei, mas hoje notei que passo uma chave (ID) mas na verdade saiu outra no documento em si, de resto tudo funcionando, criar, assinar, enviar, consultar, cancelar, inutilizar e danfe's para NF-e.

**Comment by lukBarros** [comment]
Segue:

[
		    "atualizacao" => date('Y-m-d h:i:s'),
		    "tpAmb" => $configuracao->sped_nfe_ambiente,
		    "razaosocial" => $emitente->nome_social,
		    "siglaUF" => $emitente->coreCidade->UF,
		    "cnpj" => $emitente->cnpjSemMascara,
		    "schemes" => "PL_008i2",
		    "versao" => $xmlVersao,
		    "tokenIBPT" => $configuracao->sped_nfe_tokenIBPT,
		    "CSC" => '',
		    "CSCid" => "",
		    "aProxyConf" => [
		        "proxyIp" => "",
		        "proxyPort" => "",
		        "proxyUser" => "",
		        "proxyPass" => ""
		    ]

**Comment by rafaelzuim** [comment]
@lukBarros 
Obrigado pelo seu compartilhamento de informações, eu irei madrugada a dentro por aqui para solucionar meu problema.

Uma coisa que te falo olhando o seu modelo acima é que, embora você esteja a minha frente (conseguiu assinar o xml), você está utilizando a SCHEMA antiga, essa PL_008i2 é da nota 3.10 que será desativada quinta feira.

Qualquer novidade posto por aqui

**Comment by lukBarros** [comment]
Ok qual seria o esquema correto?

**Comment by rafaelzuim** [comment]
@lukBarros 
Eu acredito que sim amigo, eu recebi esta resposta em outro Tópico, e faz todo o sentido, se você utilizar  o SCHEMA PL_008i2 , sua nota será validada localmente nos padrões do layout 3.10, então você pode em alguns casos receber uma resposta negativa do sefaz na hora de enviar o lote ao sefaz.

Aqui consegui rodar o startguide, na realidade só faltava pra mim utilizar alguns ' Sets' que já estavam contidos na class MAKE , mas que o exemplo do startguide não tem (Por se tratar de um exemplo para nota no layoput 3.10)

Se você ou alguém ai precisar do modelo de start guide correto para emissão da nota ainda com dados fixos ( Passo 1 para a contrução de uma solução ) é só me chamar.

Abraço

**Comment by robmachado** [comment]
@lukBarros Faça um PR do seu start guide pode ajudar outros e reduzir a duvidas de muitos

**Comment by lukBarros** [comment]
@rafaelzuim  massa man, acabei de gerar e enviar e obter cstat 100 com o esquema correto.  

Vou adicionar a documentação do starguide essa observação como comentário num pull

**Comment by lukBarros** [comment]
@robmachado  fiz 2 PR's o outro é no doc do repositório do projeto mail
