### ISSUE TITLE
Sugestão: schemas

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/sped-nfe#477]
https://github.com/nfephp-org/sped-nfe/blob/8e59950ed4918f2f8242f451ba20128b9ea0cf33/src/Common/Tools.php#L169

Eu sei que sou chato, e acho que um tanto preguiçoso também, mas isso me leva a pensar, porque não fica junto da versão isso ? e em vez de passar versão e schema passa ou um ou o outro ?

**Comment by robmachado** [comment]
Muito bem ! é que você não está lembrado mas já houve casos em que haviam duas versões de schema VALIDOS simultaneamente, ambas do mesmo LAYOUT. Em alguns estados usava-se um em outros o outro. DOIDO né !!

**Comment by lpj145** [comment]
é meu caro amigo, sinto que sefaz colocou muita pressão em cima de você nesse desenvolvimento kkkkk desculpa meus questionamentos, é que vou lançar a primeira versão de uma api que terminei aqui, e fiz muita coisa redundante que poderia estar próximo do core do framework, por isso que pensei na ideia do macro, porque podemos adicionar comportamento de acordo com a necessidade, e se isso poder rolar perto de onde as coisas realmente acontecem, maravilha!
