### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by lucasalencar05** [nfephp-org/sped-nfe#480]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [
Catchable fatal error: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given, called in and defined in \spednfe\vendor\nfephp-org\sped-nfe\src\Factories\Protocol.php on line 71 ] bug
 

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute 4.0:

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1 Acima de 150 itens retorna esse erro.
2 Com 100 itens gera a NFe normalmente.

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Não existe a classe MakeNFe neste projeto ... essa classe é de um projeto anterior agora DESCONTINUADO

**Comment by robmachado** [comment]
Outro detalhe ! a classe Protocol não deve ser utilizada !!! Existe uma classe para fazer o complementação da NFe com a adição do protocolo.
Complements::class com o método toAuthorize() veja em https://github.com/nfephp-org/sped-nfe/blob/master/docs/Complements.md

**Comment by lucasalencar05** [comment]
https://github.com/nfephp-org/sped-nfe/blob/master/docs/Make.md

**Comment by robmachado** [comment]
Sim Make e não MakeNFe mas acho que esse MakeNFe é construção sua !!

**Comment by lucasalencar05** [comment]
Sim só peguei Make.md e renomeei para MakeNFe.php,
Tudo ocorre bem, até 100 itens, gera a NFe normalmente, 
quando coloco 150 ou mais itens me retorna o erro.

**Comment by robmachado** [comment]
Vamos lá se o erro é na classe Make, porque está indicando a linha 71 da classe Protocol ??

**Comment by lukBarros** [comment]
Parece erro da implementação de Protocol()

**Comment by robmachado** [comment]
Colega !! não use a classe Protocol !!!

**Comment by lucasalencar05** [comment]
try {
            $protocol = new NFePHP\NFe\Factories\Protocol();
            $xmlProtocolado = $protocol->add($xmlAssinado, $protocolo);

            $stdCl = new NFePHP\NFe\Common\Standardize($xmlProtocolado);
            $json = $stdCl->toJson();
            $array = json_decode($json);
            echo json_encode(
                array(
                    'xMotivo' => $array->protNFe->infProt->xMotivo,
                    'cStat' => $array->protNFe->infProt->cStat,
                    'chNFe' => $array->protNFe->infProt->chNFe,
                    'nProt' =>$array->protNFe->infProt->nProt 
                ), JSON_UNESCAPED_UNICODE
            );*/
        } catch (\Exception $e) {
            //aqui você trata possíveis exceptions ao adicionar protocolo
            echo json_encode(
                array(
                    'xMotivo' => str_replace("\n", "<br/>", $e->getMessage()),
                    'cStat' => 0
                ), JSON_UNESCAPED_UNICODE
            );
            exit;
        }

**Comment by lucasalencar05** [comment]
MUDEI ESSE TRECHO PARA.

use NFePHP\NFe\Complements;

$req =  $xmlAssinado ;
 $res =  $protocolo;

try {
    $xml = Complements::toAuthorize($req, $res);
    header('Content-type: text/xml; charset=UTF-8');
    echo $xml;
} catch (\Exception $e) {
    echo "Erro: " . $e->getMessage();
}

TIVE ESSE RETORNO.

"xMotivo":"Os documentos se referem a diferentes objetos. Os digest são diferentes."

**Comment by robmachado** [comment]
Agora SIM ... temos que o HASH digest do XML da NFe é diferente do HASH digest da resposta da SEFAZ

**Comment by robmachado** [comment]
Olhe os dois XML e compara os DIGEST de ambos

**Comment by lucasalencar05** [comment]
robmachado, como comparar?

**Comment by robmachado** [comment]
No XML da NFe
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <Reference URI="#NFe35180658716523000119550000000502731540011215">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <DigestValue>F17QWPQ6QNxtoEfuIM51nb+WK/8=</DigestValue>
                </Reference>
            </SignedInfo>

E no XML da resposta da consulta da SEFAZ
<infProt>
        <tpAmb>1</tpAmb>
        <verAplic>SP_NFE_PL_008i2</verAplic>
        <chNFe>35180658716523000119550000000502731540011215</chNFe>
        <dhRecbto>2018-06-01T13:23:08-03:00</dhRecbto>
        <nProt>135180364623219</nProt>
        <digVal>F17QWPQ6QNxtoEfuIM51nb+WK/8=</digVal>
        <cStat>100</cStat>
        <xMotivo>Autorizado o uso da NF-e</xMotivo>
    </infProt>

Então o DIGEST da assinatura 
 <DigestValue>F17QWPQ6QNxtoEfuIM51nb+WK/8=</DigestValue>

Tem que ser IGUAL ao digVal do Protocolo
<digVal>F17QWPQ6QNxtoEfuIM51nb+WK/8=</digVal>

**Comment by lucasalencar05** [comment]
robmachado, só mudou o retorno,
 com 100 itens gera a NFe normal, 
com mais de 100.
o retorno
"xMotivo":"Os documentos se referem a diferentes objetos. Os digest são diferentes."

**Comment by lucasalencar05** [comment]
Enviei o xml e arquivo php

**Comment by lucasalencar05** [comment]
Chegou aí?
Aqui deu.
llinux.rlm@gmail.com
Endereço não encontrado.

**Comment by robmachado** [comment]
Tem um "L" a mail no endereço
