### ISSUE TITLE
Tools - Melhoria descritiva das RuntimeExceptions

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#483]
* **Estou enviando um ...**
  - [ ] bug
  - [ ] requisição de funcionalidade
  - [X] melhoria interna da API?

## Contexto (Ambiente)
Ao fazer um find no código da classe Tools temos 14 ocorrências da string 'Não foram passados todos os dados necessários.', todas ao gerar RuntimeException.

## Descrição detalhada
Esta string genérica poderia ser melhorada indicando em cada exceção qual foi o campo/parâmetro que falhou, ajudando assim o usuário dev no uso da API. Como a mensagem é genérica, ele não sabe muito bem o que aconteceu...

## Possível implementação
Exemplo:
```
    public function sefazValidate($nfe)
    {
        if (empty($nfe)) {
            throw new RuntimeException(__METHOD__ . ' - Parâmetro nfe parece vazio!');
        }
```

**Comment by lukBarros** [comment]
@robmachado parece bacana melhorar isso, oq acha?

**Comment by robmachado** [comment]
Claro .. sempre a espaço para melhorar meu amigo

**Comment by fmertins** [comment]
Bom dia, vou tentar ajudar nesta durante a semana, abracos.

**Comment by fmertins** [comment]
Olá, vou começar a refatorar, uma dúvida, não seria melhor gerarmos InvalidArgumentException nestes casos de parâmetro faltando/etc, ao invés de RuntimeException?

**Comment by robmachado** [comment]
@fmertins 
Em alguns casos InvalidArguments é mais indicado em outros pode ser o RunTime tem que verificar caso a caso. Mas no final tudo é Exception

Roberto

**Comment by fmertins** [comment]
Olá, fiz o PR #535
