### ISSUE TITLE
Implementar nos exemplos como gerar o XML da NF-e/NFC-e 4.00

### ISSUE THREAD

**Issue by NewtonMan** [nfephp-org/sped-nfe#484]
As versões anteriores a 5 possuem na parta /examples uma série de exemplos de uso, entre eles havia o exemplo de uso das classes para gerar o XML através de chamadas aos métodos com descrição dos parametros e etc....

Acredito que seria muito importante manter esses exemplos acompanhando a versão vigente dos documentos em cada um dos projetos.

Estou tentando desenvoler o layout da NF-e 4 e estas classes e exemplos só existem de maneira funcional para a versão 3.10.

Alguém poderia dar uma direção pelo menos de onde posso localizar o que mudou?

**Comment by lukinhaspm** [comment]
Tarde

A diferença principal é que os exemplos estão na pasta docs - alguns não tem o código fonte, mas você encontra muita coisa no grupo do Google 
https://github.com/nfephp-org/sped-nfe/tree/master/docs

Exemplos
https://github.com/nfephp-org/sped-nfe/tree/master/examples

Grupo do Google
https://groups.google.com/forum/#!forum/nfephp

Obs, nem todos os exemplos e modelos da documentação estão 100%, observe nomes de variáveis e formas de como fazer, adapte ao seu código.

ABs

**Comment by NewtonMan** [comment]
Obrigado @lukinhaspm isso já ajuda, mas acredito que aquilo que é bom deve ficar melhor e não deixar de existir.

A descentralização é um problema ainda neste projeto pois entendo que é complicado dividir uma grande lib que encapsulava tudo em frentes de atuação diferentes, é um enorme desafio, e é o tipo de coisa que é mais fácil fazer do zero de novo.

Mas acho que seria legal estabelecer alguns requerimentos funcionais, sem isso vejo esse projeto andando devagar e um tanto sem direção, todos sabem que é preciso implementar o suporte a isso ou aquilo, a maneira de chegar ao objetivo está documentada, mas é preciso ir além, eu acho que seria interessante dividir ainda mais os projetos com classes que tratam dos grupos de dados dos documentos.

Um referencia interessante é a documentação do FlexDocs das libs deles de NFe/CTe/MDFe/etc talvez alinhar a estrutura do projeto de forma similar possa descomplicar um pouco as coisas.

Enfim, eu não vejo a mesma organização (limpa) nestes repositórios e documentos aqui e acho que é uma maneira melhor de trabalhar, inclusive estimularia mais desenvolvedores a participar.

**Comment by lukinhaspm** [comment]
Concordo com você em alguns pontos,

Mas antecipando a resposta padrão do grupo, que eu concordo, é que o
projeto é aberto e free e depende das pessoas, vemos a quantidade de
pessoas que usam, e que estão recorrendo ao projeto agora que precisa
migrar a versão, mas não vemos todas essas pessoas ajudando em exemplos e
documentações.

Abs

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em qui, 2 de ago de 2018 às 15:26, NewtonMan <notifications@github.com>
escreveu:

**Comment by NewtonMan** [comment]
Olá @lukinhaspm eu sou uma pessoa que tem interesse em ajudar mas devido a bagunça acredito que só vá atrapalhar de fato. Veja que entre meus repositórios eu tenho um conjunto de classes para efetuar a leitura e carregar em um objeto os dados de NFs. Estou na medida do possível contribuindo para a comunidade de modo geral, eu não quero ser apenas um crítico, abri esse issue com a intenção de fazer estes apontamentos caso a coisa não estivesse andando da maneira que esperava.

Eu vou abrir alguns repositórios e criar uma estrutura bem pensada e farei uma sugestão aqui.

Por hora minha sugestão é que criem um arquivo no /examples/MakeNFe.md com o seguinte conteúdo:
Veja como gerar o XML aqui:
https://github.com/nfephp-org/sped-nfe/blob/master/docs/Make.md

**Comment by robmachado** [comment]
Um desenvolvedor deve em principio poder ler um documento (e vários são bem detalhados) e escrever seu código. Dito isso não pretendo fazer mais exemplos ou me preocupar com os mesmos. 
A grande maioria dos aplicativos (e classes) OpenSource disponíveis no GitHUB nem isso tem.
Não sou eu quem deve se preocupar com "como" fazer sua aplicação funcionar. Eu apenas mantenho um mecanismo facilitador.
Quanto a DIVISÃO de projetos, foi feito pois antes aquilo erá uma MINHOCA (as versões anteriores da API) e estava ficando cada vez ma is complexo manter. Divida para conquistar, divida para simplificar. Use o SOLID, use os PSRs, atualize para padrões PHP mais atuais. E é isso que está sendo feito.
A API usa o VERSIONAMENTO SEMANTICO então quem for usar o pacote deve se atentar a isso.
Não é meu problema que muitos desenvolvedores deixaram as coisas para ultima hora e não se anteciparam para atualizar (a versão 4 foi congelada a mais de 2 anos e isso foi avisado).
Eu sou aberto a sugestões, comentários e ajuda.
Então se pode fazer melhor AJUDE e FAÇA ...

**Comment by NewtonMan** [comment]
Olá @robmachado antes de mais nada eu quero agradecer por todo o trabalho realizado por você, sem ele nada disso seria possível.

Eu observei melhoras gigantescas pois uso essa API desde o primeiro release, anteriormente eu havia feito tudo na mão.

Mas desde já registro que minha intenção é ajudar a melhorar, não levem nada para o lado pessoal, ninguém é melhor do que ninguém, muito menos eu.

Como disse vou tentar compartilhar em breve com você @robmachado uma possível linha de organização que deve somar a tudo que está sendo feito, trazendo uma melhor organização.

Eu devo montar um escopo de eco sistema com NFe, CTe e MDFe e apresento a você, quem sabe eu não te convenço?

Um abraço

**Comment by robmachado** [comment]
Fico no aguardo :+1:
