### ISSUE TITLE
CLASS MAKE

### ISSUE THREAD

**Issue by limabibi** [nfephp-org/sped-nfe#487]
Olá,

Ao chamar a classe Make esta apresentando erro:

Parse error: syntax error, unexpected '[' in Make.php on line 34

**Comment by robmachado** [comment]
Pode ser um problema no seu ambiente. Na linha 34 temos 
```php
public $erros = [];
```
O que está perfeitamente correto !

**Comment by NewtonMan** [comment]
@limabibi você está usando uma versão do PHP que não oferece suporte para a nova syntaxe de arrays, deve estar usando PHP 5.4 ou anterior.

Para resolver isso atualize seu ambiente para o PHP 7 e observe a lista de extensões que é preciso estar habilitadas para o pleno funcionamento da API.

**Comment by NewtonMan** [comment]
Recomendo também que leia:
https://github.com/nfephp-org/sped-nfe/blob/master/docs/StartGuide.md

**Comment by limabibi** [comment]
Obrigado NewtonMan.....se atualizar para 5.6 não é o suficiente? Apenas o 7 resolve a questão do erro no array?

**Comment by robmachado** [comment]
PHP 5.6 resolve mas o recomendado é passar para PHP7.2 se seu aplicativo e seu ambiente suportarem.

**Comment by limabibi** [comment]
Posso perguntar mais uma coisa por gentileza? É que a contabilidade não informou a gente sobre essa a nova versão 4.0 e agora temos que correr para desenvolver... Na hora de chamar a classe make, eu estou usando 

Use NFephp/NFe/Make

Mais aí aparece que a classe não foi encontrada....como devo chamar essa classe, por gentileza?

**Comment by robmachado** [comment]
Antes de chamar a classe seu aplicativo deve carregar o autoload.php do composer

**Comment by limabibi** [comment]
Eu ja fiz tudo que pediu e ainda nao aparece a classe :(

require_once "../../vendor/autoload.php";

$nfe = new Make();
$std = new \stdClass();

**Comment by robmachado** [comment]
Colega ! você é o desenvolvedor PHP, é você quem tem que saber como usar o PHP

**Comment by NewtonMan** [comment]
Olá @limabibi trabalhar com classes a partir do PHP 7 é um pouco diferente devido a implementação de NAMESPACES.

Depois do require ... autoload.php você deve chamar/importar as classes usando os namespaces delas nas primeiras linhas do seu código.

No primeiro momento pode parecer meio burocrático mas isso ajuda em vários aspectos, principalmente em performance, pois só as classes importadas por namespaces estarão disponíveis para você trabalhar, outras linguagens como Java, C#, VB, e outras já tinham suporte a namespaces há bastante tempo.

Para o seu código funcionar você precisa importar as classes que vai usar via namespaces também, algo como:
```
require_once "../../vendor/autoload.php";

// Importando via namespaces
use NFePHP\NFe\Make; // importou a classe Make
use NFePHP\NFe\Tools; // importou a classe Tools

$nfe = new Make(); // Agora $nfe é um objeto de make
```
