### ISSUE TITLE
Alteração operação consulta Sefaz-AM

### ISSUE THREAD

**Issue by marcelonogueira** [nfephp-org/sped-nfe#489]
* **Estou enviando um ...**
  - [X] bug

* ** Por favor, conte-nos sobre o seu ambiente: **
  - Versão do leiaute: 4.00

## Comportamento esperado
Alterar a operação do método nfeConsultaNF da SEFAZ-AM de **NFeConsulta4** para **NFeConsultaProtocolo4**.

## Comportamento Atual
A Sefaz-AM alterou o caminho do serviço de consulta.

## Solução possível
Alterar a linha 17 do arquivo nfephp-org/sped-nfe/storage/wsnfe_4.00_mod55.xml para:
`<NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsultaProtocolo4" version="4.00">https://nfe.sefaz.am.gov.br/services2/services/NfeConsulta4</NfeConsultaProtocolo>`

**Comment by robmachado** [comment]
Ajustado em MASTER, assim que der passo para o release
