### ISSUE TITLE
Problema com as URLs do estado de SERGIPE em Produção

### ISSUE THREAD

**Issue by ericalves** [nfephp-org/sped-nfe#490]
Boa tarde.

Eu estava tentando emitir um cupom para o estado de Sergipe no layout 3.10 e recebi o erro _Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto_.

Verifiquei que as URLs tanto da versão 4.00 quanto da 3.10 estavam desatualizadas e atualizei. Realizei o teste na versão 3.10 e foi sem problemas, porém na versão 4.00 sigo recebendo o mesmo código de rejeição (395). 

Realizando o teste em homologação, ambos os layouts passam sem problemas.

Acredito que existe algum problema na montagem da URL em produção, porém não consigo identificar qual.

Seguem XMLs de exemplo. Da versão 3.10 (sucesso) e 4.00 (erro). Anexei também os XMLs de homologação que foram sem problemas.

[Zip com 4 XMLs, 2 prod e 2 homolog](https://drive.google.com/open?id=1canMjSC8JzVAGTVRV-sQKoylAK5t_Uw1)

**Comment by NewtonMan** [comment]
Olá @ericalves o layout da NF-e 3.10 foi desativado e isso foi avisado há 2 anos (em 2016).

Para você iniciar com a NFe 4.00 visite esse endereço:
https://github.com/nfephp-org/sped-nfe/blob/master/docs/StartGuide.md

**Comment by ericalves** [comment]
Bom dia. Na verdade, amigo, o prazo foi prorrogado. E não é esse o problema que estou relatando.

Se você ler o que escrevi vai entender que na 3.10 ainda está funcionando.

Obrigado.

**Comment by robmachado** [comment]
Veja o meu POST 
https://groups.google.com/forum/#!topic/nfephp/8sS_8j-1xCM

**Comment by ericalves** [comment]
Boa noite.

Desculpem a demora no retorno.

@NewtonMan Segue [link](https://www.bsoft.com.br/blog/prorrogado-o-prazo-nf-e-4-0-emissor-atualizado) fala da prorrogação e um link para a nota oficial.

@robmachado Li o seu post e acredito que seja isso mesmo. Fiz o pull dos fontes novamente (vi que ocorreram alterações nos arquivos de layout) e realizei um novo envio em homologação no layout 4.00 e funcionou sem problemas. Amanhã pela manhã irei atualizar a lib em produção e realizar o teste também em produção e aviso aqui para fecharmos a issue.

Muito obrigado pelo auxílio.

**Comment by ericalves** [comment]
Bom dia.

Realizei os testes em produção e continuo recebendo rejeição do SEFAZ. Gerei primeiro em produção ajustando as URLs de prod exatamente como o link que você mandou Google Groups, a tag ficou assim:

`	<infNFeSupl>
		<qrCode>
			<![CDATA[http://www.sefaz.se.gov.br/nfce/consulta?p=28180811677714000155650000000015671768217555|2|1|3|0C831F0609A3DAC5075BF17C36B7B6F0AF4FC4A0]]>
		</qrCode>
		<urlChave>http://www.sefaz.se.gov.br/nfce/consulta</urlChave>
	</infNFeSupl>`

Usei o arquivo uri_consulta_nfce.json que você posto e ajustei a URL de produção conforme o link que vc havia postado.

Não sei o que posso olhar, as URLs estão certas!

**Comment by robmachado** [comment]
@ericalves As SEFAZ estão com uma série de FALHAS nesses quesitos. E o ENCATE colocou um monte de URLS "exoticas" para dizer o minimo.
Eu não uso, nem tenho como testar o NFCe portanto dependo de vocês. Infelizmente isso terá de ser feito por tentativa e rro e muito possivelmente atraves de contatos com o pessoal técnico de cada SEFAZ.

**Comment by ericalves** [comment]
Perfeito @robmachado . Vamos deixar essa issue aberta então, pois com a versão atual da lib está gerando esse problema. 
Estou em contato com o SEFAZ-SE para tentar localizar o problema, assim que descobrir algo posto aqui e já faço o pull request da correção.

Abração e obrigado pelo auxílio.

**Comment by robmachado** [comment]
A LIB não gera o problema a SEFAZ e o ENCATE é que geram o problema, devido a falta de informação clara e confiavel.
Os colegas que usam a LIB geram problema pois muito poucos ajudam corrigindo as URLS dos webservices após encontrarem a solução. Esse é um software LIVRE e portanto não tenho a obrigação de corrigir tudo, mesmo por que não tenho como faze-lo.

**Comment by ericalves** [comment]
Claro @robmachado! Meu comentário foi bem por isso, quem quiser utilizar a lib HOJE para gerar um cupom fiscal em Sergipe vai obter o mesmo erro que eu, e precisamos ajustar. Não foi uma crítica, pelo contrário, como usuário dessa lib, quero e pretendo seguir ajudando na evolução da mesma, e como você mencionou, você não utiliza o NFCe, dependendo de nós, usuários dela, para essas melhorias.

Usava até pouco tem a versão descontinuada, reescrevi minha API devido a 4.00 para utilizar a sped-nfe. Na versão anterior fiz diversas correções no nosso fork. 

Vou seguir realizando os ajustes necessários na sped-nfe só que agora farei pull requests dessas correções para o restante da comunidade.

**Comment by robmachado** [comment]
Só queria chorar com alguém 

**Comment by robmachado** [comment]
Corrigido em master
