### ISSUE TITLE
Arquivo Strings

### ISSUE THREAD

**Issue by Vanias** [nfephp-org/sped-nfe#492]
Boa tarde, gerei um arquivo txt conforme layout, porém quando chamo a classe Convert::parse($txt), retorna um erro:

Fatal error: Class 'NFePHP\Common\Strings' not found in ...

notei que este arquivo realmente não existe, alguem pode me ajudar?

**Comment by robmachado** [comment]
Claro !!

Você não instalou pelo composer ! e portanto não instalou as dependências da API 
Ou não está usando o autoload do composer !!!

**Comment by Vanias** [comment]
meu amigo, irei tentar via composer, minha tentativa foi via download do github. Postarei aqui o resultado, grato pela assistencia!

**Comment by robmachado** [comment]
Os pacotes de dependências estão explicitados no arquivo composer.json
Várias classes estão em outro pacote sped-common que são classes usadas por vários projetos sped

**Comment by Vanias** [comment]
Amigo, instalei via composer veio essas pastas adicionais, porém, preciso alterar algo para que funcione? existe o arquivo Strings.php no sped-common porem a classe Convert.php não enxerga ele

**Comment by robmachado** [comment]
Colega eu uso diariamente a API, se não enxerga é algum problema ai no seu código

Roberto

**Comment by Vanias** [comment]
obrigado amigo, estou seguindo aqui a documentação emiti um txt e chamei a classe Convert, porem a partir tela nao enxerga o Strings. Continuarei tentando

**Comment by NewtonMan** [comment]
@Vanias você está importando as classes via namespaces?

Observe na sessão de "Como implementar" no meu repositório:
https://github.com/NewtonMan/sped-nfe

**Comment by Vanias** [comment]
@NewtonMan amigo, fiz isso apenas onde eu uso a Convert.php
adicionei:
require VENDOR_DIR . 'autoload.php';

parou um dos erros agora, apresenta outros. A dúvida é se preciso fazer isso em toda a lib, estou usando essa vendor no cakephp:
Fatal error: Interface 'NFePHP\NFe\Exception\ExceptionInterface' not found in

**Comment by AlvaroAlves** [comment]
Você fez a instalação via composer?

Em qua, 8 de ago de 2018 11:23 AM, Roberto L. Machado <
notifications@github.com> escreveu:

**Comment by Vanias** [comment]
@robmachado fico feliz que na sua funcione amigo, pergunto aqui as dúvidas para quem quiser e puder me auxiliar (no caso quem ja usou toda a lib), @AlvaroAlves instalei via composer sim, fiz a anotação que esta no seu blog, porem resolveu o primeiro erro rs,

**Comment by robmachado** [comment]
Tente usar o Xdebug e veja onde se perde

**Comment by robmachado** [comment]
Outra dica para você estude PSR-4 e LARAVEL tem cursos gratuitos e vários videos no Youtube com certeza vai ajudar em alguma coisa que você está esquecendo ou errando.
