### ISSUE TITLE
Consulta de eventos registrados na NF-e

### ISSUE THREAD

**Issue by GeekSilva97** [nfephp-org/sped-nfe#493]
Dei uma olhada na documentação e não encontrei nada referente a **consulta de eventos** da NF-e. Na verdade encontrei na documentação encontrei o arquivo [ProcEventoNFe.md](https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/ProcEventoNFe.md). No entanto não possui exemplo de método no código. Alguém já utilizou essa funcionalidade ?

PS: Obrigado por esse belo trabalho, parabéns aos envolvidos.

**Comment by robmachado** [comment]
@GeekSilva97 
Para começar recomendo que leia com atenção (poucos o fazem) o manual da SEFAZ.
**Não existe webservice de consulta de Eventos !** 

A que você se refere quando fala "consulta de eventos" ??

Veja que se você utiliza uma terminologia "estranha" fica difícil entender o que você precisa.

**Comment by GeekSilva97** [comment]
Eu li. Talvez não tenha dada a devida atenção, fala um pouco sobre eventos mas não é bem o que eu precisava. Na verdade perguntei aqui justamente porque pode ser que haja alguma falha naquele manual, como já me disseram inclusive em uma outra issue aqui.

Com "consulta de eventos" em refiro a listar os eventos que foram registrados naquela NF-e.

**Comment by GeekSilva97** [comment]
Nesse link: http://nfe.sefaz.ce.gov.br/pages/consultaNfeXSLTParametro.jsf?efnConsult={CHAVE NFE}
Lá no final, tem uma seção: **Eventos ds NF-e**. Como mostra a imagem.

![nota](https://user-images.githubusercontent.com/15680379/43851347-cec50d3c-9b10-11e8-835b-688024bd809f.PNG)

Estou me referindo a esses eventos. Mas me parece que realmente não tem como. Será preciso apelar para **Web Scraping**.

Obrigado pela atenção.

**Comment by robmachado** [comment]
Isso retorna quando você faz a consulta da Chave da NFe

**Comment by GeekSilva97** [comment]
Compreendi. Então creio que no WS ele faz de alguma forma que traz o último (e as vezes nem traz). Obrigado @robmachado vou tentar coletar essa lista por meio de Web Scraping.
