### ISSUE TITLE
soap:SenderError reading XMLStreamReader.

### ISSUE THREAD

**Issue by thiagoreri** [nfephp-org/sped-nfe#500]
Pessoal estou usando o layout 4.0

Na realização dos eventos de envio de lote, consultarecibo o $resp recebe essa mensagem 'soap:SenderError reading XMLStreamReader.'

**Comment by robmachado** [comment]
Com o que ? Qual software ?

**Comment by thiagoreri** [comment]
Desculpas, era problema no soap
