### ISSUE TITLE
267 - Motivo: Rejeição: Chave de Acesso referenciada inexistente [nRef: 1]

### ISSUE THREAD

**Issue by limabibi** [nfephp-org/sped-nfe#505]
Olá,

Estou tentando emitir uma NF de Devolução e quando chega em Consulta Recibo ela é rejeitada:
267 - Motivo: Rejeição: Chave de Acesso referenciada inexistente [nRef: 1]
A chave de saída referencia é existente foi emitida em Julho/2018 e ao consultar ela no site do sefaz ela esta aparecendo como autorizada.

Uma observação: A nota de saída foi emitida em modo de produção, e a nota de devolução que estou tentando emitir está no modo homologação, porque ainda estamos em fase teste. 

Olhei o manual "Nota Técnica 2016.002", mas não tem nada a respeito da rejeição 267.
Pderiam me ajudar, por gentileza?
Desde já grata.

**Comment by fmertins** [comment]
Olá, tente suporte direto com a SEFAZ e/ou grupo do projeto no Google, aqui são dúvidas mais relacionadas ao projeto mesmo, abraços.

**Comment by limabibi** [comment]
Ok, obrigada. Já consegui resolver.
