### ISSUE TITLE
Download XML Detalhado

### ISSUE THREAD

**Issue by Craivy** [nfephp-org/sped-nfe#511]
Estou com um problema aqui referente ao XML da NF, pois quando tento fazer o download da nf ela só me retorna o xml resumido... Será que alguém pode me ajudar de alguma forma para trazer o xml detalhado da nota???

**Comment by solracnet** [comment]
Qual é o método que você está usando para baixar as notas?

**Comment by euclecio** [comment]
Aproveitando a issue sobre download do XML , de acordo com a documentação não é possível fazer download para emitentes
https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/Download.md

```
NOTA: Este serviço NÃO está disponivel para os emitentes, mas apenas aos destinatários, transportadores e outros autorizados, desde que essa NFe tenha sido previamente manifestada !!!
```

Estou com casos de duplicidade onde o cliente exclui a nota e não consegue mais o XML, terá algum método para fazer download pelo emitente ou tem outra maneira de eu recuperar o download?

**Comment by robmachado** [comment]
Apenas pelo site de consulta da nfe (na sefaz do estado ou na receita) mas para isso é necessário saber a chave de 44 digitos dessa nota.

**Comment by robmachado** [comment]
Cara ! não tenho a menor ideia do que você fez ai !! Nem de como está fazendo isso !!!
mas as notas destinadas após a manifestação da ciência da operação demoram algum tempo para serem disponibilizadas.

**Comment by alemaorsl** [comment]
Sabes de quanto tempo demora essa liberação?

**Comment by robmachado** [comment]
As vezes minutos, as vezes horas. 
Não dá para cravar nada, isso não depende dos nossos sistema se sim da Receita e da SEFAZ.
Eu não uso o download de forma direta apenas com o DFe e faço as consultas ao DFe em intervalos de 2 a 3 horas. E sempre recebo todas as NFe manifestadas no intervalo anterior.

**Comment by alemaorsl** [comment]
Ok, vou aguardar aqui, para ver se os documentos ficam disponíveis, o processo que eu fiz foi usar o DFe e depois manifestei os documentos, mas isso eu fiz ontem até agora só está retornando o resumo da NFe...

mas vou aguardar para ver se a situação muda..
Obrigado

**Comment by robmachado** [comment]
Não se esqueça de INCREMENTAR sempre o ultnsu usado na consulta senão você recebera sempre os mesmos dados colega

**Comment by juizmill** [comment]
Mas alguém sabe me dizer como o [fsist ](https://www.fsist.com.br/#consulta) faz o download do XML?

**Comment by robmachado** [comment]
Ele usa o site da Receita mas acaba burlando o CAPTCHA (não si como)
Os XML que ele retorna NÃO SÃO os originais, o digest, assinatura e certificado são diferentes dos originais. Isso deixa esses documentos INCORRETOS e ILEGAIS para fins de arquivamento.

**Comment by juizmill** [comment]
@robmachado Mesmo vc colocando o certificado no opção de informar o certificado que eles tem?

**Comment by robmachado** [comment]
Bom isso eu não testei ! Se for passado o certificado, o xml **poderá** ser baixado normalmente e será o xml REAL enviado originalmente.

**Comment by juizmill** [comment]
@robmachado isto que acho estranho! Meu problema é quando envio a nota e o retorno vem com o status 105 "Lote em processamento", ou seja a receita não retorna o XML assinado.. e quando tento novamente fala que o XML já foi enviado e que gerou duplicidade. 

Desta forma não consigo obter o XML assinado e nem gerar a DANF.. sabe de alguma solução para contornar este problema..

**Comment by robmachado** [comment]
Olha essa ISSUE não está tratando disso NÃO misturem as BOLAS fica confuso demais !!

**Comment by robmachado** [comment]
Mas vou esclarecer um pouco:
1 - a receita não retorna o xml da NFe assinado, retorna um protocolo DEPOIS de processar seu XML e não encontrar erros.
2 - se o LOTE esta EM PROCESSAMENTO, tudo que você pode fazer é continuar buscando o retorno até o processamento da RECEITA retornar, OU ...
3 - em caso de paralisação do servidor do autorizador, pode verificar se está ativada a contingência (pela SEFAZ) e se estiver criar uma NOVA NFE (com um novo numero) e enviar em contingência, e assim que retornar o serviço da SEFAZ autorizadora deverá, consultar o NFe emitida anteriormente (durante a paralisação do serviço) para verificar se foi aceita, e se SIM então CANCELAR essa NFE para não ter duplicidade de dados (uma vez que já havia emitida outra em contingência). Porém se a NFE não tiver sido aceita (acusou algum erro) então esse Numero de NFE deverá ser INUTILIZADO.

**Comment by juizmill** [comment]
Entendi, obrigado pela ajuda.

**Comment by felipeiise** [comment]
> Bom isso eu não testei ! Se for passado o certificado, o xml **poderá** ser baixado normalmente e será o xml REAL enviado originalmente.

O fsist pede a instalação de uma extensão no Chrome ou Firefox, assim fica "fácil", ele nada mais faz do que ter controle sobre o navegador, não decompilei e inspecionei o fonte da extensão, mas instalei para testes e vou desinstalar em seguida, na época destes posts não sei se era assim com reCAPTCHA, mas o sistema deles através da extensão redireciona para o site da Fazenda, com o campo da chave oculto (porque é informado no site deles), pedindo apenas para resolver o reCAPTCHA, e assim que envia, ele retorna para o site deles, e aí claro com todo o conteúdo disponível da nota para fazer "web scraping" (gerar PDF, xml inválido)

Baixei diretamente pelo site da Fazenda o xml com meu certificado (uma nota que recebi para o meu CPF) e comparei com o XML baixado sem certificado pelo fsist e realmente é um XML inválido do ponto de vista legal, pois a assinatura e outros campos de validação não batem, eles devem gerar o XML com base nos dados do HTML da nota, porém usando a opção do certificado no fsist o XML é idêntico, porque ele nada mais faz do que servir de ponte para o site da Fazenda através da extensão e baixar o XML válido.

E testando com uma chave de acesso que meu CPF não é nenhum dos autores da nota fiscal, ao escolher a opção no fsist de baixar o XML com certificado naturalmente ele não consegue, porque é uma restrição da Fazenda.

**Comment by felipeiise** [comment]
> Mas alguém sabe me dizer como o [fsist ](https://www.fsist.com.br/#consulta) faz o download do XML?

O fsist pede a instalação de uma extensão no Chrome ou Firefox, assim fica "fácil", ele nada mais faz do que ter controle sobre o navegador, não decompilei e inspecionei o fonte da extensão, mas instalei para testes e vou desinstalar em seguida, na época destes posts não sei se era assim com reCAPTCHA, mas o sistema deles através da extensão redireciona para o site da Fazenda, com o campo da chave oculto (porque é informado no site deles), pedindo apenas para resolver o reCAPTCHA, e assim que envia, ele retorna para o site deles, e aí claro com todo o conteúdo disponível da nota para fazer "web scraping" (gerar PDF, xml inválido)

Baixei diretamente pelo site da Fazenda o xml com meu certificado (uma nota que recebi para o meu CPF) e comparei com o XML baixado sem certificado pelo fsist e realmente é um XML inválido do ponto de vista legal, pois a assinatura e outros campos de validação não batem, eles devem gerar o XML com base nos dados do HTML da nota, porém usando a opção do certificado no fsist o XML é idêntico, porque ele nada mais faz do que servir de ponte para o site da Fazenda através da extensão e baixar o XML válido.

E testando com uma chave de acesso que meu CPF não é nenhum dos autores da nota fiscal, ao escolher a opção no fsist de baixar o XML com certificado naturalmente ele não consegue, porque é uma restrição da Fazenda.

**Comment by Clarck1** [comment]
> Cara ! não tenho a menor ideia do que você fez ai !! Nem de como está fazendo isso !!! mas as notas destinadas após a manifestação da ciência da operação demoram algum tempo para serem disponibilizadas.

eu entendi essa parte. minha duvida é se tem como listar as chaves de acessos das nf-e emitias contra pra poder rodar o manifesto e poder fazer o download. qual método usar nesse caso?
pq com a chave de acesso em mãos é fácil. e quando não tem?
eu sei q isso vem por email e tals. mas daí é processo manual.
mas vi sistemas q já puxam essas chaves e fazem o manifesto e o download tudo automático.
te como fazer isso com nfephp?
