### ISSUE TITLE
Bug: Calculo do total da tag vFCPSTRet

### ISSUE THREAD

**Issue by KelwinMello** [nfephp-org/sped-nfe#513]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte

## Comportamento esperado
Ao usar a função `tagICMSTot` da classe `Make`, quando informado nos itens vFCPSTRet, deve ser calculado automaticamente o `NFe/infNFe/total/ICMSTot/vFCPSTRet`.

## Comportamento Atual
Mesmo informando `vFCPSTRet` nos itens, no total não é informado, resultando na rejeição ao enviar para a receita: `Rejeição 859 - Total do FCP retido anteriormente por Substituição Tributária difere do somatório dos itens`

## Solução possível
Na classe `Make linha 3980` alterar:
`$this->stdTot->vFCPSTRet += (float) !empty($std->vFCPST) ? $std->vFCPSTRet : 0;`
para 
`$this->stdTot->vFCPSTRet += (float) !empty($std->vFCPSTRet) ? $std->vFCPSTRet : 0;`

**Comment by NewtonMan** [comment]
Ola @KelwinMello acabei de mandar um pull com a correção.

Obrigado pela ajuda!

**Comment by robmachado** [comment]
Corrigido em MASTER, em breve subo o release
