### ISSUE TITLE
Validação de TXT de uma NFe no modelo 4.00

### ISSUE THREAD

**Issue by falinhares** [nfephp-org/sped-nfe#520]
Quando eu uso o código sugerido para validar o TXT de uma nota no novo modelo (4.00) eu recebo os seguintes erros:

  0 => string 'ERRO:  Todas as linhas devem terminar com 'pipe'. [NOTAFISCAL|1]' (length=64)
  1 => string 'ERRO: O número de parâmetros na linha está errado (esperado #5) -> (encontrado #4). [ A|4.00|NFe53180822355902000183550010000001281003400057| ] Esperado [ A|versao|Id|pk_nItem| ]' (length=181)
  2 => string 'ERRO: Existem caracteres especiais, acentos ou aspas em algum campo dos dados. [C|COSINERGIA FINAN&Ccedil;AS &amp; EMPREENDEDORISMO LTDA ME|COSINERGIA FINAN&Ccedil;AS &amp; EMPREENDEDORISMO LTDA ME|0771982200122||0771982200122|7020400|3|]' (length=238)
  3 => string 'ERRO: Existem caracteres especiais, acentos ou aspas em algum campo dos dados. [C|COSINERGIA FINAN&Ccedil;AS &amp; EMPREENDEDORISMO LTDA ME|COSINERGIA FINAN&Ccedil;AS &amp; EMPREENDEDORISMO LTDA ME|0771982200122||0771982200122|7020400|3|]' (length=238)
  4 => string 'ERRO: O número de parâmetros na linha está errado (esperado #25) -> (encontrado #22). [ W02|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|21600.00|1868.40| ] Esperado [ W02|vBC|vICMS|vICMSDeson|vFCP|vBCST|vST|vFCPST|vFCPSTRet|vProd|vFrete|vSeg|vDesc|vII|vIPI|vIPIDevol|vPIS|vCOFINS|vOutro|vNF|vTotTrib|vFCPUFDest|vICMSUFDest|vICMSUFRemet| ]' (length=387)
  5 => string 'ERRO: Essa referência não está definida. [W04c|0.00|]' (length=56)
  6 => string 'ERRO: Essa referência não está definida. [W04e|0.00|]' (length=56)
  7 => string 'ERRO: Essa referência não está definida. [W04g|0.00|]' (length=56)
  8 => string 'ERRO: O número de parâmetros na linha está errado (esperado #3) -> (encontrado #2). [ Y| ] Esperado [ Y|vTroco| ]' (length=116)
  9 => string 'ERRO:  Todas as linhas devem terminar com 'pipe'. [YA]' (length=54)
  10 => string 'ERRO: Essa referência não está definida. [YA01|0|01|19191.60|]' (length=65)

Me parece que está sendo feita uma validação para o modelo 3.10 ainda. Como posso indicar q a nota que carreguei no TXT é a 4.00?

        //validar TXT de uma NFe
        use NFePHP\NFe\Common\ValidTXT;
        $txt = file_get_contents('./files/modelo_nfe_400.txt');
        $errors = ValidTXT::isValid($txt);
        var_dump($errors);

**Comment by robmachado** [comment]
O Formato do TXT que deve ser usado é esse https://github.com/nfephp-org/sped-nfe/blob/master/docs/txtlayout400.md

**Comment by falinhares** [comment]
Vou adaptar o meu código. Muito obrigado!

**Comment by avandrevitor** [comment]
@falinhares e @robmachado  tive problemas recentes também com o formato as linhas W02 e N02 estão seguindo o formato da 3.10.

Fizemos alguns testes aqui ao importar pelo emissor gratuito 4.0

**Comment by robmachado** [comment]
Tem a estrutura dos dois padrões aqui
[Padrão API LOCAL](https://github.com/nfephp-org/sped-nfe/blob/master/docs/txtlayout400.md)
[Padrão SEBRAE](https://github.com/nfephp-org/sped-nfe/blob/master/docs/txtlayout400_sebrae.md) EM DESENVOLVIMENTO

**Comment by PabloAPereira** [comment]
Boa tarde Roberto.

A documentação Padrão API local tem uma divergencia na documentação, tentei arrumar, mas não tenho permissão ;-).

Atual -> O|CNPJProd|cSelo|qSelo|cEnq|
API -> O|clEnq|CNPJProd|cSelo|qSelo|cEnq| ]

ERRO: O número de parâmetros na linha está errado (esperado #7) -> (encontrado #6). [ O||||999| ] Esperado [ O|clEnq|CNPJProd|cSelo|qSelo|cEnq| ]

**Comment by robmachado** [comment]
Na verdade não existe divergência esse campo foi alterado mesmo 
"O":"O|CNPJProd|cSelo|qSelo|cEnq|",

**Comment by robmachado** [comment]
Mas essa alteração somente existe em MASTER ou pelo menos deveria estar apenas lá ..

**Comment by robmachado** [comment]
Ainda não houve o lançamento do RELEASE para esse caso !

**Comment by robmachado** [comment]
Já foi feito o RELEASE. Fique atento ao formato do TXT
Quanto ao formato SEBRAE ainda não foi totalmente concluido
