### ISSUE TITLE
Bug ao gerar Hash QRcode NFCe

### ISSUE THREAD

**Issue by PlaynowGames** [nfephp-org/sped-nfe#527]
Amigos, ao emitir uma NFCe e gerar o QRCode esta ocasionando um erro na URL da consulta e com isso a HASH esta ficando errada ao comparar no SEFAZ

src\Factories\QRCode.php na linha 210
if (strpos($url, '?p=') === false) {
            $url = $url.'?p=';
 }

a url está ficando com 2 pontos de ?? e ocasionando a Rejeição (464): Código de Hash no QR-Code difere do calculado

após retira um ? o erro foi solucionado.

abraços!

**Comment by fmertins** [comment]
Olá, que estranho, já faz algumas semanas, fiz testes e uso de geração de NFC-e e foi tudo normal e tudo certo...

**Comment by PlaynowGames** [comment]
então, assim que fiz um composer update começou a dar esse erro, fui investigando até chegar nessa parte do qrcode 2.0, antes tava normal porque estava emitindo com qrcode 1.0

**Comment by robmachado** [comment]
Não pode existir nenhuma "?" nos endereços do arquivo storage/wsnfe_4.00_mod65.xml
E atualmente não existe nenhuma "?" nesses endereços em master, mas o release 5.0.61 ainda tinha esses erros. Eu subi o release 5.0.62 com a correção.

**Comment by PlaynowGames** [comment]
obrigado roberto!

**Comment by edimar27** [comment]
Me ajudou muito @PlaynowGames ! Obrigado.
