### ISSUE TITLE
Erro ao consultar cadastro cliente sefaz rs

### ISSUE THREAD

**Issue by mateusperego** [nfephp-org/sped-nfe#528]
* **Estou enviando um ...**
  - [ X ] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **
Linux CentOS 7.2, apache com php 5.6.

  - Versão do leiaute:
 "nfephp-org/sped-nfe": "^5.0",

## Comportamento esperado
Ao consultar um cliente pelo sefazCadastro retornar os dados do contribuinte encontrado.

## Comportamento Atual
Ao consultar cliente com UF do RS, retorna mensagem dizendo:
Este serviço [NfeConsultaCadastro] não está disponivel para esta unidade da federação [RS] ou para este modelo de Nota [55].

## Solução possível
Adicionado o link: https://cad.sefazrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro4.asmx . NfeConsultaCadastro dentro da homologação e consultou tanto para homologação como produção.

**Comment by robmachado** [comment]
Corrigido em master, será incluso no próximo release
