### ISSUE TITLE
Erro ao consultar cadastro cliente sefaz DF

### ISSUE THREAD

**Issue by LukasMeine** [nfephp-org/sped-nfe#530]
Este serviço [NfeConsultaCadastro] não está disponivel para esta unidade da federação [DF] ou para este modelo de Nota [55].

Este é um comportamento esperado? Achei estranho, já que na documentação consta que:

>Estados atendidos: NFe (modelo 55) TODOS

**Comment by lukinhaspm** [comment]
Tarde, todos nesse caso refere-se a Emissão de NFe, o serviço de consulta a cadastros NÃO é disponibilizado por todos os estados, outro exemplo é o RJ. Entrei em contato recentemente e eles reafirmaram não ter nenhum webservice para consulta de cadastros.
