### ISSUE TITLE
Erro ao emitir nota fiscal DF

### ISSUE THREAD

**Issue by LukasMeine** [nfephp-org/sped-nfe#531]
Ambiente de homologação, erro encontrado ao usar a sigla DF.

Message: An error occurred while trying to communication via soap, [https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx]HTTP/1.1 100 Continue HTTP/1.1 404 Not Found Cache-Control: private Content-Type: text/html; charset=utf-8 Server: Microsoft-IIS/7.5 X-AspNet-Version: 4.0.30319 X-Powered-By: ASP.NET Date: Mon, 17 Sep 2018 20:37:01 GMT Content-Length: 1939

Aparentemente o sistema seta para a URL do RS quando uso a sigla do DF, e ela não funciona. Alguma ideia do porquê?

código que estou usando:

```
$xml = $nfe->getXML();

$config = [
   "atualizacao" => "2018-02-06 06:01:21",
   "tpAmb" => 2, // Se deixar o tpAmb como 2 você emitirá a nota em ambiente de homologação(teste) e as notas fiscais aqui não tem valor fiscal
   "razaosocial" => "Empresa teste",
   "siglaUF" => "DF",
   "cnpj" => "CNPJ",
   "schemes" => "PL_008i2",
   "versao" => "3.10",
   "tokenIBPT" => "AAAAAAA"
];
$configJson = json_encode($config);

$certificadoDigital = file_get_contents('certificado.pfx');

$tools = new NFePHP\NFe\Tools($configJson, NFePHP\Common\Certificate::readPfx($certificadoDigital,'senha'));
$xmlAssinado = $tools->signNFe($xml);

$idLote = str_pad(100, 15, '0', STR_PAD_LEFT); // Identificador do lote
$resp = $tools->sefazEnviaLote([$xmlAssinado], $idLote);
```

**Comment by andre-vinicius** [comment]
Boa tarde,

Mas você está utilizando a versão 3.10? Essa versão de XML para NF-e foi descontinuada e acredito que os serviços também. Eu acredito que seja por causa disso.
E o DF utiliza a Sefaz Virtual do Rio Grande do Sul SVRS.

Você pode buscar mais informações em:
http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=
https://groups.google.com/forum/#!forum/nfephp

**Comment by LukasMeine** [comment]
Obrigado!
