### ISSUE TITLE
feature - baixar nota com chave de autenticação - inserir o codigo e baixar o xml da nota

### ISSUE THREAD

**Issue by alvarolordelo** [nfephp-org/sped-nfe#534]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [x ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
<! --- Diga-nos o que deve acontecer ->

## Comportamento Atual
<! --- Diga-nos o que acontecer em vez do comportamento esperado ->

## Solução possível
<! --- Não é obrigatório, mas sugere uma correção / razão para o bug, ->

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
01 - Baixar a nota fiscal da sefaz de forma a introduzir apenas a chave de acesso.
02 - Apos baixar ler o xml da nota

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Parceiro!
Isso depende da origem da NFe, se for uma nota de terceiros destinada a você OK já existe
Se for uma NFe emitida por você,  NÃO EXISTE nem existirá essa funcionalidade !!! 
Nesse caso tem que usar a pagina de consulta da SEFAZ

Roberto

**Comment by alvarolordelo** [comment]
Senhor Roberto, tudo bem?
O que quis me referir é a possibilidade de importar pela api uma nota (XML) com a chave de acesso, caso já exista essa funcionalidade fico grato, 
Exemplo:
Comprei de um fornecedor uma lista de produtos e preciso dar entrada no meu cadastro desses itens, logo com a chave de acesso (números de 44 posições) baixaria o XML da nota para posterior leitura.

**Comment by robmachado** [comment]
Essa funcionalidade existe no webservice da SEFAZ APENAS para as NFe destinadas ao seu CNPJ (ou de seus clientes, caso tenha um ERP).
VIDE https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/Download.md
VIDE https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/DistDFe.md

**É muito mas muito importante você acessar e estudar os manuais de notas técnicas da SEFAZ, para entender o funcionamento e limitações desse método.**

Não existe nenhum serviço oficial (via webservice) capaz de baixar as NFe por você emitidas.

**Comment by falinhares** [comment]
Roberto,

Pq não existe nenhum serviço oficial para baixar as NFes emitidas de um CNPJ? Gostaria de baixar estes XMLs para ajudar a um escritório de contabilidade a ter certeza que o cliente enviou todas as NFes emitidas e coibir eventuais fraudes de emissões de NFe sem o conhecimento do meu cliente.

Obrigado,

**Comment by robmachado** [comment]
## Parta do seguinte raciocínio:
- Quem emite deve possuir as suas próprias NFes
- Essa posse é determinada por questões inclusive LEGAIS, seja o **emitente é OBRIGADO LEGALMENTE a manter os XML** das suas próprias NFes 
- Portanto não há a necessidade de baixar algo que o emitente já possui.

## Quanto à questão Contador:
- Existe um campo na NFe,  o "AutXML" onde o emitente pode incluir o CNPJ ou o CPF do contador e com isso fica autorizado que o contador BAIXE as NFe desse emitente, desde que utilize o seu certificado eCPF ou eCNPJ  (me refiro ao contador), utilizando o serviço do DFe.

**Comment by falinhares** [comment]
Entendo seu ponto Roberto. O meu ponto é quando alguém de ma fé rouba um certificado digital e emite uma NFe com este certificado sem o conhecimento do dono do certificado digital ou do contador da empresa que possui o certificado digital. Ele emitindo sem usar o AutXML, a NFe vira fantasma e só aparecerá numa notificação da Receita informando que os tributos desta NFe não foram recolhidos.

A idéia é pegar preventivamente estas situações, uma vez que alguns escritórios de contabilidade possuem dezenas de funcionários e alguns com acesso aos certificados dos clientes.

**Comment by robmachado** [comment]
## Não deixe o certificado ser roubado ! Não há alternativa ! 
### A SEFAZ não fornece esse recurso que você deseja !
O **certificado do emitente** deve ser protegido e pode ser de várias formas:
- nunca guarde o certificado na nuvem em um arquivo, prefira o banco de dados;
- não guarde a senha em "plain text" na base de dados use encriptação;
- não disponibilize o seu eCNPJ para qualquer um, o contador por exemplo não necessita desse certificado, ele pode usar o dele mesmo, mas para isto, será preciso ter uma procuração (para usar o eSocial por exemplo).

> NOTA: O sped-nfe não mantem os certificados PFX abertos no disco, ele grava em uma pasta temporária, com uma chave gerada em tempo de execução (apenas em memória) que não pode ser recuperada ao terminar a transmissão e o certificado que foi salvo temporariamente é então removido.

**Comment by falinhares** [comment]
Entendi. A SEFAZ devia implementar isso. É simples e seria um mecanismo de checagem importante para clientes.

Obrigado,

**Comment by asantos-lnascimento** [comment]
Vejo todas essas issues, queria só falar uma coisa @robmachado, n sei como vc aguenta isso!!

**Comment by robmachado** [comment]
Isso é normal !! Entender essas rotinas implica em estudar a documentação e muitas pessoas não gostam nem de ler, que dirá estudar.

**Comment by falinhares** [comment]
Eu li e estudei a documentação. Nem sempre ela é clara e por isso há a área de conversa. Acho desnecessárias e agressivas as colocações acima. Nunca faltei com o respeito com ninguém aqui e gostaria de ser igualmente respeitado.

**Comment by robmachado** [comment]
@falinhares 
Colega !!! não me referi a você, nem me refiro agora a ninguém em particular ... 
Me referi a todos que fazem questionamentos sem analisar e estudar. Agressivo ?!?! Sejamos profissionais, um comentário SEM indicar ninguém, não menciona nenhum nome, não referencia nada, apenas declara um FATO.
Uma enorme parcela de profissionais brasileiros, com nível superior, são "analfabetos funcionais", inclusive entre desenvolvedores e programadores (bem como entre todas as outras profissões). Quando o colega fez a menção sobre **"AS ISSUES"** ele não estava se referindo apenas a **"ESTA ISSUE"** e nem a você em particular.  Quem se enxergou ai foi você mesmo, é muito "mimimi" para um adulto.

**Comment by alvarolordelo** [comment]
A sefaz é um serviço publico, e no BR geralmente nenhum funciona bem de forma a sempre melhorar e atender aos seus usuários... todos aqui queremos um ambiente melhor e mais seguro, com funcionalidades que façam a vida da gente melhor....
É péssimo saber que algo assim não pode ser solicitado a sefaz já que beneficiaria a toda a comunidade.
Obrigado a todos que responderam a Issue.
