### ISSUE TITLE
Melhoria: revisão ocorrências "3.10"

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#539]
* **Estou enviando um ...**
  - [x] melhoria futura

## Contexto (Ambiente)
O layout 3.10 da NF-e morreu, remover ocorrências desta versão do layout na programação da API.

## Descrição detalhada
Existem 24 ocorrências da string "3.10" em 10 arquivos diferentes, revisa-las para substituir por algo como "4.00" ou se serão removidas, etc.

**Comment by robmachado** [comment]
Melhor alterar para 4.00 ! mas deixe que eu faço isso

**Comment by robmachado** [comment]
Corrigido !! em master por ora

**Comment by fmertins** [comment]
Show :+1:

**Comment by rafaelqm** [comment]
Eu utilizo a biblioteca para baixar as notas emitidas contra o CNPJ de um cliente, e ainda existem algumas notas no layout 3.10, seria à partir de quando que este layout morreu @fmertins ?

**Comment by robmachado** [comment]
@rafaelqm 
Não só o layout 3.10 não pode ser usado como quaisquer webservices vinculados a aquele layout (3.1) não estão mais disponíveis desde **2 agosto/2018**
