### ISSUE TITLE
v5.0 - Método 'addCancelamento' da classe Complements não aceita string xml como parâmetro

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/sped-nfe#54]
Redirecionando ....
Solicitado em:

https://github.com/nfephp-org/nfephp/issues/915

Estive olhando o método addCancelamento e notei que as variáveis '$pathNFefile' e '$pathCancfile', só aceitam como parâmetro um path para arquivo XML, uma sugestão seria que ele aceite também string XML, igual outras funções da mesma classe.

O outro ponto é uma sugestão/dúvida, que eu observei no manual de orientação do contribuinte é que no caso do cancelamento de nota podem ser aceitas de 1 a 20 notas por lote, mas o nfephp aceita somente 1. No meu caso isso não me afeta em nada, mas não sei se em um contexto mais geral isso seria interessante.

**Comment by robmachado** [comment]
Vamos fazer isso sim ... fazer as entradas dos dados serem em strings 

Quanto aos múltiplos cancelamentos simultâneos, isso terá de ser melhor estudado, mas até hoje (depois de 8 anos de uso) nunca fiz ou ouvi falar que alguêm tenha feito isso
