### ISSUE TITLE
Tools::sefazEnviaLote() -- Parâmetro $indSinc

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#541]
https://github.com/nfephp-org/sped-nfe/blob/29753ed3101be82846e6b656da18b53d09f7c20b/src/Tools.php#L58-L60

Olá, estava revisando esta linha e pensei, **talvez seria melhor levantar uma Exception** ao invés de _alterar silenciosamente_ o parâmetro enviado pelo código-cliente do método?

Exemplo: usuário quer autorizar lote com 3 NF-es e enviou $indSinc=1, talvez ele não sabe que isso é inválido porque a API acaba ajudando-o e transmitindo como 0-Síncrono... OK vai transmitir o lote mas depois ele vai ter que consultar o recibo, enquanto que no modo 1-Síncrono não existe número de recibo, correto?

Isso não pode ser meio perigoso/ruim para o código-cliente?

**Comment by robmachado** [comment]
É concordo com você ... seria mais prudente realmente disparar um exception ...

**Comment by robmachado** [comment]
Corrigido ! em master por ora
