### ISSUE TITLE
Erros de endereço de consulta de chave e qrcode para a BA

### ISSUE THREAD

**Issue by rozael** [nfephp-org/sped-nfe#547]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **
Homologação
  - Versão do leiaute: NFCE_4.00

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
Ao gerar o xml os endereços de consulta e qrcode que deveriam ser carregados são esses:
Estou usando "BA": "http:\/\/hinternet.sefaz.ba.gov.br\/nfce\/consulta", no arquivo uri_consulta_nfce.json e
http://hnfe.sefaz.ba.gov.br/servicos/nfce/qrcode.aspx no arquivo wsnfe_4.00_mod65.xml

## Comportamento Atual
Só que toda vez o xml é carregado com esses daqui:
<qrCode><![CDATA[http://hnfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx
<urlChave>http://hnfe.sefaz.ba.gov.br/servicos/nfce/default.aspx </urlChave>

## Solução possível
Mandaram eu alterar nos arquivos:
uri_consulta_nfce.json e wsnfe_4.00_mod65.xml mas nao adianta ele continua colocando errado na montagem do xml

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Vide http://nfce.encat.org/desenvolvedor/qrcode/

**Comment by robmachado** [comment]
Alterado o endereço do QRCode BA em homologação tag v5.0.64 
Atenção a partir desse release somente PHP7.x !!!

**Comment by rozael** [comment]
O endereço do QRCODE esta ok agora!!
Mas o http:\/\/hinternet.sefaz.ba.gov.br\/nfce\/consulta do arquivo uri_consulta_nfce continua montando errado, no arquivo esta certo e é esse dai de cima.
vou postar o trexo do xml:

<qrCode><![CDATA[http://hnfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx?chNFe=29180996719000000115650010000000021000002586&nVersao=100&tpAmb=2&dhEmi=323031382d30392d32385432313a35323a35312b30303a3030&vNF=20.00&vICMS=0.00&digVal=5764386b515669616538444e64754b6c666b58555853484f4a33493d&cIdToken=000001&cHashQRCode=1AAAC5CD70BEC31893DFBB8ABBA640AE51B3E641]]></qrCode>
      <urlChave>http://hnfe.sefaz.ba.gov.br/servicos/nfce/default.aspx </urlChave>

**Comment by rozael** [comment]
Ele continua carregando esse daqui
http://hnfe.sefaz.ba.gov.br/servicos/nfce/default.aspx e so quando eu mudo pra esse manualmente é q funciona: http:\/\/hinternet.sefaz.ba.gov.br\/nfce\/consulta
