### ISSUE TITLE
src/Factories/Parser.php -- Revisar métodos vazios

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#549]
https://github.com/nfephp-org/sped-nfe/blob/072981d44784426b56996db34af5f9d2f3ac168a/src/Factories/Parser.php#L212-L216

Temos alguns métodos vazios nesta classe, podem ser excluídos? Não encontro referências a eles, parecem não ser usados...

Exemplos:
protected function baEntity($std)
protected function nEntity($std)
protected function wEntity($std)

**Comment by robmachado** [comment]
Não podem ser removidos .. por questão do construtor (por hora)

**Comment by fmertins** [comment]
Olá, ok...
Outra dúvida, aproveitando a issue, se quero criar a classe de teste tests/Common/WebservicesTest.php e dentro dela preciso ler algum arquivo XML dos webservices, que estão em storage/wsnfe_4.00_mod55.xml, posso fazer isso ou digamos que preciso copiar o mesmo arquivo para dentro da pasta de fixtures?

**Comment by fmertins** [comment]
Exemplo, precisaríamos ter fixtures/storage?

**Comment by robmachado** [comment]
Fernando ! sinta-se a vontade para propor e fazer o PR que achar que deve ser feito.
Qualquer ajuda como eu sempre disse é bem vinda :+1:
