### ISSUE TITLE
Erros de endereço de consulta de chave BA

### ISSUE THREAD

**Issue by rozael** [nfephp-org/sped-nfe#550]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **
Homologação
  - Versão do leiaute:Versão do leiaute: NFCE_4.00

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
Ao gerar o xml o endereço de consulta e que deveria ser carregado é esse:
Estou usando "BA": "http://hinternet.sefaz.ba.gov.br/nfce/consulta", no arquivo uri_consulta_nfce.json 

## Comportamento Atual
Só que toda vez o xml é carregado com esse daqui: http://hnfe.sefaz.ba.gov.br/servicos/nfce/default.aspx 

## Solução possível
Mandaram eu alterar o arquivo:
uri_consulta_nfce.json mas nao adianta ele continua colocando errado na montagem do xml

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Em teste local foi gerado o seguinte:
```
<qrCode>
<![CDATA[
http://hnfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx?p=29181033657677000156650010001654399001654399|2|2|01|150.00|6d395a7251544b4d7876374131426c6e662f6e6d4e4756582b4e383d|1|9C886E1A36ADC68CAFDF114F3424CD30E8371631
]]>
</qrCode>
<urlChave>http://hinternet.sefaz.ba.gov.br/nfce/consulta</urlChave>
```
Não é esse o comportamento esperado ?

**Comment by rozael** [comment]
Boa noite Rob!! Obrigado pela atenção!!
Quanto ao qrcode a sua modificação resolveu e agora esta ok!!
Mas o problema é a url de consulta q continua carregando essa abaixo!

<qrCode><![CDATA[http://hnfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx?chNFe=29180996719000000115650010000000021000002667&nVersao=100&tpAmb=2&dhEmi=323031382d30392d32385432333a34393a34392b30303a3030&vNF=20.00&vICMS=0.00&digVal=657246746f416e6c556964777642726e667a6343735173664b4f673d&cIdToken=000001&cHashQRCode=DE9D180C26342C41D62C4F85F0A93EC6FE35BBC6]]></qrCode>
      <urlChave>http://hnfe.sefaz.ba.gov.br/servicos/nfce/default.aspx </urlChave>
