### ISSUE TITLE
Nome Operação Incorreta para RecepcaoEvento / MT no wsnfe_4.00_mod65.xml 

### ISSUE THREAD

**Issue by fabiomigliorini** [nfephp-org/sped-nfe#552]
Corrigir o operation de **NFeRecepcaoEvento** para **NFeRecepcaoEvento4** da url https://nfce.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento4

**Comment by robmachado** [comment]
OK no bloco Produção para MT
