### ISSUE TITLE
Sugestão de melhoria na documentação

### ISSUE THREAD

**Issue by juizmill** [nfephp-org/sped-nfe#562]
Estou trabalhando em um projeto no qual estamos usando a biblioteca **sped-nfe** e ao analisar o código já desenvolvido percebi que tinha uma variável chamada **$elem** por todo o código. 

Vim até a documentação e reparei que ela também está aqui. 

Acho melhor remover ela da documentação, sabendo que não tem a necessidade da mesma.

**Comment by fmertins** [comment]
Bom dia, teria um ou dois exemplos?

**Comment by nagahshi** [comment]
se fizesse uma PR então 😄

**Comment by juizmill** [comment]
@fmertins @nagahshi aqui está um exemplo https://github.com/nfephp-org/sped-nfe/pull/563

**Comment by fmertins** [comment]
Ah, é só na classe Make então pelo que entendi? Blz...

**Comment by juizmill** [comment]
@fmertins Sim! Na documentação, acho melhor remover a variável **$elem** para não confundir as pessoas..
