### ISSUE TITLE
Exemplo com front end básico e comentários nos parâmetros do xml 🚀🚀

### ISSUE THREAD

**Issue by LukasMeine** [nfephp-org/sped-nfe#565]
Fizemos um exemplo com um front end basicão e consultamos um contador pra podermos comentar em cima da maioria dos parâmetros que são passados no xml! Queríamos deixar aqui para ajudar quem possa precisar :) 

https://github.com/citaralabs/emissor-nota-fiscal

**Comment by robmachado** [comment]
Muito Legal da parte de você fornecerem essa ajuda !! 
:+1:  :1st_place_medal:

**Comment by robmachado** [comment]
faça a sua apresentação do seu projeto, para o pessoal do grupo NFePHP tenho certeza que vai ajudar muitos iniciantes e até outros mais experientes que não tem conhecimentos fiscais.

**Comment by LukasMeine** [comment]
Vou fazer sim, muito obrigado pelo feedback! 🚀🎉
