### ISSUE TITLE
Tools.php - $soapnamespaces (An error occurred while trying to communication via soap)

### ISSUE THREAD

**Issue by silvagpe** [nfephp-org/sped-nfe#572]
* **Estou enviando um ...**
  - [x ] bug

Olá,
Estou testando a Framework, e realizando um teste simples de comunicação com a Sefaz RS encontrei  um problema de BadRequest. Talvés isso não ocorra em outros estados.

O problema ocorre no evento sefazStatus "NfeStatusServico4"
https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx

* ** Por favor, conte-nos sobre o seu ambiente: **
PHP 7.1, "schemes" => "PL_009_V4",  "versao" => '4.00',
UF = RS

## Comportamento esperado  
SoapCurl => $httpcode == 200

{ "attributes": { "versao": "4.00" }, "tpAmb": "2", "verAplic": "RS201805211008", "cStat": "107", "xMotivo": "Servico em Operacao", "cUF": "43", "dhRecbto": "2018-11-15T22:59:23-02:00", "tMed": "1" }

## Comportamento Atual 
SoapCurl => $httpcode == 400

An error occurred while trying to communication via soap, [https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx]HTTP/1.1 400 Bad Request Cache-Control: private Content-Type: application/soap+xml; charset=utf-8 Server: Microsoft-IIS/7.5 X-AspNet-Version: 4.0.30319 X-Powered-By: ASP.NET Date: Fri, 16 Nov 2018 00:59:03 GMT Content-Length: 0

## Solução possível
Se for possível alterar o namespace e não refletir nos demais estados.

Alterar de **xmlns:soap** para **xmlns:soap12** com essa alterção consegui o retorno esperado pela sefaz.

sped-nfe/src/Common/Tools.php
```
protected $soapnamespaces = [
        'xmlns:xsi' => "http://www.w3.org/2001/XMLSchema-instance",
        'xmlns:xsd' => "http://www.w3.org/2001/XMLSchema",
        'xmlns:soap12' => "http://www.w3.org/2003/05/soap-envelope"
    ];
```

## Passos para reproduzir
```
error_reporting(E_ALL);
ini_set('display_errors', 'On');

require __DIR__ . '/vendor/autoload.php';

use NFePHP\Common\Certificate;
use NFePHP\NFe\Common\Standardize;
use NFePHP\NFe\Tools;

//define('SOAP_1_2', 'SOAP_1_2');

try {

    $arr = [
        "atualizacao" => date('Y-m-d h:i:s'),
        "tpAmb" => 2,
        "razaosocial" => "DISTRIBUIDORA...",
        "cnpj" => "25...",
        "siglaUF" => "RS",
        "schemes" => "PL_009_V4",
        "versao" => '4.00',
        "tokenIBPT" => "AAAAAAA",
        "CSC" => "6A...",
        "CSCid" => "0...",
        "proxyConf" => [
            "proxyIp" => "",
            "proxyPort" => "",
            "proxyUser" => "",
            "proxyPass" => "",
        ],
    ];
    $configJson = json_encode($arr);

    $certificadoDigital = file_get_contents('DIST.pfx');
    $certificate = Certificate::readPfx($certificadoDigital, 'senha');
    $tools = new Tools($configJson, $certificate);
    $tools->model('55');
    //$uf = 'SP';
    //$tpAmb = 2;
    //$response = $tools->sefazStatus($uf, $tpAmb);
    //este método não requer parametros, são opcionais, se nenhum parametro for
    //passado serão usados os contidos no $configJson
    $response = $tools->sefazStatus();

    //você pode padronizar os dados de retorno atraves da classe abaixo
    //de forma a facilitar a extração dos dados do XML
    //NOTA: mas lembre-se que esse XML muitas vezes será necessário,
    //      quando houver a necessidade de protocolos
    $stdCl = new Standardize($response);
    //nesse caso $std irá conter uma representação em stdClass do XML
    $std = $stdCl->toStd();
    //nesse caso o $arr irá conter uma representação em array do XML
    $arr = $stdCl->toArray();
    //nesse caso o $json irá conter uma representação em JSON do XML
    $json = $stdCl->toJson();

    echo $json;

} catch (\Exception $e) {
    echo $e->getMessage();
}

```

Obrigado pela atenção.

**Comment by robmachado** [comment]
Em testes locais e usando varios servidores NÃO FOI POSSIVEL  reproduzir o erro que você encontrou.
Possivelmente, pode ter ocorrido por alguma instabilidade no servidor. Ou por algo no seu servidor.

**Comment by silvagpe** [comment]
Bom dia Roberto,
Na verdade eu estou avaliando para migrar minha aplicação C# para PHP e só encontrei o erro quando comparei o XML do evelope SOAP, então percebi que no projeto em PHP ele estava gerando o namespace dessa forma xmlns:soap="http://www.w3.org/2003/05/soap-envelope" e em C# xmlns:soap12="http://www.w3.org/2003/05/soap-envelope".  Quando ajustei o namespace passou a funcionar a comunicação. 

Mas para evitar impacto no código seria possível externar essa configuração em um aquivo json ou passar por parametro (array de namespaces) alguma coisa do tipo?

**Comment by robmachado** [comment]
Farei testes para verificar qual seria a melhor solução.
Talvez todos trabalhem normalmente em ambas as versões do SOAP, então poderia passar todos eles para SOAP 1.2.
Mas eu testo regularmente TODOS os estados e no meu caso não EXISTE esse BUG.

**Comment by robmachado** [comment]
E na verdade já existe algo similar mas nas classes SOAP, que teriam de ser previamente criadas e injetadas o que também é possivel

**Comment by silvagpe** [comment]
Eu vi essa variável na classe SoapBase.php protected $prefixes = [1 => 'soapenv', 2 => 'soap']; 
Eu até alterei a minha versão para protected $prefixes = [1 => 'soapenv', 2 => 'soap', SOAP_1_2 => 'soap12']; porém ele não alterava o valor dos namespaces.

De qualquer forma vou mandar uma versão manualmente alterada equanto você avalia a melhor solução.

Obrigado pela atenção e se eu puder ajudar em algo é só falar.

**Comment by robmachado** [comment]
Realmente não encontrei forma alguma de reproduzir qualquer falha na comunicação SOAP da forma como esta a API atualmente. Portanto não farei alterações nesse ponto. Mas se mais alguém além de você reportar alguma falha nesse quesito voltamos ao assunto.

**Comment by silvagpe** [comment]
Ok, sem problemas. 
Por hora eu consigo ajustar sem mudar o código ogirinal, apenas herdando a classe tools
class CustomTools extends Tools{}
