### ISSUE TITLE
Erro emitir nfc-e modelo 65 em ambiente de homologação da Bahia

### ISSUE THREAD

**Issue by uilhianet** [nfephp-org/sped-nfe#577]
"xMotivo": "Rejeicao: Endereco do site da UF da Consulta por chave de acesso diverge do previsto"

**Comment by uilhianet** [comment]
Alguém sabe como faço para alterar os endereço?

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-nfe/blob/master/storage/uri_consulta_nfce.json

**Comment by robmachado** [comment]
Me informe a URL correta no caso ! para que possa corrigir na tabela

**Comment by uilhianet** [comment]
a unica diferença que encontrei em um nfce que a sefaz aceitou para um que ela rejeitou foi o seguinte,
ela aceitou com url(Emitido por outro sistema sem utilizar a biblioteca):
http://hinternet.sefaz.ba.gov.br/nfce/consulta
e rejeitou com url (usando o a biblioteca)
hinternet.sefaz.ba.gov.br/nfce/consulta

**Comment by uilhianet** [comment]
transmitiu é isso mesmo.
O endereço é 
<urlChave>http://hinternet.sefaz.ba.gov.br/nfce/consulta</urlChave>

**Comment by tdsereno** [comment]
Versão 4.0 – Utilização obrigatória a partir de 01/10/2018:
http://nfe.sefaz.ba.gov.br/servicos/nfce/qrcode.aspx (deverá compor o QR Code para
acesso ao endereço de consulta)
Após a página, deve ser inserido o caractere “?” e os parâmetros."

Fonte:
https://nfe.sefaz.ba.gov.br/servicos/nfce/documentos/configuracao_programa_emissor_REV_3.pdf
