### ISSUE TITLE
O que seria Padrão Sebrae?

### ISSUE THREAD

**Issue by jgustavo99** [nfephp-org/sped-nfe#578]
Olá!

"A conversão com o PADRÂO SEBRAE ainda está incompleta!!"

O que seria o PADRÃO SEBRAE aonde o pacote está incompleto?

**Comment by robmachado** [comment]
Padrão SEBRAE é o do emissor gratuito !
E requer engenharia reversa para ser construído, pois não existe manual com referencia ao padrão TXT gerado pelo emissor gratuito, agora mantido pelo SEBRAE.
