### ISSUE TITLE
v5.0 - Sugestão Debug Exceptions

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/sped-nfe#58]
Uma coisa que eu já encontrei observando as classes internas do nfephp é que ele tem umas classes independentes de Exceptions, e isso é bom. Mas você poderia melhorar isso, ou pelo menos facilitar esse reconhecimento por parte dos usuários sobre os tipos de Exceptions(do nfephp) disponíveis.

Ou você poderia documentar quais as Exceptions que normalmente o nfephp pode gerar, ou seja, especificar para que aqueles Exceptions personalizados servem e quando eles aparecem.

É muito incômodo ter que ficar revirando a API para descobrir essas coisas, sem contar o risco de estragar algo que estava funcionando.

Outro ponto é que vocês podiam definir um nível de log para esses Exceptions da api, colocar um identificador em algum lugar da string da Exception  ou lançar essa string da Exception como um json, onde seria possível identificar o que é erro de problemas não ligados diretamente a nota ( erro de leitura de arquivos, problema de ssl) e o que são problemas realmente ligados a nota como falhas na validação, problemas de envio.

Enfim, gerar alguma forma que facilite identificar o que são erros que só nós programadores devemos saber e o que são erros que usuários podem ver, ou pelo menos documentar o que pode aparecer.

Isso é uma simples sugestão, a viabilidade disso no contexto geral, só vocês podem dizer.

Desde já  obrigado pela atenção.

**Comment by robmachado** [comment]
Sim suas observações são muito relevantes, estou sempre aberto a sugestões e se quiser/puder ajudar nesse quesito eu agradeceria.
Estou revisando e reescrevendo a  API para sua próxima versão 5.0, na branch v5.0, e estou tentando documentar as coisas um pouco mais dê uma olhada no repositório e se tiver sugestões com alguma ajuda no código melhor ainda

**Comment by ianclever** [comment]
No por esses dias não vou poder ajudar com código, porque estou correndo para colocar meu emissor de NFC-e para funcionar.

Mas vou ter que criar algo parecido nele, depois que eu definir isso eu dou uma ideia, mais palpável.

Agora quando submeter código, eu até quero, mas eu ainda não entendo bem o funcionamento do git, e nas classes internas eu fico receoso de quebrá-las, mas se você der uma supervisão posso fazer assim que folgar aqui.

**Comment by ianclever** [comment]
Uma vaga noção de como fazer isso eu já tenho.

Uma boa definição seria separar classes de erros comuns, ex.:

erroComunicacao para aquelas questões de timeout, envio de pacotes ....
erroES ou erroIO para as questões relacionadas a arquivos ...

e assim sucessivamente.

dentro dessas grandes classes você podia definir códigos de erros que identificam o erro específico.

aí na hora de disparar a Exception você lançaria uma string json com algo assim:

'{"erroComunicacao":{"cod" : "0", "erro" : "erro aqui"}}'

Assim o cara pega isso e no debug do sistema dele pode filtrar esse json e tudo que for erroComunicacao

ele transforma num array de erro como algo tipo:

'{"erroComunicacao":[{"cod" : "0", "erro" : "erro aqui"}, {"cod" : "0", "erro" : "erro aqui"}]}'

e aí ele se vira e decide qual classe de erro é interessante para ele, pode até fazer um objeto dos erros
para log como:

'[ {"erroComunicacao":[{"cod" : "0", "erro" : "erro aqui"}, {"cod" : "0", "erro" : "erro aqui"}]},
{"erroIO":[{"cod" : "0", "erro" : "erro aqui"}, {"cod" : "0", "erro" : "erro aqui"}]} ]'.

**Comment by robmachado** [comment]
Ian;
Você deve dar uma olhada em sped-common v5.0 lá as classes comuns estão sendo separadas e tem seus próprios Exceptions, falta melhorar a documentação

**Comment by ianclever** [comment]
Sobre a questão de especificar um código de para cada erro específico dentro das classes de Exception, eu vi ontem que no construtor da Classe Exception do php tem um parâmetro onde você pode atribuir um código de erro.

Você podia aumentar o nível de reconhecimento identificando também conjuntos de erros comuns dentro de cada classe.

Ex.: A classe IOException é para Exceptions relacionadas a erros de E/S, mas dentro desse conjunto maior existem ainda erros comuns, como por exemplo erro ao Abrir a Stream do arquivo, erros de Leitura de arquivos, erros de Escrita de arquivos, erros relacionados com permissões ...

Para esse conjunto de erros específicos podia definir um padrão de código, assim dá para saber qual a classe de erros e qual o Tipo de erro específico dentro da classe.

**Comment by robmachado** [comment]
Ian;
Estou revendo o código do sped-nfe e também acho que podemos melhorar bastante incluindo classes especificas de Exceptions nesse pacote também, e melhorar as classes no sped-common

**Comment by ianclever** [comment]
Eu gerei uma versão de exceptions para o emissor aqui da empresa, mas não sei se ele serve para o propósito geral e é baseado na versão anterior do nfephp.
O que eu posso é liberar as exceptions e alguns exemplos, porque o código do emissor é da empresa, e por questões de segurança também. Na minha versão eu consegui fazer os tratamentos, mas acabou ficando direcionado. Você se interessa em dar uma olhada? Se sim eu crio uns exemplos de uso.
É um uso não padrão das exceptions mas funcionou para o que eu queria.

**Comment by robmachado** [comment]
Claro que interessa :+1: 

Pode me mandar os trechos de código para meu email linux.rlm@gmail.com
