### ISSUE TITLE
Lote em processamento

### ISSUE THREAD

**Issue by jgustavo99** [nfephp-org/sped-nfe#580]
Olá, Boa noite!

Quando o lote estiver em processamento na consulta do recibo, vocês aconselham aguardar ser retornado algo (colocar em um loop)?

**Comment by robmachado** [comment]
É melhor você LER a documentação a respeito de contingência !!
Mas esclarecendo:
1 - se a NFe já foi envia e recebida NUNCA TENTE a mesma NFe em contingência NEVER
2 - a contingência não é SUA escolha para ativar quando desejar !! É a SEFAZ quem ativa a contingência e apenas ela. Aqui em SP ja ficamos mais de 6 horas sem emissão porque a SEFAZ estava com problemas e a contingência NÃO FOI autorizada pela SEFAZ !!! Tem que ficar de  olho no SITE da SEFAZ para ver se a contingência foi ativada ou não !!

**Comment by jgustavo99** [comment]
Como assim o Sefaz ativa a contigencia?

Pelo que eu entendi se o retorno demorou da NFC-e, ou o servidor ficar inacessível já gero uma contingência offline...

E para cada nota não posso ficar vendo status do Sefaz pois é consumo indevido

**Comment by robmachado** [comment]
Isso é verdade APENAS para NFCe e não para SP nem CE onde deve ser usado o SAT

Mas no caso da NFe  (modelo 55) é o que eu disse anteriormente !! Modelos diferente regras diferentes !

**Comment by robmachado** [comment]
POREM para as NFCe já enviadas eu tenho minhas duvidas de como agir ! (eu não uso NFCe então nesse caso não sei qual seria a forma correta)

**Comment by jgustavo99** [comment]
Como eu posso testar a contingência online (NFC-e)? Existe algum servidor do sefaz de teste para mim testar ele fora do ar? Ou se retornar uma exception no enviar lote já posso colocar como contingência?

**Comment by robmachado** [comment]
Colega o que significa OFF LINE ?? Se é OFF LINE não tem nenhuma conexão, não é !!
Um NFCe emitido OFF LINE não é transmitido até que esteja ON LINE recomendo que você ESTUDE a documentação da SEFAZ.

**Comment by jgustavo99** [comment]
Eu quis dizer contingência online (SEFAZ FORA DO AR ou TIMEOUT SEFAZ)...

Como eu poderia testar isso? Esperar o Sefaz ficar fora do ar não seria uma opção hehe...

Existe algum servidor para mim testar será?

Atualmente retornando um exception no envio do lote ou consulta do recibo eu já coloco como contingência.

**Comment by robmachado** [comment]
Essa não é uma boa solução !
Para NFCe, recomendo o seguinte:

0 - tente sempre usar modo SÍNCRONO para envio das NFCe (se disponivel), então nesse caso quando houver falha passe imediatamente para contingência OFF LINE

Se não houver disponibilidade de modo síncrono, então a aplicação deveria ser pensada de forma diferente trabalhando sob eventos, gerenciados por um processo em backend (ex. daemon PHP ou algo do tipo).

1 - falha no envio da NFCe (a nota não foi recebida)
     ---> teste o status da SEFAZ   
            ---> se retornar SUCESSO 
                   ---> tente enviar a NFCe novamente 
                           ---> se falhar alterne para CONTINGÊNCIA OFF LINE e gere a NFCe
            ---> se houver nova falha alterne para CONTINGÊNCIA OFF LINE e gere a NFCe

2 - NFCe enviada com sucesso (recebido o recibo)
      ---> falha ao buscar a autorização da NFCe emitda
            ---> teste o status da SEFAZ   
                   ---> se retornar SUCESSO 
                          ---> tente  novamente
                                 ---> se falhar novamente passe para contingência OFF LINE
                                  ---> cancele a NFCe anterior (deverá ser enviada assim que a conexão retornar)
                                  ---> emita nova NFCe OFF LINE

**_NOTA: isso é uma visão ainda bem SIMPLISTA do processo em si._**

**Comment by jgustavo99** [comment]
E como faço no modo SÍNCRONO? Pelo que eu vi a doc só via ASÍNCRONO

**Comment by robmachado** [comment]
O método sefazEnviaLote() recebe ou pode receber os seguintes parâmetros:
```php
sefazEnviaLote(
        $aXml, //array com o XML da NFCe (recomendo sempre uma por vez)
        $idLote = '', //numero do lote para seu controle
        $indSinc = 1, //indicador de uso síncrono de for 1 ou true ativa modo síncrono  
        $compactar = false, //compacta a mensagem (muitos SEFAZ não aceitam)
        &$xmls = [] //importante para você
)
```
NOTAS: 
1 - o modo síncrono não funciona em todas as SEFAZ, terá de testar antes. Além disso a logica muda pois no modo síncrono os dados de resposta são diferentes, já será retornado o protocolo em muitos casos
2 - o ultimo parâmetro, passado como referencia, retornará em um array as NFCe completas com os dados de QRCode, para você poder gravar em sua base.

**Comment by lukBarros** [comment]
Minha ajuda e como está implementado na minha app.

Envio se retornar 105 eu espero 2 segundos e consulto se retornar 105 (ou 217) eu espero 3s e tento de novo, se por fim retornar 105 (ou 217) eu espero 3s e tento de novo, se na terceira não vem 100 eu pulo a numeração e tento em contigencia offline

*** PARA NFCe visse!
