### ISSUE TITLE
Carta de correção com CPF

### ISSUE THREAD

**Issue by mateusperego** [nfephp-org/sped-nfe#581]
* **Estou enviando um ...**
  - [ ] bug
  - [ X ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

## Descrição detalhada
Atualmente ao fazer uma carta de correção aceita apenas com emissor CNPJ, adicionar a opção de enviar uma CC-e com CPF.

## Possível implementação
No sefazevento ele pega o cnpj das configurações, testar se é um CNPJ ou CPF e criar no xml.

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Ao que conste da documentação, não existem alterações a serem feitas para emissão e qualquer evento com CPF.
Não existem alterações declaradas sobre as estruturas dos XMLs, nesses casos.

**Comment by mateusperego** [comment]
Posso estar interpretando errado, mas conforme a NT_2018_001_v.1.00 na página 18 fala sobre carta de correção com CPF. Inclusive para o RS eu enviei algumas cartas de correção em homologação e aceitou, só eu mudei manualmente a seguinte linha . "<CNPJ>$cnpj</CNPJ>" para . "<CPF>$cnpj</CPF>" dentro do evento. Me retornou 135-Evento registrado e vinculado a NF-e, protocolou o xml e gerou o DACCE normalmente.

**Comment by robmachado** [comment]
Então essa mudança não está documentada ! mas tudo bem vou promover a alteração visto que você já testou.

**Comment by mateusperego** [comment]
Ao atualizar ou baixar o pacote não está baixando as alterações para testar.

**Comment by robmachado** [comment]
Já foi enviado o release para isso !
