### ISSUE TITLE
Subtrair desconto da base de cálculo ICMS

### ISSUE THREAD

**Issue by Jack184** [nfephp-org/sped-nfe#584]
Olá. Existe alguma opção para subtrair automaticamente o desconto da base de cálculo total? Segue print em anexo.
![captura de tela 2018-12-04 as 10 58 41](https://user-images.githubusercontent.com/38541696/49443469-b3a5e300-f7b3-11e8-8b48-8bf44a2b4a7b.png)

**Comment by nagahshi** [comment]
O valor da base de calculo ai esta normal amigo, igual o valor de produtos.
nesse tipo ai ele só colocou o desconto normal

Em ter, 4 de dez de 2018 às 11:00, Jack184 <notifications@github.com>
escreveu:

**Comment by Jack184** [comment]
Isso quer dizer que preciso passar o valor do desconto em outro campo além de vDesc na tag produto?

**Comment by nagahshi** [comment]
Caso voce esta gerando manualmente os totais da NFe o desconto deve ser
preenchido lá tbm

Em ter, 4 de dez de 2018 às 16:31, Jack184 <notifications@github.com>
escreveu:

**Comment by nagahshi** [comment]
esse exemplo ai voce ta preenchendo o valor embranco '' que é convertido pra 0.00

faça isso:
```
                    /** Tag Total **/
                   $stdICMSTot = new stdClass();
                   $stdICMSTot->vTotTrib = 0;
                   $ICMSTot = $nfe->tagICMSTot($stdICMSTot);
```

**Comment by Jack184** [comment]
Irei testar e aviso @nagahshi . Obrigado desde já!

**Comment by Jack184** [comment]
A solução no @nagahshi funcionou. Fechando aqui!
