### ISSUE TITLE
Como validar os dados por tag, antes de prosseguir com a construção da NF

### ISSUE THREAD

**Issue by lukBarros** [nfephp-org/sped-nfe#585]
* **Estou enviando um ...**
  - [ x ] requisição de funcionalidade

  - Versão do leiaute:
4.00

## Comportamento esperado

Antes de usar por exemplo tagDest() eu poder usar o checkTagDest() que me volta true ou false para uma série de validações sobre os campos.

Por exemplo, ao mandar um checkTagDest() eu poderia receber um false caso o nome seja vazio, ou maior que o determinado no layout.

Por exemplo, ao mandar um checkTagTransp()  e receba um false caso do o campo modFrete estiver setado com um valor inválido.

## Comportamento Atual

Ajudar desenvolvedores a debugar e implementar validações de campos antes de 'queimar' um número com a chave gerada para um XML com falha no esquema.

**Comment by robmachado** [comment]
Eu já estou refatorando a classe Make tendo em vista os seguintes conceitos:
1 - os dados serão pré validados quanto ao tipo e formato
2 - cada TAG será desmembrada em uma sub classe separada para permitir maior facilidade na manutenção  e permitir um controle mais apurado e localizado dos parâmetros
Ainda não tem um prazo para terminar, mas já está adiantado.

**Comment by lukBarros** [comment]
Ótimo!!!

**Comment by lukBarros** [comment]
Vou fechar ok?
