### ISSUE TITLE
Problemas recorrentes com timeout

### ISSUE THREAD

**Issue by lukBarros** [nfephp-org/sped-nfe#587]
Venho recebendo esse retorno 

An error occurred while trying to communication via soap, Connection timed out after 20000 milliseconds [https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx]

Há como aumentar o timeout? Nesse caso posso entrar em contingência?

**Comment by robmachado** [comment]
Qual é o SO que vocês estão usando ? Qual a SEFAZ ? Qual a versão do PHP ? 
Quanto a aumentar o timeout sim dá para aumentar diretamente na classe SOAP
Ex. 
```
$tools = new Tools($config, $certificate);
$tools->soap->timeout(40); //tempo para timeout em segundos
```
Quanto a pergunta se pode entrar em contingência quando recebe o timeout ou falha no webserver ?
Resposta: Se estiver usando o modelo 55 (NFe) a resposta é NÃO ... não pode passar para contingência a não ser que a mesma seja autorizada pela SEFAZ autorizadora.

**Comment by brunonrosa** [comment]
Estou com o mesmo problema, preciso implementar a emissão em contingência. Período de Natal as APIs ficam congestionadas e mesmo alterado o timeout o erro ocorre. Por exemplo: Estou imaginando em alterar o timeout para 10 segundos apenas (como o caixa de supermercado), em caso de falha eu ativo a contingência. Para isso vou colocar um try/catch no método $tools->sefazEnviaLote, se falhar eu ativo a contingência dentro do catch e depois? Chamo a emissão da Danfce? Quando for enviar por definitivo o que eu devo chamar para emitir uma nota previamente emitida em contingência?

**Comment by robmachado** [comment]
Uma coisa é NFe (modelo 55) e outra muto diferente sob o aspecto da Contingência é a NFCe (modelo 65).
São regras e critérios totalmente diferentes ! E portanto requerem tratamentos muito diferentes.

**Comment by Jack184** [comment]
Acredito que foi instabilidade no SEFAZ. Não tive mais esse problema. Obrigado pela atenção!
