### ISSUE TITLE
Falha na autorização

### ISSUE THREAD

**Issue by Jack184** [nfephp-org/sped-nfe#589]
Bom dia. Estou recebendo este erro ao tentar autorizar a nota recentemente: 

An error occurred while trying to communication via soap, Network file descriptor is not connected [https://nfe.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx]

Alguém sabe algo a respeito?

**Comment by lukBarros** [comment]
Estou a passar pelo mesmo amigo, realmente está instável no SEFAZ RS.

**Comment by fmertins** [comment]
Olá, acredito que não seria então um erro da API?
Gerou alguma exception da API?

**Comment by Jack184** [comment]
Acredito que foi instabilidade no SEFAZ, pois não teve mais erro. Fechando aqui.
