### ISSUE TITLE
v5.0 - Make remover "indPag" essa tag não mais existe no layout 4.0 da SEFAZ

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-nfe#59]
public function tagide(
        $cUF = '',
        $cNF = '',
        $natOp = '',
        **$indPag = '',**
        $mod = '',
        $serie = '',
        $nNF = '',
        $dhEmi = '',
        $dhSaiEnt = '',
        $tpNF = '',
        $idDest = '',
        $cMunFG = '',
        $tpImp = '',
        $tpEmis = '',
        $cDV = '',
        $tpAmb = '',
        $finNFe = '',
        $indFinal = '0',
        $indPres = '',
        $procEmi = '',
        $verProc = '',
        $dhCont = '',
        $xJust = ''
    )

**Comment by Clarck1** [comment]
$indPag voltou? não voltou? como está?

**Comment by robmachado** [comment]
SIm veja a Nota técnica Nota Técnica 2016.002 - v 1.51
Mas isso ainda não está no STABLE RELEASE, vai para lá amanhã
