### ISSUE TITLE
Problemas NFe Completa

### ISSUE THREAD

**Issue by gustavomanes** [nfephp-org/sped-nfe#591]
Eu utilizo a função sefazDistDFe para buscar as nfe geradas pelo certificado digital, porem só devolve a NFe resumida tem alguma opção para receber os produtos juntos ou realizar uma outra consulta para pegar os produtos?

**Comment by olavocneto** [comment]
https://github.com/nfephp-org/sped-nfe/blob/2cef3dbc5c629f39f8fd95059c46b1189920781c/docs/metodos/Download.md

**Comment by gustavomanes** [comment]
Obrigado Olavo, mas isto já consegui, fazer retornar os dados da nota, o que preciso é da nota completa com os dados dos produtos que estão na nota.

Os dados retornados são:

"@attributes" => array:1 [
    "versao" => "1.01"
  ]
  "chNFe" => "33181028163164000159550010000005001292498556"
  "CNPJ" => "28163164000159"
  "xNome" => "77VENDAS DE PRODUTOS ELETRONICOS EIRELI-ME"
  "IE" => "87397335"
  "dhEmi" => "2018-10-02T00:00:00-03:00"
  "tpNF" => "1"
  "vNF" => "215.54"
  "digVal" => "wnpK+4UICtr1FbK5qlhCUyFWGvg="
  "dhRecbto" => "2018-10-02T17:34:30-03:00"
  "nProt" => "333180138256441"
  "cSitNFe" => "1"

Se não tiver uma função direta para isso, teria alguma função que conseguiria consulta pela chave os produtos da NFe

Obrigado

**Comment by robmachado** [comment]
Os resumos necessitam ser MANIFESTADOS pelo menos com a "ciência da operação" para serem liberadas as NFe completas, em uma busca posterior. Leia a documentação (nossa e da SEFAZ)

**Comment by gustavomanes** [comment]
Entendi então posso usar essa função sefazManifesta para realizar a manifestação e depois realizar a consulta novamente?

Obrigado

**Comment by robmachado** [comment]
Exato; mas LEMBRE-SE que essas coisas "NÃO SÃO instantâneas" ou seja demora um tempo entre a manifestação e a liberação do documento completo !

**Comment by gustavomanes** [comment]
Entendi obrigado pelas informações, sem querer abusar mas se puderem me dar só mais uma ajuda, essa manifestação pode implicar em alguma coisa para o cliente (dono do certificado), 

Obrigado

**Comment by robmachado** [comment]
Prezado Colega !! é muito chato ficar explicando coisas que estão na documentação !!
Não a "ciencia da operação" não implica em nenhum risco nem para o emitente nem para o recipiente.

**Comment by gustavomanes** [comment]
Rob obrigado pela ajuda, ja clareou minhas ideias, não encontrei esta informação na documentação.

Obrigado

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/Manifesta.md
http://www.nfe.fazenda.gov.br/portal/perguntasFrequentes.aspx?tipoConteudo=yjOJMwFOkA0=
Nota Técnica 2012.002
Nota Técnica 2013.001
