### ISSUE TITLE
NFC-e Cest possibilidade de setar valores zerado

### ISSUE THREAD

**Issue by schneiderbruno** [nfephp-org/sped-nfe#597]
Olá,

temos um sistema em java onde geramos NFC-e para empresas Simples Nacional.
Para situação tributária 102 está ok pois não necessita de CEST.

Porém para situação tributária 500, é obrigatório o campo CEST.
No sistema em java simplesmente setamos o CEST como "000000". O sefaz RS aceita de boa.

Utilizando essa biblioteca não conseguimos inserir a tag cest 

$std->CEST = "0000000";
...
$this->nfe->tagprod($std);

Não vai no XML da nota fiscal o campo cest.

Olhamos a documentação e vimos que existe a possibilidade de inserir através da função tagCEST.
Só que daí o sefaz obriga a inserir o CNPJ do fabricante. Ou seja, teríamos que mudar o sistema
para que cada produto com situação tributária 500 ter que setar o cnpj do fabricante.

Sugerimos que o na função "tagprod" aceitem o campo CEST.
Isso evitaria bastante trabalho visto que é possível simplesmente setar esse campo como zero.

Caso não seja possível, é viável simplesmente no campo cnpj do fabricante setar o cnpj do emitente? NEsse caso seria como se o emitente fizesse o produto?

Bom,
desde já obrigado.

**Comment by robmachado** [comment]
Não sei da onde você tirou que na função *tagCEST()* é OBRIGATÓRIO passar o cnpj ou qualquer outra coisa.
Pois **NÃO É**.
Você pode passar o CEST e apenas ele, nada mais !! 
Não passe ou nulifique os outros campos.

**Comment by schneiderbruno** [comment]
Ta bem, 
muito obrigado pelo retorno.
E também aproveito para parabenizar vc pela iniciativa, a lib mantida por vc é muito show... abstrai toda complexidade inerente. 
Enfim, obrigado por compartilhar e ajudar.
