### ISSUE TITLE
Melhorias contingência da Tools?

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#600]
https://github.com/nfephp-org/sped-nfe/blob/58fdc6163e34950be474ed6274de12573f0fac86/src/Common/Tools.php#L194

Boa tarde pessoal, em especial mestre @robmachado 
Estava revisando a associação que a Tools tem com a classe Contingency, conforme esta linha acima, no construtor da Tools, sempre instancia uma contingência vazia... **Não seria interessante podermos passar um objeto Contingency no construtor da Tools?** Exemplo, quero instanciar uma Tools já em contingência...

E olhando na documentação da contingência, hoje temos os exemplos na [seção USAGE](https://github.com/nfephp-org/sped-nfe/blob/master/docs/Contingency.md#usage), ok, mas acho que não está claro que após instanciar a contingencia precisa atribui-la à propriedade $contingency da Tools... O que acham?

Por fim, a prop $contingency da Tools acho que não deveria mais ser pública, para não poder ser alterada diretamente, então mudariamos ela para privada/protegida e criamos um método setContingency() que só aceita objeto da classe, penso que fica mais seguro...?

Abraços, valeu!

**Comment by robmachado** [comment]
Vamos lá:
1 - não vejo problema em PERMITIR passar a classe Contingency() no construtor (opcionalmente), se não for passada será criada uma instancia vazia da classe, ou seja operação normal.
2 - sim concordo que é melhor deixar essa prop como protegida e não permitir a alteração após o carregamento da classe tools, porém isso acarretaria uma QUEBRA na funcionalidade.

Mas como essa é uma alteração que QUEBRA uma funcionalidade deverá haver um incremento de versão, saindo de v5.0 para v5.1 por exemplo, e existem alguns PASSOS para fazer isso. 
- subir o ultimo release da versão 5.0
- criar uma branch para 5.0 
- fazer o PR para com as alterações em master
- alterar a documentação (indicando como funcionaria cada versão)
- subir o release para v5.1.1

**Comment by robmachado** [comment]
Então minha sugestão por ora é incluir a classe Contingency() no construtor  e apenas isso. 
Existem muitas outras melhorias que podemos fazer em uma nova branch v5.1, e assim que estiverem prontas e testadas passamos para master. É o que sempre foi feito.

**Comment by robmachado** [comment]
Já subi esses ajustes, falta documentar apenas (está em master apenas) mas vou subir um release.
