### ISSUE TITLE
Erro serviço não disponível para UF

### ISSUE THREAD

**Issue by robertowiest** [nfephp-org/sped-nfe#617]
Olá, estou com o seguinte erro ao tentar emitir uma NF para o estado de GO 

> Erro na emissão: Assina: Nenhum servico encontrado para UF [GO], modelo [65]

Alguma sugestão de como posso resolver esse problema?

**Comment by robmachado** [comment]
Esse retorno ocorre quando exatamente ??
Desconheço essa MENSAGEM !! a API foi modificada por vocês ??

**Comment by robertowiest** [comment]
Seria as linhas 493-496 do arquivo https://github.com/nfephp-org/sped-nfe/blob/master/src/Common/Tools.php, porém antes dela adicionamos isso

`if ($stdServ === false) {
            throw new \RuntimeException("Nenhum servico encontrado para UF [$sigla], modelo [$this->modelo]");
        }`

**Comment by robertowiest** [comment]
Eu retirei essa linha que adicionamos e retornei o estado original. Porém acontece o seguinte erro 

> Erro na emissão: Assina: Servico [NfeConsultaQR] indisponivel UF [GO] ou modelo [65]

**Comment by robertowiest** [comment]
Estou tentando imprimir uma NFce

**Comment by robmachado** [comment]
Impressão é com a API [sped-da](https://github.com/nfephp-org/sped-da) e não esta API
o sped-da irá gerar um PDF com base no XML pode usar este exemplo como referencia 
https://github.com/nfephp-org/sped-da/blob/master/examples/testaDanfce.php

**Comment by robertowiest** [comment]
Esta certo. Estou tentando entender o código dessa sua API, para então partir para o próximo passo. Antes, me tire uma dúvida. Ao chamar a função get, passando como parâmetro a sigla GO, da classe 

> https://github.com/nfephp-org/sped-nfe/blob/master/src/Common/Webservices.php

O que essa função irá retornar? Pelo pouco que entendo irá retornar null, não?

**Comment by robmachado** [comment]
Não irá retornar nulo não !!

GO existe como autorizador para o modelo 65, logo, serão retornados os dados contidos em https://github.com/nfephp-org/sped-nfe/blob/master/storage/wsnfe_4.00_mod65.xml
em um stdClass

**Comment by robertowiest** [comment]
Pois é....mas está me retornando nulo. Alguma forma de debugar? Estou tentando die ou print_r e não estou conseguindo imprimir o valor das variáveis...

**Comment by robertowiest** [comment]
Encontrei meu erro. Uma sugestão de alteração de código. No seu arquivo 

> https://github.com/nfephp-org/sped-nfe/blob/master/src/Common/Tools.php

Sua função 

> getXmlUrlPath

Nela existe um

`$file = str_replace('55', '65', $file);`

Porém se o caminho do arquivo tiver um número 55, por exemplo 15583363000174/api-nfe/storage/wsnfe_4.00_mod65.xml essa função irá alterar para 16583363000174/api-nfe/storage/wsnfe_4.00_mod65.xml e o sistema ira dar um erro que não encontra o serviço. Claro isso foi no meu caso. Mas fica uma sugestão de alteração.

**Comment by robmachado** [comment]
Ai é que está !

O pacote foi feito para o uso do COMPOSER e todos os pacotes do composer
ficam na pasta VOLATIL chamada VENDOR e não em uma pasta com outra
denominação.

Roberto

**Comment by robmachado** [comment]
Função ajustada em master!

Roberto
