### ISSUE TITLE
Web Services NFCe para MG

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-nfe#620]
Bom dia!

O estado de MG já liberou os webservices e datas para implantação da NFCe. Pode incluir no wsnfe_4.00_mod65.xml?

http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/

Alterei somente os links, não alterei method, operation e version. Como isto é definido?

  <UF>
    <sigla>MG</sigla>
    <homologacao>
        <NfeAutorizacao method="nfeAutorizacaoLote" operation="NFeAutorizacao4" version="4.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeAutorizacao4</NfeAutorizacao>
        <NfeRetAutorizacao method="nfeRetAutorizacaoLote" operation="NFeRetAutorizacao4" version="4.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeRetAutorizacao4</NfeRetAutorizacao>
        <NfeInutilizacao method="nfeInutilizacaoNF" operation="NFeInutilizacao4" version="4.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeInutilizacao4</NfeInutilizacao>
        <NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsulta4" version="4.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeConsultaProtocolo4</NfeConsultaProtocolo>
        <NfeStatusServico method="nfeStatusServicoNF" operation="NFeStatusServico4" version="4.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeStatusServico4</NfeStatusServico>
        <RecepcaoEvento method="nfeRecepcaoEvento" operation="NFeRecepcaoEvento" version="1.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4</RecepcaoEvento>
        <NfeConsultaQR method="QR-CODE" operation="NfeConsultaQR" version="200">https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml</NfeConsultaQR>
    </homologacao>
    <producao>
        <NfeAutorizacao method="nfeAutorizacaoLote" operation="NFeAutorizacao4" version="4.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeAutorizacao4</NfeAutorizacao>
        <NfeRetAutorizacao method="nfeRetAutorizacaoLote" operation="NFeRetAutorizacao4" version="4.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeRetAutorizacao4</NfeRetAutorizacao>
        <NfeInutilizacao method="nfeInutilizacaoNF" operation="NFeInutilizacao4" version="4.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeInutilizacao4</NfeInutilizacao>
        <NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsulta4" version="4.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeConsultaProtocolo4</NfeConsultaProtocolo>
        <NfeStatusServico method="nfeStatusServicoNF" operation="NFeStatusServico4" version="4.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeStatusServico4</NfeStatusServico>
        <RecepcaoEvento method="nfeRecepcaoEvento" operation="NFeRecepcaoEvento" version="1.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4</RecepcaoEvento>
        <NfeConsultaQR method="QR-CODE" operation="NfeConsultaQR" version="200">https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml</NfeConsultaQR>
    </producao>
  </UF>

Obrigado!

**Comment by robmachado** [comment]
Incluso MG como emitente de NFCe
