### ISSUE TITLE
Ajustar a OBRIGATORIEDADE dos novos campos NT 2018.005

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-nfe#625]
Alguns campos inclusos nas Nota Técnica 2018.005 - v1.00 de 02/01/2019 e Nota Técnica 2018.005 - v1.10 de 12/02/2019, passarão a ser **exigidos a partir de 24/04/2019**, então deverá ser ajustada essa obrigatoriedade (ou não).
Alguns campos estão em um BLOCO portanto caso existam deverão TODAS serem exigíveis (conforme indicado na NT).

NOTA: alguns campos poderão permanecer como "Não Obrigatórios" pois serão exigíveis a critério da Sefaz autorizadora, sem uma definição unica para todos. Isso irá implicar na possibilidade de rejeição **sem que aja condição da API prever esse fato.**

NOTA: conferir alteração dos XSDs, e atualiza-los
NOTA: ajustar o exemplo de montagem do XML com esses novos campos

**Comment by fmertins** [comment]
Bom dia, revisando a NT 2018.005 versao 1.10 página 4, a data para o ambiente de producao é **29/04** correto?

**Comment by robmachado** [comment]
Exato ! entra em produção em 29/04, porém a EXIGIBILIDADE iré depender do desejo de cada SEFAZ autorizador !! Ai, mora o problema QUEM irá exigir essas informação e quem não irá ??

**Comment by robmachado** [comment]
Até lá ainda poderão haver outras alterações, como de costume !! Eles não se cansam de complicar as coisas.

**Comment by fmertins** [comment]
Éééé meu estimado mestre, pelo que estou entendendo vamos ter o cenário "o campo é obrigatório conforme layout do XML MAAAAS dependendo da SEFAZ ela não exige que seja..."
#tenso #medo :-(

**Comment by robmachado** [comment]
heheheh já estou acostumado !! é que você não viu ainda o eSocial e as outras tranqueiras SPED

**Comment by robmachado** [comment]
Alterado
