### ISSUE TITLE
Motivo: 878 - Rejeição: Endereço do site da UF da Consulta por chave de acesso diverge do previsto

### ISSUE THREAD

**Issue by markintux** [nfephp-org/sped-nfe#628]
* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: PL_009_V4

## Comportamento esperado
- Enviar o lote normalmente

## Comportamento Atual
Apresenta o erro: 878 - Rejeição: Endereço do site da UF da Consulta por chave de acesso diverge do previsto

## Passos para reproduzir
1 - Sigo normalmente sem erro até a parte de Enviar o Lote
2 - Seto $tools->model(65);
3 - O lote é enviado
4 - Quando consultado o recibo (resposta do lote), através da variável protocolo, vem a mensagem do título deste nota.
5 - Código:

try {
    $protocolo = $tools->sefazConsultaRecibo($recibo);
} catch (\Exception $e) {
    //aqui você trata possíveis exceptions da consulta
    exit($e->getMessage());
}
echo $protocolo;

Saída: Motivo: 878 - Rejeição: Endereço do site da UF da Consulta por chave de acesso diverge do previsto

## Contexto (Ambiente)
Estou tentando enviar uma NFC-e em ambiente de homologação no estado de SP.

**Comment by robmachado** [comment]
Faltava o https:// no inicio desse URL, já subi a correção !

**Comment by markintux** [comment]
Show Roberto! :) Muito obrigado pela atenção. Deu certo aqui.
Grande abraço!

**Comment by jefersonalmeida** [comment]
@robmachado, peço gentileza atualizar no arquivo nfephp-org/sped-nfe/storage/uri_consulta_nfce.json ambiente 2 de homologação a url de MT.

de : "MT": "homologacao.sefaz.mt.gov.br\/nfce\/consultanfce",
para: "MT": "http:\/\/homologacao.sefaz.mt.gov.br\/nfce\/consultanfce",

![image](https://user-images.githubusercontent.com/1840969/62309169-edb7a980-b454-11e9-8777-7c4b8d05f56b.png)

Desde já agradeço a atenção.
Abraços!
