### ISSUE TITLE
[BUG] Erro ao normalizar o carácter ampersand (&)

### ISSUE THREAD

**Issue by luishgp** [nfephp-org/sped-nfe#633]
## Descrição detalhada

Ao tentar enviar ao componente o carácter **&**, é chamado duas vezes o método _\NFePHP\Common\Strings::replaceUnacceptableCharacters()_, uma no método _equilizeParameters()_ e outra antes de adicionar o elemento ao **DOM**, fazendo com que o resultado seja _\&amp;amp;_, pois na primeira chamada é substituído o **&** por \&amp; e na segunda chamada é feito novamente o replace, resultando na string descrita acima. 

## Exemplo

```php
$std = new \stdClass();
$std->xNome = "Santos & Tessaro Ltda";
$std->xFant = "Pureza Gourmet";
$std->IE = "283523050";
$std->IEST = NULL;
$std->IM = NULL;
$std->CNAE = NULL;
$std->CRT = "1";
$std->CNPJ = "10733362000145"

$nfe->tagemit($std);
```

## Comportamento esperado
```xml
<emit>
    <CNPJ>10733362000145</CNPJ>
    <xNome>Santos &amp; Tessaro Ltda</xNome>
    <xFant>Pureza Gourmet</xFant>
    <IE>283523050</IE>
    <CRT>1</CRT>
</emit>
```

## Comportamento Atual

```xml
<emit>
    <CNPJ>10733362000145</CNPJ>
    <xNome>Santos &amp;amp; Tessaro Ltda</xNome>
    <xFant>Pureza Gourmet</xFant>
    <IE>283523050</IE>
    <CRT>1</CRT>
</emit>
```
## Solução possível

- Manter a chamada do método _equilizeParameters()_  visto que é utilizado em todas os métodos que adicionam tags ao XML e remover a chamada direta do método _\NFePHP\Common\Strings::replaceUnacceptableCharacters()_ ao adicionar os elementos ao **DOM**;
- Remover a chamada do _\NFePHP\Common\Strings::replaceUnacceptableCharacters()_ em _NFePHP\NFe\Make_ _(Line 7408)_;

## Passos para reproduzir

Verificar na classe _NFePHP\NFe\Make_ os métodos de construção das tags do XML, neles são chamados o método _equilizeParameters()_ e também o método _replaceUnacceptableCharacters()_, realizando o replace duas vezes.

**Comment by robmachado** [comment]
Muito obrigado ! @luishgp 
Erro (causado por mim mesmo) corrigido ! e correção já disponível para atualização !
