### ISSUE TITLE
Contingência

### ISSUE THREAD

**Issue by jgustavo99** [nfephp-org/sped-nfe#637]
Opa. Estou com uma dúvida relacionado ao NFC-E RS.

Quando é retornado alguma exception no processo de emissão, eu já emito em contingência offline. Porém eu devo também verificar o tempo para emitir em contingência.

Qual o tempo limite devo colocar para quando se esgotar eu já emitir em contingência?

Uma outra pergunta seria se existe algum tempo recomendável no instante que eu chaveie meu sistema para emissão em contingência e retome. Por exemplo eu poderia emitir 5 notas em contingência offline e após tentar emitir uma normal para ver se voltou Sefaz, ou a cada 5 mim verificar. Não sei como o pessoal costuma a fazer.

**Comment by fmertins** [comment]
Bom dia por favor veja este tipo de dúvida no grupo do Google pois é sobre como usar a API, etc.
Outra dica, pode escrever para nfe@sefaz.rs.gov.br que a SEFAZ RS presta suporte, geralmente funciona bem e respondem no mesmo dia.

**Comment by jgustavo99** [comment]
Beleza! Qual seria grupo do Google?

**Comment by fmertins** [comment]
Temos o link no README.md na home aqui do projeto... :-)
http://groups.google.com/group/nfephp
Abraços!

**Comment by robmachado** [comment]
@jgustavo99 Em primeiro lugar ESTUDE o manual da SEFAZ  e as Notas Técnicas sobre Contingência.

E preste muito bem a atenção a QUAIS tipos de contingência são aplicáveis a NFCe (mode 65) e quais não são. Inclusive as regras para estados como SP e CE onde é obrigatório do uso de SAT@ECF

NFSe normalmente tem somente emissão NORMAL e OFFLINE qualquer outra possibilidade e mais complexa.

Para tirar esse tipo de duvida use o forum https://groups.google.com/forum/#!forum/nfephp

**Comment by jgustavo99** [comment]
Valeu!

Só uma questão... Na doc não achei, mas no caso de notas em contingência falharem o envio pelo fato do sefaz estar fora do ar (NFC-e Ctg offline), eu posso tentar enviar denovo com a mesma numeração.

O mesmo vale para notas em contingência offline que foram reprovadas, posso ajustar o XML e enviar dnv com a mesma numeração e série.
