### ISSUE TITLE
0 Os documentos se referem a diferentes objetos. Os digest são diferentes. !

### ISSUE THREAD

**Issue by myckol** [nfephp-org/sped-nfe#642]
* **Estou enviando um ...**
  - [x ] bug
 
* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.00

Boa noite!
É a primeira vez q posto algo aqui, portanto, peço desculpas caso cometa algum erro.

O problema tem sido q, ao emitir uma nota fiscal modelo 55, sendo o emissor do DF, não tem problema algum mas, quando tento gerar com emissor GO (goiânia mais precisamente) me retorna o erro "0 Os documentos se referem a diferentes objetos. Os digest são diferentes. !". Percebi q a tag DigestValue do xml protocolado diverge do xml gerado, porém, não consegui ainda resolver o problema. Alguma idéia ou solução?

obrigado.

**Comment by robmachado** [comment]
Isso não é um BUG é um erro no seu sistema. 
Use o forum para pedir ajuda, mas debug sua aplicação pois o erro está nela !!
