### ISSUE TITLE
Cancelamento por Substituição

### ISSUE THREAD

**Issue by jgustavo99** [nfephp-org/sped-nfe#644]
Olá, Boa noite.

Estou enviando por aqui, pois não obtive ainda sucesso no grupo...

A minha pergunta é...

No cancelamento por substituição na própria NT existe um exemplo que cita aonde temos o NFC-e 1, e que se por algum motivo não retornar resposta, eu emito a NFC-e 2 e usando esse evento eu cancelo a NFC-e 1 referenciando a NFC-e 2.

Até aqui tudo Ok. Mas a NUMERAÇÃO delas tem que ser iguais? Pode ter PULO de numeração? Pois pelo que eu entendi não pode ocorrer. Por exemplo, se eu emito a Nota número 10 e a mesma não obtenho resposta, devo emitir NOVAMENTE a Nota número 10 como tipo de emissão em contingência ou pulo para a Nota número 11?

Desculpe-me mais uma vez por postar aqui.

Obrigado desde já.

**Comment by jgustavo99** [comment]
Se a numeração deve ser igual, então a documentação da contingência em timeout deve ser corrigida, aonde não teremos mais pulo de numeração e não devemos mais inutilizar nota. Se ela não foi autorizada, deve enviar e depois cancelar por substituição.

**Comment by robmachado** [comment]
As NUMERAÇÕES NUNCA serão IGUAIS, pois cada NFCe deve ter seu numero UNICO independentemente se for NORMAL ou OFFLINE.

**Comment by jgustavo99** [comment]
Eu enviei um e-mail para o sefaz RS e eles me informaram que devem ser iguais. Por isso me confundi...

**Comment by jgustavo99** [comment]
Veja o que me responderam - Sefaz RS:

"Vamos considerar que a empresa esteja emitindo a NFC-e de número 10. Se a empresa transmite a NFC-e para o sistema normal da SEFAZ, e por algum motivo não obteve uma resposta, então a empresa pode simplesmente emitir essa NFC-e de número 10 em contingência off-line.

 

Depois, a empresa verifica se a NFC-e de número 10 havia sido autorizada no sistema normal.

 

·   Se a NFC-e de número 10 foi autorizada no sistema normal, então a empresa tem 2 notas emitidas em duplicidade. Nesse caso, a empresa utiliza o evento de Cancelamento por Substituição, descrito na NT 2018.004, para cancelar a 1ª NFC-e. Fica valendo a segunda nota, que foi emitida em contingência.

 

·   Por outro lado, se a NFC-e de número 10 não foi autorizada no sistema normal, então tudo está certo, e não há nada que precise ser feito. Novamente, fica valendo a segunda nota, que foi emitida em contingência."

**Comment by jgustavo99** [comment]
Pelo que eu entendi entrando em contato com a Sefaz RS:

- Quando ocorrer contingência, deve-se utilizar uma série específica para a mesma: 890 a 989
- Com isso, cada nota em contingência deve seguir a numeração e essa série específica.
- Quando houver alguma nota a ser substituída utilizar o cancelamento por substituição.

Por exemplo, se foi tentando emitir a Nota 10 e a mesma retornou algum erro.

Se foi TIMEOUT, deve-se gerar a nota em contingência utilizando por exemplo a série 890 e quando retomar Sefaz cancelar a nota 10 série 1 referenciando a nota X série 890 (substituida).

Se foi SEFAZ FORA DO AR, deve-se apenas emitir a nota em contingência utilizando a série por exemplo 890.

Para contingências offline (SEM INTERNET) pode-se emitir diretamente a nota em contingência utilizando a série específica escolhida.

O material que eu verifiquei foi:

- https://www.confaz.fazenda.gov.br/legislacao/ajustes/2018/AJ0013_18
- NT 2018.004 v 1.00

Os emissores de NFC-e tem até 29 de Abril (se não me engano) para ajustar esse processo de contingência.

**Comment by jgustavo99** [comment]
O Sefaz irá lançar uma NT com essas alterações que comentei.
