### ISSUE TITLE
Nova versão dos schemas XSD de 15/03/2019

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#646]
Bom dia, conforme Portal Nacional da NF-e, Governo publicou nova versão dos schemas "PL 009 V4" dia 15/03/2019, pois teve nova versão da respectiva Nota Técnica 2018/005.

http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=

Basta atualizarmos os arquivos e fazer um pull request?

**Comment by robmachado** [comment]
Deixe  que eu baixo a atualizo, as alterações podem ter o inicio de validade mais a frente temos que conferir para não causar problemas. Essa NT entra em produção apenas em 29/04/2019

**Comment by robmachado** [comment]
incluso
