### ISSUE TITLE
Alterar Operation NFCe em MG - NFeConsultaProtocolo4

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-nfe#649]
Boa tarde!

Segue uma alteração no C:\HAFIDW\RELEASE\PHP\sped-nfe\vendor\nfephp-org\sped-nfe\storage\wsnfe_4.00_mod65.xml

Adicionar a palavra Protocolo no operation de "NFeConsulta4" para "NFeConsultaProtocolo4"

**Comment by rabraga** [comment]
Aproveitando,

Mais uma alteração para NFeRecepcaoEvento4

De:
       <RecepcaoEvento method="nfeRecepcaoEvento" operation="NFeRecepcaoEvento" version="1.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4</RecepcaoEvento>
       <RecepcaoEvento method="nfeRecepcaoEvento" operation="NFeRecepcaoEvento" version="1.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4</RecepcaoEvento>

Para:
       <RecepcaoEvento method="nfeRecepcaoEvento" operation="NFeRecepcaoEvento4" version="1.00">https://hnfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4</RecepcaoEvento>
       <RecepcaoEvento method="nfeRecepcaoEvento" operation="NFeRecepcaoEvento4" version="1.00">https://nfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4</RecepcaoEvento>

**Comment by robmachado** [comment]
Alterado
