### ISSUE TITLE
Condicional no Tools para o Schemes

### ISSUE THREAD

**Issue by lukinhaspm** [nfephp-org/sped-nfe#655]
Boa tarde,

Estou utilizando os dois layouts da NFe 4.0 ao mesmo tempo no meu sistema, passando por parâmetros se quero a V4 ou V4.00v1.2, mas reparei que o método version da classe Tools.php muda a diretiva de config "schemes" sempre pegando os disponíveis.

Modifiquei isso para respeitar o que é passado no config e acho uma boa mudar no projeto, como não manjo do pull request, decidi abrir por aqui.

Não sei se eu deveria ter feito essa chamada de outra forma, mas segue

..\vendor\nfephp-org\sped-nfe\src\Common\Tools.php
Linha 290

De

`$this->config->schemes = $this->availableVersions[$version];`

Para

`        if(!$this->config->schemes){
            $this->config->schemes = $this->availableVersions[$version];
        }`

Obrigado

**Comment by robmachado** [comment]
Os layouts dos schemas PL_009_V4 e PL_009_V4_00_v1.20, existirão separadamente apenas durante o período de transição referente a NT 2018_005_v1.20, após esse período (quando entrar totalmente em produção em 07/05/2019) *poderá* ser revista a nomenclatura.
Mas de qualquer forma existirá apenas UM conjunto de schemas, visto que o anterior fica DEPRECATED.
Quanto a propriedade availableVersions, é um problema, pois nesse caso a SEFAZ fez muitas alterações nos XSD mas **não alterou a versão**, eu coloquei essas XSD em um bloco separado apenas para realizar os testes para garantir não QUEBRAR alguma coisa, caso os XSD exijam algo que não podemos fornecer na versão atual.

**Comment by lukinhaspm** [comment]
Sim, eu entendi isso, mas essa situação vai seguir acontecendo.
Eu vou fazer essa tratativa do meu lado, mas a diretiva schemes do config então não esta sendo usada?
Obrigado

**Comment by lukinhaspm** [comment]
Vou fechar a solicitação, valeu

**Comment by rabraga** [comment]
Hoje precisei atualizar os XSD do PL_009_V4. Aqui em MG já tive rejeição por causa do modBCST=6.

This XML is not valid. Element {http://www.portalfiscal.inf.br/nfe}modBCST: [facet enumeration] The value 6 is not an element of the set {0, 1, 2, 3, 4, 5}.Element {http://www.portalfiscal.inf.br/nfe}
