### ISSUE TITLE
Classe Protocol, quebrou?

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/sped-nfe#656]
Bom dia pessoal,

Atualizei a minha API via Composer, só não tenho mais anotada a versão original, mas era lá por meados de nov-18.

Então agora estou na última release da API e parece que quebrou a classe `NFePHP\NFe\Factories\Protocol` pois não existe mais.

Pergunta: no meu composer.json o require está assim:
`"nfephp-org/sped-nfe": "^5.0"`

Não deveríamos ter controlada a versão da API de outra forma, tipo uma major version, indicando incompatibilidade?

**Comment by robmachado** [comment]
Complements::class
 vide https://github.com/nfephp-org/sped-nfe/blob/master/docs/Complements.md

**Comment by fmertins** [comment]
Bom dia mestre! Perfeito obrigado, estou refatorando... Só fiquei em dúvida ainda, não deveríamos ter controlado a versão diferente quando excluímos a classe `Protocol`, para sinalizar no Composer a incompatibilidade?

**Comment by robmachado** [comment]
Isso foi falado e repetido a mais de um ano em muitas ocasiões

Roberto

**Comment by robmachado** [comment]
Só para esclarecer Fernando;
A classe Protocol::class na versão 5.0 era um ERRO pois era para ter sido removida muito antes. Pois tinha sido substituída pela Complements::class.  Mas acabou ficando e ficando o que causou o problema. Outros terão a mesma surpresa que você. Pois não tem acompanhado muito o forum e não tem olhado  a documentação que eu tenho escrito.
Abraço

**Comment by fmertins** [comment]
Opa, tranquilo Roberto obrigado! Realmente eu não tinha visto, e olha que geralmente passo o olho nos emails :-)

Aproveitando o caso para ver se entendo da forma certa, digamos que mais adiante quando tiver alguma alteração que gera incompatibilidade, a próxima versão será uma "major", no caso, 6.0.0 já que atualmente estamos na versão 5.0.x, seria isto?

**Comment by robmachado** [comment]
Exatamente isso. 
As classes PUBLICAS (principais), ou seja aquelas que todos usam como:
- Tools
- Make
- Complements
- Convert
- Standardize - esta classe esta em sub pasta mas é util para o uso comum
- Contingency - esta classe esta em sub pasta mas é de USO COMUM para setar a contingência

Caso sofram alguma alteração que quebre a compatibilidade serão alteradas somente em uma NOVA versão por exemplo 6.0.x (veja https://semver.org/lang/pt-BR/), logicamente a branch master deixa de ser da versão anterior e passa a ser dessa nova versão. Por isso não se deve usar a branche master em aplicações STABLE.  

Já outras classes de uso INTERNO a aplicação (classes auxiliares) em principio podem sofrer alterações que as QUEBREM desde que não quebrem as classes principais. Como por exemplo as classes que estão em subpastas, Então a recomendação é NUNCA use classes em subpastas a menos que indicado pelo AUTOR.

**Comment by robmachado** [comment]
Outra recomendação, sempre faça testes a cada composer update localmente, ou de preferencia em um servidor de desenvolvimento.
Num versionamento v5.0.81 como vX.Y.Z
- Z (81) - aqui são indicadas alterações como correções apenas (SEM QUEBRA)
- Y (0) - é incrementado quando da inclusão de novos recursos e/ou correções (SEM QUEBRA)
- X (5) - é incrementado quando existem alterações incompatíveis com a versão anterior COM QUEBRA

**Comment by robmachado** [comment]
Continuando, por exemplo em algum momento vou trazer essas duas classes Standarize::class e Contingency::class para a raiz do projeto, qunado eu fizer issso a classe vai mudar de versão para 6.0.x.
Outra condição é com referencia as correções quando o numero de correções chegar a 100, haverá um incremento de versão de por exemplo v5.0.99 para v5.1.0. Não quero que chegue a 3 dígitos !
