### ISSUE TITLE
Erro envio Nfe ( Idlote   nfemit )

### ISSUE THREAD

**Issue by LEONCYO** [nfephp-org/sped-nfe#660]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: HML

  - Versão do leiaute: 4.00

Gostaria de parabenizar pela iniciativa do nfe e tambem poder contribuir de alguma forma no projeto.

Não estou conseguindo postar no grupo: https://groups.google.com/forum/#!forum/nfephp... e por isso estou solicitando retorno no erro abaixo:

* Envio lote

* erro:  
ErrorException: Undefined variable: nfemit in file C:\laragon\www\nfe\app\Http\Controllers\Invoice\DeliveryBatchController.php on line 58
Stack trace:
  1. ErrorException-&gt;() C:\laragon\www\nfe\app\Http\Controllers\Invoice\DeliveryBatchController.php:58
  2. Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleError() C:\laragon\www\nfe\app\Http\Controllers\Invoice\DeliveryBatchController.php:58
  3. App\Http\Controllers\Invoice\DeliveryBatchController-&gt;index() C:\laragon\www\nfe\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
  4. call_user_func_array() C:\laragon\www\nfe\vendor

OBS.: Esta dando erro no nfemit no idlote conforme linha abaixo:
 $idLote = str_pad($nfemit->id, 15, '0', STR_PAD_LEFT);

**Comment by robmachado** [comment]
Colega isso é do SEU sistema e não da API !!!
