### ISSUE TITLE
NT 2018.005 uf que não possui obrigação do campo CSRT

### ISSUE THREAD

**Issue by maiconkamiya** [nfephp-org/sped-nfe#665]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:

Conforme a NT 2018.005, foi implementado "Informações do Responsável técnico"
        if (empty($std->CSRT)) {
            throw new RuntimeException('O CSRT é obrigatorio.');
        }
Porem em alguns UF, a Sefaz ainda não esta realizando o credenciamento do CSRT e por este motivo não esta sendo cobrando, somente os campos ZD02, ZD04, ZD05 E ZD06.

Já os campos ZD07, ZD08 e ZD09 dependem do CRST e por isso serão de implementação futura quando o Estado passar a fornecer o código para o Responsável Técnico.

**Comment by robmachado** [comment]
Se você atualizar verá que esses campos não são exigidos
