### ISSUE TITLE
Break line infcpl

### ISSUE THREAD

**Issue by thiagoreri** [nfephp-org/sped-nfe#673]
Ola pessoal estou utlizando o /n para quebra de linha ao gerar o DANFE e o mesmo não está quebrando a linha.

**Comment by robmachado** [comment]
Em primeiro lugar isso é coisa da DANFE (sped-da) e não deste pacote.
Portanto coloque sua duvida primeiro no FORUM, e use as ISSUES para indicar algum BUG, necessidade ou falha das classes.
