### ISSUE TITLE
NFe Produtor Rural (CPF) Cancelamento 

### ISSUE THREAD

**Issue by fabiomigliorini** [nfephp-org/sped-nfe#674]
* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

## Versão do leiaute
4.1

## Comportamento esperado
Realizar o cancelamento de uma NFe

## Comportamento Atual
Retorna Falha no Schema XML

## Solução possível
Na funcão sefazEvento do Tools.php, substituir linha 786 de
                $request .= "<CPF>$cnpj</CPF>";
para 
            $request .= "<CPF>$cpf</CPF>";
e adicionar na linha 774 o seguinte
        $cpf = $this->config->cpf;
Esse bug também está presente no método sefazEventoLote

## Passos para reproduzir
Tentar cancelar qualquer NFe emitida com CPF utilizando o WS da Sefaz de MT

**Comment by robmachado** [comment]
Bom primeiro, não existe a opção de colocar um CPF no config.json, apenas existe o campo 'cnpj' onde pode ser colocado o documento (cnpj/cpf) do emitente  !!
Segundo, a classe deve poder identificar pelo certificado usado na conexão, se for um com CNPJ a propriedade $this->typePerson deve ser igual a 'J' e se o certificado for um eCPF essa propriedade deverá conter 'F'

**Comment by fabiomigliorini** [comment]
Realmente, voltei o código do Tools.php para o que tem no repositório e alterei a configuração de acordo com o que você recomendou e funcionou conforme o esperado...

Sugiro colocar no Config.md essa explicação...
