### ISSUE TITLE
Erro na validação da tagCONFISST

### ISSUE THREAD

**Issue by marciotisouza** [nfephp-org/sped-nfe#681]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

Ubuntu 18.04 / PHP 7.2

  - Versão do leiaute: 4.00

## Comportamento esperado

Validar com Sucesso mesmo que não sejam informadas as tags qBCProd  e vAliqProd 

## Comportamento Atual

Ao gerar a tagCOFINSST a validação retorna : This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}qBCProd': This element is not expected. Expected is ( {http://www.portalfiscal.inf.br/nfe}vCOFINS ).

## Solução possível
        if( isset($std->qBCProd) ){
			$this->dom->addChild(
				$cofinsst,
				"qBCProd",
				$std->qBCProd,
				true,
				"[item $std->item] Quantidade Vendida"
			);
	}

## Passos para reproduzir

$std = new \stdClass();
$std->item = 1;
$std->vCOFINS = 0;
$std->vBC = 0;
$std->pCOFINS = 0;
$nfe->tagCOFINSST($std);

## Contexto (Ambiente)

Validar uma NFe

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
 Erro na validação

## Possível implementação

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Na verdade é um pouco mais complexo que isso:
1. caso qBCProd seja declarado (isset(qBCProd) == true) então devem ser passados também vAliqProd e vCOFINS (esses três campos passam a ser obrigatórios
2. caso não seja declarado (isset(qBCProd) == false) então devem ser passados, vBC, pCOFINS e vCOFINS

> NOTA: se for passado ZERO, isso será considerado, apenas o NULL ou a não declaração impedem a inserção do campo. Então **não declare**  = ZERO que não que passar dados no campo.

Estou providenciando essa correção no comportamento da TAG.

> NOTA: pelo manual não dá para ver isso claramente mas pelo XSD fica claro que existe essa condição (choice).

**Comment by robmachado** [comment]
BUG FIX !!! verifique por favor !!

**Comment by marciotisouza** [comment]
Boa tarde, vou testar !

**Comment by marciotisouza** [comment]
Funcionou, grato ....
