### ISSUE TITLE
Estorno NFe

### ISSUE THREAD

**Issue by mauricio-jc** [nfephp-org/sped-nfe#685]
Bom dia pessoal.

Estou usando a biblioteca para emissão de Notas Fiscais no meu sistema e está funcionando muito bem, biblioteca muito boa. Mas me surgiu uma dúvida.

Tem a opção de cancelamento da Nota. Porém gostaria de saber se existe também a opção de Estornar a nota?
Pois segundo meu contador, após 24 horas da emissão da nota, não pode mais cancelar a nota emitida e sim fazer um estorno.

Podem me ajudar?

Att,
Maurício.

**Comment by rabraga** [comment]
Bom dia!

O estorno deve ser uma nota de entrada, não?

É mais uma questão fiscal/operacional do que técnica relacionada com a sped-nfe.

Para dúvidas crie um post no grupo, e não uma issue.

------ Mensagem original ------
De: "Mauricio Citadini Biléssimo" <notifications@github.com<mailto:notifications@github.com>>
Para: "nfephp-org/sped-nfe" <sped-nfe@noreply.github.com<mailto:sped-nfe@noreply.github.com>>
Cc: "Subscribed" <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Enviado(s): 22/06/2019 10:24:22
Assunto: [nfephp-org/sped-nfe] Estorno NFe (#685)


Bom dia pessoal.

Estou usando a biblioteca para emissão de Notas Fiscais no meu sistema e está funcionando muito bem, biblioteca muito boa. Mas me surgiu uma dúvida.

Tem a opção de cancelamento da Nota. Porém gostaria de saber se existe também a opção de Estornar a nota?
Pois segundo meu contador, após 24 horas da emissão da nota, não pode mais cancelar a nota emitida e sim fazer um estorno.

Podem me ajudar?

Att,
Maurício.

**Comment by brasvidal** [comment]
De experiência no Paraná, por aqui é 24 horas para cancelar, até 7 dias para cancelar com risco de tomar multa, acima disso só com nota de devolução do da pessoa pra quem foi emitida a nota.

**Comment by rogeriolins** [comment]
Exatamente, 

No Paraná é assim...

Enviado do meu iPhone

Em 5 de jul de 2019, à(s) 13:41, Marcos Vidal <notifications@github.com> escreveu:
