### ISSUE TITLE
Qual classe usar para NFe

### ISSUE THREAD

**Issue by lukBarros** [nfephp-org/sped-nfe#69]
Usar esse repositório ou usar o speed-nfe? Mas no speed-nf fala que não deve usar em produção.

**Comment by robmachado** [comment]
Por ora use o repositório do nfephp ou se tiver bons conhecimentos use este mesmo, mas lembre-se que tudo isso ira sofrer alterações com a próxima versão.
Para esse tipo de duvida é melhor usar o forum e não o GITHUB
