### ISSUE TITLE
apos atualizar o sistema parou de gerar o xml para CPF

### ISSUE THREAD

**Issue by uilhianet** [nfephp-org/sped-nfe#693]
Sempre retorna nulo tanto o XML quanto a chave

**Comment by robmachado** [comment]
Não posso avaliar nada com essas informações !

**Comment by uilhianet** [comment]
antes de atualizar a api ela funcionava normalmente para gerar o xml do produtor rural, apos te feito o update, apenas está gerando xml para CNPJ e não funcionou mais para CPF

**Comment by SilverioMiranda** [comment]
Mano se você não postar o exemplo de como você usa ela, incluindo qual a versão anterior, a versão atual, e o exemplo do código nem com bola de cristal a gente vai ter como saber o motivo de não funcionar mais

**Comment by uilhianet** [comment]
tipo eu não consigo dar muito explicação não, pois não sei qual é a causa do problema, a unica coisa que sei é que apos rodar o comanda para atualizar e ao tentar gerar um xml de uma nota com CPF não gera nada, o getXml() retorna null, já com CNPJ funciona perfeitamente, dai tive que voltar para versão que eu estava que a mesma funciona perfeitamente.

**Comment by joaoroyosilva** [comment]
Manda o trecho de código que vc gera a tag de emitente

**Comment by uilhianet** [comment]
public static function getEmitente($empresa, $address)
    {
        $std = new \stdClass();
        $std->xNome = $empresa->razao;
        $std->xFant = $address->nome_fantazia ?? $empresa->razao;
        $std->IE = $empresa->ei;
        $std->IEST = $empresa->eis;
        $std->IM = $empresa->im;
        // $std->CNAE = $empresa->cnae;
        $std->CRT = $empresa->regime;
        if ($empresa->tipo == 'F') {
            $std->CPF = str_replace('/', '', str_replace('-', '', str_replace('.', '', $empresa->cpf_cnpj)));
        } else {
            $std->CNPJ = str_replace('/', '', str_replace('-', '', str_replace('.', '', $empresa->cpf_cnpj)));
        }
        //indicar apenas um CNPJ ou CPF
        return $std;
    }

**Comment by lukinhaspm** [comment]
@uilhianet vc já tentou setar um CPF na mão, sem pegar do banco?
vc já tentou debugar e ver aonde para dentro do script? - com o debugger, ou mesmo colocando uns breaks no cod para ver se chegam?
Não vejo como ajudar assim
