### ISSUE TITLE
302: Uso Denegado: Irregularidade fiscal do destinatário

### ISSUE THREAD

**Issue by ivanmestre** [nfephp-org/sped-nfe#694]
* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte

  - Versão do leiaute: 4.00

## Comportamento Atual
Estou tentando gerar NFe em ambiente de homologação para destinatarios localizados no estado de SP. Até 1 ou 2 semanas atrás tudo estava funcionando corretamente. Na semana passada comecei a receber a seguinte mensagem da SEFAZ: 302: "Uso Denegado: Irregularidade fiscal do destinatário".  

Eu não sou o único que acontece com isso. Eu encontrei esta postagem nos Grupos do Google:
https://groups.google.com/d/msg/nfephp/Ydt0pYlFWwc/UKfZgVpMAwAJ

## Solução possível
Acho que tem a ver com a Nota Técnica 2019.001 com data de implementação do teste de 01/07/2019:
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=RD1XRVxKLtI=

**Comment by rabraga** [comment]
Boas!!

Mesmo tentando com outro destinatário, que supostamente não tem irregularidade fiscal?

Não fiz testes nem estudos aprofundados, mas acho que nada tem a ver com a SPED-NFE.

**Comment by ivanmestre** [comment]
Eu testei com o mesmo destinatário, e quasi os mesmos dados que uma nota que tinha funcionado antes. Tambem testei com os dados de um destinatário de uma nota gerada no 15/7 num outro sistema de emissão de notas em produção. Com os dois recebi a mesma mensagem. A única coisa que os dois destinatários tem em comum é que eles não tem IE.

**Comment by rabraga** [comment]
Qual o CNPJ?

**Comment by ivanmestre** [comment]
46068425000133 e 00149396000133

**Comment by rabraga** [comment]
Não consegui consultar nenhum dos dois CNPJ... 

Consulta Cadastro na SEFAZ: SP / 46068425000133 /
  ERRO - 259 / Rejeição: CNPJ da consulta não cadastrado como contribuinte na UF

**Comment by ivanmestre** [comment]
Eu preenchei eles como "Não contribuintes" a tag dest no xml ficou assim:

`<dest>
            <CNPJ>00149396000133</CNPJ>
            <xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
            <enderDest>
                <xLgr>Avenida Jurema</xLgr>
                <nro>45</nro>
                <xBairro>Indianópolis</xBairro>
                <cMun>3550308</cMun>
                <xMun>São Paulo</xMun>
                <UF>SP</UF>
                <CEP>04079000</CEP>
                <cPais>1058</cPais>
                <xPais>BRASIL</xPais>
            </enderDest>
            <indIEDest>9</indIEDest>
        </dest>`

**Comment by robmachado** [comment]
Esses CNPJ não tem registro na SEFAZ, mas estão válidos na Receita Federal.
No caso desses CNPJ tem que considerar emissão para consumidor FINAL caso contrario haverá erro.

**Comment by ivanmestre** [comment]
O campo indFinal que indica se a emissão é para consumidor final foi preenchido, e se não fosse assim a mensagem sería de rejeição (Rejeição: Operação com não contribuinte deve indicar
operação com consumidor final) nao de denegação.

Este é o xml completo sem a informação do emitente:

`<?xml version="1.0" encoding="UTF-8"?>
<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
    <infNFe Id="NFe35190711063844000106550020000000421336828505" versao="4.00">
        <ide>
            <cUF>35</cUF>
            <cNF>33682850</cNF>
            <natOp>VENDA</natOp>
            <mod>55</mod>
            <serie>2</serie>
            <nNF>42</nNF>
            <dhEmi>2019-07-22T22:53:11+02:00</dhEmi>
            <tpNF>1</tpNF>
            <idDest>1</idDest>
            <cMunFG>3502754</cMunFG>
            <tpImp>1</tpImp>
            <tpEmis>1</tpEmis>
            <cDV>5</cDV>
            <tpAmb>2</tpAmb>
            <finNFe>1</finNFe>
            <indFinal>1</indFinal>
            <indPres>0</indPres>
            <procEmi>0</procEmi>
            <verProc>1</verProc>
        </ide>
        <dest>
            <CNPJ>00149396000133</CNPJ>
            <xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
            <enderDest>
                <xLgr>Avenida Jurema</xLgr>
                <nro>45</nro>
                <xBairro>Indianópolis</xBairro>
                <cMun>3550308</cMun>
                <xMun>São Paulo</xMun>
                <UF>SP</UF>
                <CEP>04079000</CEP>
                <cPais>1058</cPais>
                <xPais>BRASIL</xPais>
            </enderDest>
            <indIEDest>9</indIEDest>
        </dest>
        <det nItem="1">
            <prod>
                <cProd>P-0001</cProd>
                <cEAN>SEM GTIN</cEAN>
                <xProd>Libro</xProd>
                <NCM>01012100</NCM>
                <CFOP>5101</CFOP>
                <uCom>PACOTE</uCom>
                <qCom>1.00</qCom>
                <vUnCom>500.00</vUnCom>
                <vProd>500.00</vProd>
                <cEANTrib>SEM GTIN</cEANTrib>
                <uTrib>PACOTE</uTrib>
                <qTrib>1.00</qTrib>
                <vUnTrib>500.00</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>136.25</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>500.00</vBC>
                        <pICMS>18.0000</pICMS>
                        <vICMS>90.00</vICMS>
                    </ICMS00>
                </ICMS>
                <IPI>
                    <cEnq>301</cEnq>
                    <IPITrib>
                        <CST>50</CST>
                        <vBC>500.00</vBC>
                        <pIPI>0.0000</pIPI>
                        <vIPI>0.00</vIPI>
                    </IPITrib>
                </IPI>
                <PIS>
                    <PISOutr>
                        <CST>49</CST>
                        <vBC>500.00</vBC>
                        <pPIS>1.6500</pPIS>
                        <vPIS>8.25</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>49</CST>
                        <vBC>500.00</vBC>
                        <pCOFINS>7.6000</pCOFINS>
                        <vCOFINS>38.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <total>
            <ICMSTot>
                <vBC>500.00</vBC>
                <vICMS>90.00</vICMS>
                <vICMSDeson>0.00</vICMSDeson>
                <vFCP>0.00</vFCP>
                <vBCST>0.00</vBCST>
                <vST>0.00</vST>
                <vFCPST>0.00</vFCPST>
                <vFCPSTRet>0.00</vFCPSTRet>
                <vProd>500.00</vProd>
                <vFrete>0.00</vFrete>
                <vSeg>0.00</vSeg>
                <vDesc>0.00</vDesc>
                <vII>0.00</vII>
                <vIPI>0.00</vIPI>
                <vIPIDevol>0.00</vIPIDevol>
                <vPIS>8.25</vPIS>
                <vCOFINS>38.00</vCOFINS>
                <vOutro>0.00</vOutro>
                <vNF>500.00</vNF>
                <vTotTrib>136.25</vTotTrib>
            </ICMSTot>
        </total>
        <transp>
            <modFrete>9</modFrete>
        </transp>
        <cobr>
            <fat>
                <nFat>FA1907-0009</nFat>
                <vOrig>500.00</vOrig>
                <vDesc>0.00</vDesc>
                <vLiq>500.00</vLiq>
            </fat>
            <dup>
                <nDup>001</nDup>
                <dVenc>2019-07-29</dVenc>
                <vDup>166.67</vDup>
            </dup>
            <dup>
                <nDup>002</nDup>
                <dVenc>2019-08-08</dVenc>
                <vDup>166.67</vDup>
            </dup>
            <dup>
                <nDup>003</nDup>
                <dVenc>2019-08-18</dVenc>
                <vDup>166.67</vDup>
            </dup>
        </cobr>
        <pag>
            <detPag>
                <tPag>03</tPag>
                <vPag>500.00</vPag>
            </detPag>
            <vTroco>0.00</vTroco>
        </pag>
        <infAdic/>
    </infNFe>
</NFe>
`

**Comment by robmachado** [comment]
Vamos seguir o raciocínio:
- a biblioteca montou o xml    OK
- a biblioteca assinou e validou o xml com o XSD OK
- a biblioteca enviou a mensagem para a SEFAZ, com sucesso OK
- a SEFAZ retornou uma resposta, então ele recebeu corretamente a mensagem enviada OK
- **a SEFAZ denegou impropriamente o XML ???, então deve ser alguma falha na SEFAZ**
Como essa NT entrou em vigor agora pode ser isso que está causando a denegação pois em principio está tentando validar o CNPJ do destinatário com o CCC Cadastro Centralizado de Contribuintes e pode estar ai a falha. Não consigo ver nenhum problema na biblioteca (não nego que pode ser algo nela, mas acho muito difícil).

**Comment by lukinhaspm** [comment]
Estou de acordo com o Roberto.

Semana passada a homologação de SP estava retornando diferença de valores
no meu XML sendo que todos os valores bateram na conta na mão, sem casas
decimais com arredondamento - fiz em produção e estava OK.

Lembro ainda que a base de consulta de cadastros do ambiente de homologação
é diferente do de produção, podendo estar desatualizado.

abs

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em ter, 23 de jul de 2019 às 14:30, Roberto L. Machado <
notifications@github.com> escreveu:

**Comment by ivanmestre** [comment]
Tem cómo contatar a SEFAZ para informar disso? Obrigado pela ajuda

**Comment by lukinhaspm** [comment]
Pelo que estava lendo seu post, de novo, em produção também aconteceu isso?
Se sim, eu aconselho a falar com o cliente... ou tentar emitir novamente em
produção, e pelo q entendi agora, você esta tentando emitir em homologação
pois não conseguiu em produção? Se sim, insisto que você fale com o cliente
e diga o que esta acontecendo. Veja essa referência:
https://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-302-uso-denegado-irregularidade-fiscal-do-destinat%C3%A1rio-como-resolver-28.html


Na última pergunta, você pode entrar em contato com a Secretaria da Fazenda
-  https://portal.fazenda.sp.gov.br/Paginas/fale-conosco.aspx

Deixo as dicas:
- Seja claro
- Escreva em tópicos
- Diga tudo que já tentou

Pois eles são pragmáticos e depende quem atender é bem direto e dão
respostas RUINS.

Aabs

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em ter, 23 de jul de 2019 às 14:47, ivanmestre <notifications@github.com>
escreveu:

**Comment by ivanmestre** [comment]
Ainda não testei em produção. Eu estou fazendo um sistema para substituir um outro sistema, por isso só estou gerando en ambiente de homologação porque o sistema ainda não está terminado e estou testando as funcionalidades. No outro sistema as notas são geradas em produção e estão funcionando, mas não usam o sped-nfe porque é um programa de PC.

**Comment by lukinhaspm** [comment]
Abre o chamado então, mas deve ser problema de diferença de ambiente do
SEFAZ...

abs

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em ter, 23 de jul de 2019 às 15:10, ivanmestre <notifications@github.com>
escreveu:

**Comment by rabraga** [comment]
De acordo com o @robmachado ... Não há o que fazer na SPED-NFE. Isso é regra de negócio. Consulte a SEFAZ de SP.

**Comment by ivanmestre** [comment]
Boa tarde, entrei em contato com a SEFAZ. Eles revisaram o CNPJ do emitente e do destinatário e disseram que isso não deveria estar acontecendo. Eles me disseram para entrar em contato com os desenvolvedores da biblioteca. O que vocês acham? Tem como resolver?

**Comment by lukinhaspm** [comment]
@ivanmestre vc testou em outro emissor? ex, o do http://www.sebrae.com.br/sites/PortalSebrae/ufs/sp/institucional/emissor-da-nf-e,43ce5762777fa510VgnVCM1000004c00210aRCRD ? Acho que seria um começo, se funcionar daria para comparar os XMLs

**Comment by joaoroyosilva** [comment]
Tenta gerar com a tag indPres = 9 e indFinal = 1

**Comment by robmachado** [comment]
Vou encerrar essa ISSUE, caso o problema persista me avisem
