### ISSUE TITLE
Sped-nfe 5 não está gerando xml com o $xml = $nfe->getXML(); 

### ISSUE THREAD

**Issue by renatoandradeweb** [nfephp-org/sped-nfe#695]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.0

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
$xml = $nfe->getXML(); deveria gerar as tags do xml

## Comportamento Atual
$xml = $nfe->getXML(); não funciona na versão 5

## Solução possível
<! --- Não é obrigatório, mas sugere uma correção / razão para o bug, ->

## Passos para reproduzir
<! --- Forneça um link para um exemplo ativo ou um conjunto de etapas não ambíguo para ->
<! --- reproduzir este bug. Incluir código para reproduzir, se relevante ->
1
2
3
4

## Contexto (Ambiente)
<! --- Como esse problema afetou você? O que você está tentando realizar? ->
Estou tentando emitir, após a atualização que fiz com o composer não aceita.
<! --- O fornecimento de contexto ajuda-nos a encontrar uma solução que seja mais útil no mundo real ->

<! --- Forneça um resumo geral do problema no Título acima ->

## Descrição detalhada
<! --- Forneça uma descrição detalhada da alteração ou adição que você está propondo ->

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Pode elaborar mais como reproduzir esse erro que você relata ??
Você debugou sua aplicação ??
Você checou o exemplo da documentação ?

**Comment by geovanent** [comment]
Amigo verifique se possui algum erro na geração do XML, estava tendo o mesmo problema quando fui ver eu não estava tratando os erros.

Exemplo de tratamento.
```
if(count($nfe->errors) > 0){
            foreach($nfe->errors as $erro){
                echo "<b>$erro</b> <br />";
            }
            die('Corriga os erros e tente novamente!');
        }
```

**Comment by intermaritima** [comment]
Estou obtendo mesmo problema e o tratamento de erros não me indica problema.
