### ISSUE TITLE
Erro Nao existe autorizador

### ISSUE THREAD

**Issue by dutopfave** [nfephp-org/sped-nfe#697]
Estou com um problema de autorização de sigla parece:
`Nao existe autorizador [01329621000186] para os webservices do modelo [55]`

a aplicação q to fazendo é essa:

`<?php 
error_reporting(E_ALL);
ini_set('display_errors', 'On');
require_once 'bootstrap.php';
use NFePHP\NFe\Tools;
use NFePHP\Common\Certificate;
use NFePHP\Common\Soap\SoapCurl;
//tanto o config.json como o certificado.pfx podem estar
//armazenados em uma base de dados, então não é necessário 
///trabalhar com arquivos, este script abaixo serve apenas como 
//exemplo durante a fase de desenvolvimento e testes.
$arr = [
    "atualizacao" => "2018-02-06 06:01:21",
   "tpAmb" => 2, // Se deixar o tpAmb como 2 você emitirá a nota em ambiente de homologação(teste) e as notas fiscais aqui não tem valor fiscal
   "razaosocial" => "TRANSPORTADORA DO VALE LTDA",
   "siglaUF" => "GO",
   "cnpj" => "01329621000186",
   "schemes" => "PL_009_V4",
   "versao" => "4.00",
   "tokenIBPT" => "AAAAAAA"
];
$configJson = json_encode($arr);
$pfxcontent = file_get_contents('certificate.pfx');
$tools = new Tools($configJson, Certificate::readPfx($pfxcontent, 'minhaSenha'));
$tools->model('55');
//sempre que ativar a contingência pela primeira vez essa informação deverá ser 
//gravada na base de dados ou em um arquivo para uso posterior, até que a mesma seja 
//desativada pelo usuário, essa informação não é persistida automaticamente e depende 
//de ser gravada pelo ERP
$aResposta = array();

//e se necessário carregada novamente quando a classe for instanciada

//executa a busca por documentos
$xml = $tools->sefazDistDFe('AN', '1', $arr['cnpj'], '0', '0', $aResposta);`

**Comment by robmachado** [comment]
Meu amigo não sei da onde vocês pegam esses códigos !!

isto está errado $xml = $tools->sefazDistDFe('AN', '1', $arr['cnpj'], '0', '0', $aResposta);`

veja https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/DistDFe.md

**Comment by dutopfave** [comment]
Entendi, fiz o procedimento do link que vc me mando, ai carrego.... carrego e dps fico página em branco, no código que se mando fala em chama o $response, será q isso q nao carrego??

desculpa pode se ate pergunta besta, é q estou começando a mexer com nota fiscal e tals... mais obrigado pela atenção.

**Comment by dutopfave** [comment]
Aparentimente deu certo aki, mostro XML aki no elements do navegador, mais pra baixa o xml ?
