### ISSUE TITLE
Sefaz do Pará muda ambiente de autorização de NF-e e NFA-e

### ISSUE THREAD

**Issue by michelfarias** [nfephp-org/sped-nfe#702]
* **Estou enviando um ...**
  - [ X ] Atualização

## Comportamento esperado
Atualização WS da Sefaz do Pará

## Comportamento Atual
Funciona por enquanto, até dia 2 de setembro

## Solução possível
Atualizar listas de WS

LINK Oficial da noticia: 
http://sefa.pa.gov.br/index.php/noticias/15474-autorizacao

**Comment by robmachado** [comment]
Alteração programada para subir no repositório na sexta-feira dia 30/08/2019, com a alteração do arquivo [storage/autorizadores.json](https://github.com/nfephp-org/sped-nfe/blob/master/storage/autorizadores.json) na chave relativa ao modelo 55 (hoje => SVAN e na sexta => SVRS)

**Comment by robmachado** [comment]
Alterado
