### ISSUE TITLE
Erro de comunicação com servidor GO

### ISSUE THREAD

**Issue by eltonjosesouza** [nfephp-org/sped-nfe#716]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.6.*",
        "nfephp-org/sped-ibpt": "^2.0",
        "nfephp-org/sped-mail": "^0.1",
        "nfephp-org/sped-nfe": "^5.0",

## Comportamento esperado
Realizar a requisição Soap e buscar as notas

## Comportamento Atual
Esta retornando esse erro
Config de envio
`{
    "atualizacao": "2019-10-17 02:33:38",
    "tpAmb": 1,
    "razaosocial": "*",
    "siglaUF": "GO",
    "cnpj": "*",
    "schemes": "PL_009_V4",
    "versao": "4.00",
    "tokenIBPT": "*",
    "CSC": "*",
    "CSCid": "*",
    "aProxyConf": {
        "proxyIp": "",
        "proxyPort": "",
        "proxyUser": "",
        "proxyPass": ""
    }
}`

Erro retornado

An error occurred while trying to communication via soap,  SSL read: error: 00000000:lib(0):func(0):reason(0), errno 104 [https: //www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx] 24
Undefined variable: resp

## Solução possível
<! --- Não é obrigatório, mas sugere uma correção / razão para o bug, ->

## Passos para reproduzir
1 - Só realizei a requisição e começou a dar esse erro

## Contexto (Ambiente)
Estou tentando baixar as notas emitidas contra o  CNPJ

## Descrição detalhada
Começou a dar o problema esporadicamente, agora esta todo o momento e não baixa mais as notas

## Possível implementação
<! --- Não é obrigatório, mas sugere uma ideia para implementar adição ou alteração ->

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Erro 104 significa que a conexão foi resetada pelo servidor.
De forma geral esse é um erro causado por alguma falha ou sobrecarga no servidor.

Mas pode ter a haver com o certificado enviado para a conexão.
No passado GO apresentava  erro na comunicação com o ambiente de homologação, devido a um erro na configuração dos servidores DELES, que incorretamente exigia que o próprio certificado do emitente contivesse TODA a cadeia de certificados dentre dele (o que não é de forma alguma usual ou exigido).
Acredito que esse problema seja devido a falhas no próprio servidor da SEFAZ GO, ou se seu servidor não conseguir se comunicar com nenhum outro SEFAZ e os erros retornados dos outros SEFAZ for parecido com esse, então é bem provável que a falha esteja no seu ambiente.
