### ISSUE TITLE
[dev-master] Erro na Chave de Acesso - Campo Id nao corresponde a concatenacao dos campos correspondentes

### ISSUE THREAD

**Issue by rodolfojnn** [nfephp-org/sped-nfe#718]
* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.00

## Comportamento esperado
Emissão da NF-e

## Comportamento Atual
Ao atualizar para a branch dev-master atual, deu o seguinte erro:
**[cStat 502] Erro na Chave de Acesso - Campo Id nao corresponde a concatenacao dos campos correspondentes**
Fizemos o downgrade para a v5.0.91 e voltou a funcionar

Exemplo de uma chave que deu problema: NFe41191111812498000103650050000010451515607994

Será que tem a ver com o dígito verificador?

**Comment by robmachado** [comment]
O comportamento da classe Make foi alterado.
1 - se a chave de 44 digitos não for passada como parâmetro na tagInfNFe() um chave será criada e inserida;
2 - se a chave for passada, essa chave SERÁ usada mesmo que incorreta. 
Para saber se a chave é incorreta ou não você deve agora checar os erros da classe com getErrors()

**Comment by rodolfojnn** [comment]
Perfeitamente. Mas em nosso código não estou setando a propriedade "Id" na tagInfNFe, apenas a "versao".

```
$std = new \stdClass();
$std->versao = $nfeTools->config->versao;
$nfe->taginfNFe($std);
```

Então acredito que a chave incorreta seja a gerada pelo Make, lá no checkNFeKey(Dom $dom)

**Comment by robmachado** [comment]
Já foi corrigido esse erro ! teste por favor

**Comment by rodolfojnn** [comment]
Deu certo! Muito obrigado pelo retorno!
