### ISSUE TITLE
Erro ao normalizar o carácter ampersand (&) parte 2

### ISSUE THREAD

**Issue by rdtHK** [nfephp-org/sped-nfe#728]
**Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp**. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* **Por favor, conte-nos sobre o seu ambiente:**

	- nfephp-org/sped-nfe versão 5.0.84 mas também deve afetar a versão mais recente

## Comportamento esperado

Transformar os '&' no xNome em '\&amp;':

```xml
<emit>
    <CNPJ>10733362000145</CNPJ>
    <xNome>Santos &amp; Tessaro Ltda</xNome>
    <xFant>Pureza Gourmet</xFant>
    <IE>283523050</IE>
    <CRT>1</CRT>
</emit>
```

## Comportamento Atual

Os '&' são convertidos para '\&amp;amp;':

```xml
<emit>
    <CNPJ>10733362000145</CNPJ>
    <xNome>Santos &amp;amp; Tessaro Ltda</xNome>
    <xFant>Pureza Gourmet</xFant>
    <IE>283523050</IE>
    <CRT>1</CRT>
</emit>
```

Esse erro deve acontecer em todos os lugares onde o equilizeParameters é chamado antes do addChild/setAttribute.

## Solução possível

Remover o String::replaceUnacceptableCharacters do método equilizeParameters.

O addChild da classe DOMImproved já chama o htmlspecialchars que faz quase as mesma coisa (o htmlspecialchars sempre substitui o '&' e o replaceUnacceptableCharacters só substitui '& ').
E o setAttribute do DOMDocument também converte os caracteres para as entities correspondentes (menos o ').

## Passos para reproduzir
	
```php
$make = new NFePHP\NFe\Make();

$std = new \stdClass();
$std->xNome = "Santos & Tessaro Ltda";
$std->xFant = "Pureza Gourmet";
$std->IE = "283523050";
$std->IEST = NULL;
$std->IM = NULL;
$std->CNAE = NULL;
$std->CRT = "1";
$std->CNPJ = "10733362000145";

echo $make->dom->saveHTML($make->tagemit($std));
```

Pelo menos na versão 5.0.84 do sped-nfe esse código retorna

```xml
<emit>
	<CNPJ>10733362000145</CNPJ>
	<xNome>Santos &amp;amp; Tessaro Ltda</xNome>
	<xFant>Pureza Gourmet</xFant>
	<IE>283523050</IE>
	<CRT>1</CRT>
</emit>
```

Esse erro também acontece com atributos:

```php
$make = new Make();

$std = new \stdClass();
$std->xCampo = "foo <> '\"";
$std->xTexto = "";

echo $make->dom->saveHTML($make->tagobsFisco($std));
```

retorna

```xml
<obsFisco xCampo="foo &amp;lt;&amp;gt; &amp;#39;&amp;quot;">
	<xTexto/>
</obsFisco>
```

## Contexto (Ambiente)

Tentei gerar uma nfe com um & no nome do emitente e o '&' virou '\&amp;amp;' no xml.

## Descrição detalhada

No início do Make::tagemit ele chama o equilizeParameters que converte o & no nome do emitente para \&amp;.
Depois, quando ele adiciona o xNome ao $emit, o DOMImproved::addChild chama htmlspecialchars no conteudo da tag (o xNome), transformando o
'\&amp;' em '\&amp;amp;'.

O setAttribute do DOMDocument também faz essas substituições (menos o '). Exemplo:

```php
$make = new Make();

$std = new \stdClass();
$std->xNome = "Santos & Tessaro Ltda <> '\"";

$emit = $make->dom->createElement("emit");
$emit->setAttribute("xNome", $std->xNome);
$res = $make->dom->saveHTML($emit);
```

Retorna 

```xml
<emit xNome="Santos &amp; Tessaro Ltda &lt;&gt; '&quot;"></emit>
```

Esse bug já foi reportado em: https://github.com/nfephp-org/sped-nfe/issues/633

Mas a versão v5.0.84, que foi lançada depois da versão com a correção (v5.0.78), apresenta o mesmo problema.

Esse erro ainda deve acontecer na versão mais recente do sped-nfe. 
O Make ainda chama o Strings::replaceUnacceptableCharacters antes do DOMImproved::addChild que também usa o htmlspecialchars.

**Comment by robmachado** [comment]
Você tem toda razão !!
A classe DOMImproved **não deve fazer isso** .. estou alterando o sped-common e removendo essa duplicidade.

**Comment by robmachado** [comment]
a v5.0.44 do sped-common já está disponivel com a remoção do htmlspecialchars do método DOMImproved::addChild().
Pois **não é adequado** que esse filtro fique nessa classe. 
Os dados que chegam a ela (DOMImproved) já devem ter sido previamente normalizados.

**Comment by robmachado** [comment]
Muito obrigado por sua ajuda extremamente clara e precisa. :+1:
