### ISSUE TITLE
ERRO Qrcode (gerado automaticamente) SEFAZ MA 

### ISSUE THREAD

**Issue by rjlfurtado** [nfephp-org/sped-nfe#730]
* **Erro nas URLs geradas automaticamente no QRCode ...**
  - [x] 395 - [Simulacao] Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto
--

* ** Estou utilizando o ambiente de homologação**

  - Versão do leiaute: NFC-e 4.0
  - Modelo: 65
## Solução possível

(MA) Testei com o endereço abaixo e funcionou corretamente.

* 1- http://www.hom.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp?
* 2- É necessário que seja utilizado o protocolo (HTTP) e não o (HTTPS) 

Deve ser atualizado a URL do MA pois é um problema para mim e imagino que para os mais novos do que eu também seja.

**Comment by robmachado** [comment]
Você pode informar qual é o URL correto ? Para que eu possa atualizar !
O site do ENCAT onde deveriam ter as informações corretas, tem sempre os dados **incorretos e incompletos**, dessa forma sem a ajuda dos colegas que usam e acessam esses serviços fica inviável manter esses dados corretos.

**Comment by rjlfurtado** [comment]
Olá, meu amigo.
Primeiramente, muito obrigado pelo seu excelente trabalho!
Eu verifiquei aqui nesse link e percebi que está atualizado os links para o Maranhão (MA).
Segue: http://nfce.encat.org/desenvolvedor/qrcode/

**Comment by rjlfurtado** [comment]
Brother @robmachado, apesar de ambos os links estarem funcionando, com a atualização que você fez agora pouco adicionando: 

> https://homologacao.sefaz.ma.gov.br/portal/consultarNFCe.jsp

O problema continuou, então eu setei o endereço dentro do XML (no dedo): 

> http://www.hom.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp

Aí sim funcionou normal.

**Comment by rjlfurtado** [comment]
Não atendido.
