### ISSUE TITLE
Erro URL ambiente de Homologação Sefaz-MA 

### ISSUE THREAD

**Issue by rjlfurtado** [nfephp-org/sped-nfe#734]
Erro nas URLs geradas automaticamente no QRCode ...

 395 - [Simulacao] Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto
--
** Estou utilizando o ambiente de homologação**

Versão do leiaute: NFC-e 4.0
Modelo: 65
Solução possível
(MA) Testei com o endereço abaixo e funcionou corretamente.

1- http://www.hom.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp?
2- É necessário que seja utilizado o protocolo (HTTP) e não o (HTTPS)
Deve ser atualizado a URL do MA pois é um problema para mim e imagino que para os mais novos do que eu também seja.

**Comment by rjlfurtado** [comment]
Sem resolução, tempo perdido na tentativa de ajudar.

**Comment by robmachado** [comment]
Rafael;
Seu tempo não é igual ao meu tempo. Cada um sabe a sua própria disponibilidade. 
Lembre-se que esse é um pacote OpenSouce não ganho nada (ou quase nada) com isso, e trabalho no meu tempo livre.
