### ISSUE TITLE
This XML is not valid. Expected is imposto 

### ISSUE THREAD

**Issue by eumanito** [nfephp-org/sped-nfe#742]
Quando não preencho a tag vTotTrib (M02) nos produtos/serviços não está criando a tag <imposto> inteira, sendo que o campo é opcional segundo o manual.

Alguém pode me ajudar?

Erro:
`This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}det': Missing child element(s). Expected is ( {http://www.portalfiscal.inf.br/nfe}imposto ).`

**Comment by robmachado** [comment]
vTotTrib deve ser passada mesmo que seja 0.00

**Comment by eumanito** [comment]
Obrigado @robmachado, consegui resolver passando o número do item assim:
`$params['item'] = $i;
$nfe->tagimposto((object)$params);`
