### ISSUE TITLE
Erro no Make()

### ISSUE THREAD

**Issue by felipeparente** [nfephp-org/sped-nfe#744]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ x ] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:
"php": ">=7.2",
"cakephp": "3",
"nfephp-org/sped-nfe": "^5.0",

## Comportamento esperado
Informar o erro referente a criação do XML

## Passos para reproduzir
$nfe = new Make();

$std = new \stdClass();
$std->versao = '4.00'; //versão do layout (string)
$std->Id = 'NFe35150271780456000160550010000000021800700082'; //se o Id de 44 digitos não for passado será gerado automaticamente
$std->pk_nItem = null; //deixe essa variavel sempre como NULL

$nfe->taginfNFe($std);
...
$nfe->monta(); ou $nfe->getXML();

Se informar o "Id", ocorre uma exceção na geração do XML, mas esse erro não aparece no "getErrors()"

**Comment by robmachado** [comment]
$std->Id = 'NFe35150271780456000160550010000000021800700082';

Correto 
**$std->Id = '35150271780456000160550010000000021800700082';**

**Comment by felipeparente** [comment]
> $std->Id = 'NFe35150271780456000160550010000000021800700082';
> 
> Correto
> **$std->Id = '35150271780456000160550010000000021800700082';**

Entendi, porém o getErrors() não informa nada.. Vêm vazio.

**Comment by robmachado** [comment]
Certo vou dar uma olhada nisso Obrigado ! 
assim que resolver você vai receber o aviso do GITHUB

**Comment by robmachado** [comment]
Isso não é um erro !
1 - a chave passada tem os caracteres não numéricos removidos
2 - se a chave estiver incorreta um erro será relatado
3 - se houverem erros a reportar será lançado um execption pelo método monta()

Você deve capturar a exception e ver como irá tratar
