### ISSUE TITLE
Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by victorvilella** [nfephp-org/sped-nfe#746]
* **Estou enviando um...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* **Meu ambiente:**
  * PHP 7.4 32 bits
  * Windows
  * Apache

  - Versão do leiaute:
## Comportamento esperado
A constante `SOAP_1_2` deveria existir quando habilitamos a extensão `soap`, fazendo com que o código seja alimentado corretamente e a emissão da nota seja feita sem problemas

## Comportamento Atual
Por algum motivo, esta constante não está definida no meu ambiente, gerando erro.

## Solução possível
A declaração de uma constante dentro da classe `NFePHP\NFe\Common\Tools` com valor `2` (Referente ao valor original da constante) pode corrigir o problema.

## Passos para reproduzir
1 Montar seu ambiente em uma instalação com PHP 7.4 32 bits no Windows e Apache
2 Tentar emitir uma NFe normalmente

## Possível implementação
Acredito que se simplesmente refatorássemos o valor da constante para o inteiro `2` ou criar uma constante dentro da classe possa resolver o problema.
```php 
<?php 
class Tools {
  public const SOAP_1_2 = 2;
}
```

**Comment by robmachado** [comment]
Estranho !! pois tenho varias instalações rodando e nunca tive problemas com isso !
Qual é o S.O. que você está usando ?

**Comment by robmachado** [comment]
Verifique se você tem o modulo SOAP instalado na maquina php-soap e me informe por gentileza.

**Comment by robmachado** [comment]
Apenas esclarecendo, essa constante integra o PHP (pelo modulo SOAP) bem comi muitas outras constantes usadas no projeto como as do cURL. Eu procurei na net para ver se existe prespectiva de remover essas constantes do PHP, mas não achei nada a respeito.

**Comment by victorvilella** [comment]
Também achei muito estranho. A princípio eu fiz tudo corretamente (senão o composer não conseguiria instalar este projeto, imagino eu).

Pensando bem, a chance de ser algum erro meu é considerável.

**Comment by victorvilella** [comment]
EU vou fechar esta issue pois eu creio que seja algum problema de build da versão do PHP que estou usando. Estou usando a 7.4.1 liberada dois ou três dias depois de eu montar meu ambiente. Acho que se eu fizer um downgrade para a 7.3 esse erro não acontecerá.

**Comment by luanmarcosfgns** [comment]
Isso é por a extensão SOAP não está habilitada no PHP o meu deu esse problema e resolvi fazendo isso
