### ISSUE TITLE
Erro ao tentar baixar uma xml

### ISSUE THREAD

**Issue by izacximenes** [nfephp-org/sped-nfe#750]
* **Estou enviando um ...**
  - [ X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  
    PHP 7.2
    UBUNTU
    Apache

Estou tentando baixar uma xml usando:
 https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/Download.md

 Mas estou recebendo o seguinte erro:

 Warning: Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP) in /var/www/html/.../vendor/nfephp-org/sped-nfe/src/Common/Tools.php on line 524

Notice: Undefined index: SOAP_1_2 in /var/www/html/.../vendor/nfephp-org/sped-common/src/Soap/SoapBase.php on line 414
An error occurred while trying to communication via soap, [https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx]HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/soap+xml; charset=utf-8
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Fri, 21 Feb 2020 17:31:36 GMT
Content-Length: 0

**Comment by robmachado** [comment]
Isso nada tem haver com a biblioteca, e algum problema na compilação do PHP no seu ambiente.
As constantes SOAP_1_2 e várias outras estão dentro do próprio PHP.
vide https://www.php.net/manual/pt_BR/soap.constants.php

**Comment by izacximenes** [comment]
Vou verificar, obrigado!

**Comment by izacximenes** [comment]
O problema foi resolvido reiniciando o serviço do apache, obrigado!
