### ISSUE TITLE
This XML is not valid. Element

### ISSUE THREAD

**Issue by sousaakira** [nfephp-org/sped-nfe#751]
Estou recebendo os seguintes erros ao tentar gera uma nota

`This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}vTotTrib': [facet 'pattern'] The value '86.4' is not accepted by the pattern '0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.

Element '{http://www.portalfiscal.inf.br/nfe}vTotTrib': '86.4' is not a valid value of the atomic type '{http://www.portalfiscal.inf.br/nfe}TDec_1302'.

Element '{http://www.portalfiscal.inf.br/nfe}vTotTrib': [facet 'pattern'] The value '27.6' is not accepted by the pattern '0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.

Element '{http://www.portalfiscal.inf.br/nfe}vTotTrib': '27.6' is not a valid value of the atomic type '{http://www.portalfiscal.inf.br/nfe}TDec_1302'.

{"Status":"Ok"}`

**Comment by robmachado** [comment]
vTotTrib deve ser "86.40" com duas casas decimais

**Comment by RafaelHerculano** [comment]
Por favor, estou com um problema que não estou conseguindo resolver há dias.
This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}infRespTec': This element is not expected. Expected is one of ( {http://www.portalfiscal.inf.br/nfe}infAdic, {http://www.portalfiscal.inf.br/nfe}exporta, {http://www.portalfiscal.inf.br/nfe}compra, {http://www.portalfiscal.inf.br/nfe}cana )

Poderiam me ajudar?

**Comment by robmachado** [comment]
Este não é o canal adequado para isso !
Use o grupo Nfephp https://groups.google.com/g/nfephp para postar suas perguntas
