### ISSUE TITLE
sefazCadastro (MT) (Unable to load cURL, verify if libcurl is installed)

### ISSUE THREAD

**Issue by lramondev** [nfephp-org/sped-nfe#752]
Ao utilizar o método sefazCadastro com a sigla MT o sistema me retorna um erro de libcurl, msm alterando a versão do protocolo.
"$tools->soap->httpVersion('1.1')"
Nos outros estados o retorno funciona.

Versão da biblioteca: "nfephp-org/sped-nfe" : "^5.0"
Servidor: Ubuntu Server 18.04
PHP: 7.3.15

**Comment by robmachado** [comment]
Qual erro ??
Qual o envelope enviado ?

**Comment by robmachado** [comment]
Em um teste local o que obtenho é 
INTERNAL ERROR 500 ou seja um erro do servidor e não um erro do libcurl

**Comment by lramondev** [comment]
Obs: O erro não tem nada a ver com libcurl. Fiz confusão.
**Erro**:
NFePHP \ Common \ Exception \ SoapException
An error occurred while trying to communication via soap, [https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro4]HTTP/1.1 500 Internal Server Error Connection: close Date: Wed, 04 Mar 2020 12:34:59 GMT Content-Type: application/soap+xml; charset=utf-8; action="http://www.w3.org/2005/08/addressing/soap/fault" Set-Cookie: BIGipServer~Interno~POOL-NFE=rd1o00000000000000000000ffffc0a80211o12071; path=/; Httponly; Secure Set-Cookie: f5avraaaaaaaaaaaaaaaa_session_=MAPFENMJAMPOFGDHPBNBFCLPMPFKKBCLANAFNLGNFFKEPCMNBBKNBBIAKFJGBLKJJEGDCMICAAPDKCKDCFPAOAGKEKAPGNDLAFCOAILGOGKNIGLCJAMKCELMJFCLANPM; HttpOnly; secure

**-$this->urlService**: https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro4
**-$this->urlMethod**: consultaCadastro4
**-$this->urlAction** : "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro4" 
**-SOAP_1_2** : 2
**-$parameters**: Array ( [nfeDadosMsg] => CONS-CADMT33337122008020 )
**-$this->soapnamespaces**: Array ( [xmlns:xsi] => http://www.w3.org/2001/XMLSchema-instance [xmlns:xsd] => http://www.w3.org/2001/XMLSchema [xmlns:soap] => http://www.w3.org/2003/05/soap-envelope )
**-request**: CONS-CADMT33337122008020
**-$this->objHeader**: SoapHeader Object ( [namespace] => http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4 [name] => nfeCabecMsg [data] => Array ( [cUF] => 51 [versaoDados] => 2.00 ) [mustUnderstand] => )

**Comment by robmachado** [comment]
Acredito que compreenda o que significa ERRO 500 INTERNAL SERVER ERROR 
se não, entenda que é um erro **INTERNO do SERVIDOR da SEFAZ de MT** ou seja nada tem haver com a requisição cURL , XML ou com a biblioteca, com o PHP ou mesmo com sua aplicação ou com qq outra coisa no meio do caminho.
**Sempre que obtiver erro 500 fale com o pessoal técnico da SEFAZ.**

**Comment by lramondev** [comment]
Ok obrigado!
