### ISSUE TITLE
Arquivo de Licença com conflito

### ISSUE THREAD

**Issue by andrelugomes** [nfephp-org/sped-nfe#754]
O Arquivo https://github.com/nfephp-org/sped-nfe/blob/master/LICENSE.md esta apresentando Duas lincenças LGPL e MIT.

O erro foi adicionado nesse commit: https://github.com/nfephp-org/sped-nfe/commit/3082ad1c73dee28868fdab2f729e6b4ea3218345

Posso abrir um PR fazendo a correção? Aqui seria uma boa thread para discutir qual licença aplicar?

**Comment by robmachado** [comment]
Então ... em todos os pacotes do nfephp-org deverão ficar sobre DUPLO licenciamento
- LGPLv3 e **também MIT**
Quem for usar o pacote decide sob qual licença irá usar esse pacote.
Não é incorreto que o licenciamento seja "múltiplo", pois dependendo do caso será melhor usar uma ou outra forma.
O que o duplo licenciamento permite é uma maior liberdade para quem quer usar as bibliotecas, anexe-las aos seus produtos e vender esses produtos ou serviços, sem receio de alguma ação por direitos autorais.

**Comment by andrelugomes** [comment]
Legal @robmachado ... confesso que não conhecia o conceito do Lincenciamento Duplo. 

Agora esta claro pra mim. Se precisar de alguma ajuda é so falar...
