### ISSUE TITLE
Vb.net usar recurso

### ISSUE THREAD

**Issue by Marlonwg** [nfephp-org/sped-nfe#757]
Bom dia como uso este recurso no vb.net tem algum código para utiliza-lo 
se nao tiver entra em contato no meu e-mail preciso utilizar este complemento.

**Comment by robmachado** [comment]
Colega; eu no faço a menor ideia que como juntar PHP com VB.NET, nem sei se é possível;
Minha recomendação, para sistemas DESKTOP é você contratar uma API como por exemplo a https://www.cloud-dfe.com.br/ 
Entre muitas outras, o custo é relativamente baixo e remove a dificuldade desse tipo de "junção"

**Comment by joaoroyosilva** [comment]
No caso para aplicativos locais eu recomendo vc usar https://github.com/dfebr/dfebr-net ou framework do AcBR
