### ISSUE TITLE
An error occurred while trying to communication via soap

### ISSUE THREAD

**Issue by jsmaximo** [nfephp-org/sped-nfe#758]
ao enviar o lote da nota assinada me retorna esse erro abaixo, ja ative a extensão soap e as outras exigidas o que pode ser ?

An error occurred while trying to communication via soap,   [https://hnfe.sefaz.ba.gov.br/webservices/NFeAutorizacao4/NFeAutorizacao4.asmx]HTTP/1.1 100 Continue

HTTP/1.1 403 Forbidden
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Mon, 23 Mar 2020 15:13:09 GMT
Content-Length: 1233
)

**Comment by robmachado** [comment]
Erro 403 indica que o seu certificado não deve ser válido !! 
Podem haver outros motivos para essa falha, mas teria de investigar mais.

**Comment by gabrielmonteiroo** [comment]
jsmaximo conseguiu descobrir o erro? Comigo aconteceu a mesma coisa em todos os testes de homologação no webservice da Bahia, acredito que não seja certificado pq em produção funciona.
