### ISSUE TITLE
Gerar NFCe

### ISSUE THREAD

**Issue by lucaspaulino** [nfephp-org/sped-nfe#762]
Boa noite!!

Gente, estou terminando de implementar para gerar nota fiscal de serviço. E uma pessoa me falou que tem que ir na prefeitura.

Somente com certificado digital não dá certo para gerar as notas fiscais de serviço?

**Comment by robmachado** [comment]
Cada Prefeitura das mais de 2000 que estão usando mais de 200 modelos de NFSe diferentes, possuem suas próprias REGRAS. Veja com a prefeitura em questão !
