### ISSUE TITLE
Inserir várias formas de pagamento

### ISSUE THREAD

**Issue by rafaelvida2** [nfephp-org/sped-nfe#763]
Olá

É possível inserir várias formas de pagamento usando essa API?

**Comment by robmachado** [comment]
Sim

**Comment by joaoroyosilva** [comment]
vc pode chamar o método de inserir o pagamento diversas vezes. conforme o exemplo abaixo

  foreach ($nfe->pags as $pag) {
                    $std = new stdClass();
                    $std->tPag = $pag->paymentForm->cod;
                    $std->vPag = "0.00";
                    $std->CNPJ = $pag->cardFlag ? $pag->cardFlag->cardOperator->cnpj : '';
                    $std->tBand = $pag->cardFlag ? $pag->cardFlag->flag : '';
                    $std->cAut = $pag->cardFlag ? $pag->authorization : '';
                    if ($nfe->natOpe->goal == 4) {
                        $std->tPag = '90';
                    } else {
                        $std->vPag = number_format($pag->value, 2, '.',
                            ''); //Obs: deve ser informado o valor pago pelo cliente
                        $std->tpIntegra = 2;
                    }
                    $elem = $XMLnfe->tagdetPag($std);
                }
