### ISSUE TITLE
ERRO emissão Sefaz AM - (link WS errado) 

### ISSUE THREAD

**Issue by michelfarias** [nfephp-org/sped-nfe#772]
Estava com um problema para emitir a NFCe em homologação e apresentava o seguinte erro:

**An error occurred while trying to communication via soap,   [https://nfce.sefaz.am.gov.br/nfce-services/services/NfeConsulta4]**

HTTP/1.1 500 Internal Server Error
Date: Sun, 07 Jun 2020 22:18:21 GMT
Transfer-Encoding: chunked
Content-Type: application/soap+xml; charset=utf-8; action="http://www.w3.org/2005/08/addressing/soap/fault"
X-ORACLE-DMS-ECID: 6204acfb-6a6a-46ad-b20f-1e8e047fd9cf-0004beb3
X-ORACLE-DMS-RID: 0

Fui verificar e o endereço do WS estava errado, pois estava com espaço, portanto então gerava esse erro.

<NfeConsultaProtocolo method="nfeConsultaNF" operation="NFeConsulta4" version="4.00">	https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeConsulta4</NfeConsultaProtocolo>

E também teve outro problema na consulta da NFe assim com o mesmo problema da ISSUE: 
https://github.com/nfephp-org/sped-nfe/issues/432

Mudando de **operation="NFeConsulta4" para operation="NFeConsultaProtocolo4"** ai agora está funcionando normalmente, fui verificar no projeto principal ainda constava a url antiga mesmo havendo o fechamento dessa ISSUE.

Eu alterei em meu projeto, porém não sei como faço pra enviar pra vocês pelo git o arquivo, se puderem enviar o passo a passo para que eu possa enviar essa alteração. Obrigado

**Comment by robmachado** [comment]
Assim que é bom, acha o problema e CORRIGE !! parabéns :+1:

**Comment by michelfarias** [comment]
Muito obrigado, consegui fazer o PULL REQUEST com auxilio do Cleiton Perin. Abraços
