### ISSUE TITLE
Emissão sem CPF

### ISSUE THREAD

**Issue by lucaspaulino** [nfephp-org/sped-nfe#774]
Como configurar pra emitir sem necessidade de preencher endereço e cpf do cliente?

**Comment by robmachado** [comment]
A classe Make permite a emissão de NFCe (modelo 65) sem passar os dados do cliente o metod Make::tagDest é opcional

**Comment by lucaspaulino** [comment]
@robmachado eu fiz aqui... deu certo, mas como faço agora pra enviar sem o endereço do cliente?

**Comment by lukinhaspm** [comment]
a NFCe não exige nem o CPF e nem o endereço, é isso
