### ISSUE TITLE
Certificado inválido

### ISSUE THREAD

**Issue by lucaspaulino** [nfephp-org/sped-nfe#775]
Estou testando com um certificado e deu tudo ok para gerar as notas. Porém fui testar com outro certificado, que instalei e testei no navegador, e está dando este erro:

`Unable to read certificate, get follow error: (error:0D07209B:asn1 encoding routines:ASN1_get_object:too long)(error:0D068066:asn1 encoding routines:ASN1_CHECK_TLEN:bad object header)(error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error)(error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error)
`
Alguém sabe o que pode ser?

Obrigado,

@felipefill @guilherme-santos @fonini @gersonfs @walkeralencar

**Comment by robmachado** [comment]
Pode ser, a senha !! NUNCA use acentos nas senhas, procure usar apenas ASCII letras e números
Muitas vezes os usuários usando o windows colocam senhas em outro charset que o utf-8 então não consegue abrir o certificado.
Exporte o certificado do seu browser usando uma senha apenas com letras e números e tente novamente.

**Comment by lucaspaulino** [comment]
@robmachado então, não tem como exportar. Fala que é uma permissão de quem emitiu. A senha é 123456. Eu importei no chrome,

**Comment by robmachado** [comment]
Então me parece ser alguma falha na cópia desse certificado ou na  geração do mesmo.
Eu uso certificados da Certisign e nunca vi um problema desse tipo

**Comment by lucaspaulino** [comment]
@robmachado é isso mesmo, o sistema deu algum bug aqui que está salvando o certificado com falha. Enviei direto do phpmyadmin e deu certo, obrigado

**Comment by robmachado** [comment]
Se você está subindo o certificado tenha cuida pois é BINARIO se não configurar o script direito var dar "caca" mesmo.

**Comment by lucaspaulino** [comment]
@robmachado estava fazendo assim e funcionou, só que hoje fui subir um novo certificado e começou a dar problema e aí todos começaram a dar problema tbm. Eu envio o conteudo do certificado via post curl:

```
$imgData = addslashes(file_get_contents($file['tmp_name' ]));

					$postRequest = array('send_certified' => $imgData, 'senha' => $_POST['nf_certified_password'], 'cnpj' => preg_replace("/[^0-9]/", "", $_POST['document']));

					$cURLConnection = curl_init('https://nf.site.com.br/send_certified.php');
					curl_setopt($cURLConnection, CURLOPT_POSTFIELDS, $postRequest);
					curl_setopt($cURLConnection, CURLOPT_RETURNTRANSFER, true);

					$apiResponse = curl_exec($cURLConnection);
					curl_close($cURLConnection);
```
