### ISSUE TITLE
DistDFe - Ciencia da Operacao Duplicidade

### ISSUE THREAD

**Issue by GlauberF** [nfephp-org/sped-nfe#778]
- [X] bug
- [ ] requisição de funcionalidade
- [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

## Descrição detalhada
Para recuperar o XML completo, preciso primeiro manifestar com base no resumo do XML da nf-e.
porem quando faço a manifestação, dou **Ciencia da Operacao**, para dai sim recuperar o XML completo, esta dando rejeição.

```xml
<cStat>573</cStat><xMotivo>Rejeicao: Duplicidade de evento</xMotivo>
<chNFe>42200581015380000130550010000047911801614997</chNFe>
<tpEvento>210210</tpEvento><xEvento>Ciencia da Operacao</xEvento>
```

Sei que a rejeição é por que já foi dado Ciência, porem se dar esse problema de rejeição, vai me impedir de conseguir buscar o XML completo mesmo que quem deu Ciência não fui eu?

E para evitar que de duplicidade, existe algum método para eu saber se determinada NF-e já foi manifestada ?

**Comment by robmachado** [comment]
Primeiro isso não é um BUG, é o retorno da própria SEFAZ, nada tem haver com essa biblioteca.
Segundo, Se a NFe já está manifestada , você deve conseguir baixar a NFe.

Caso não consiga, sugiro que entre em contato com a SEFAZ e descreva o problema para eles.
