### ISSUE TITLE
Autorizar NFe 55 - Ambiente Produção

### ISSUE THREAD

**Issue by profjuliooliveira** [nfephp-org/sped-nfe#780]
* **Estou enviando um ...**
  - [ x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: NFe 4.0

## Comportamento esperado
No Ambiente de Produção precisamos Autorizar a NF mod 55, deveria ser enviada, já que conseguimos Enviar: Normalmente em Ambiente de Homologação: NF mod 65 e 55.
Normalmente no Ambiente de Produção: NF mod 65.

## Comportamento Atual
Ao trocar para Ambiente de Produção (Estado do Pará), simplesmente só retorna a Mensagem:

**_Erro ao tentar se comunicar com a Sefaz.
Não foram passados todos os dados necessários._**

Aparece um link da origem da Mensagem: ... /nfephp-org/sped-nfe/src/Tools.php
Dentro da Tools, as possíveis causas:
linha 277
       if (!isset($nSerie) || empty($nIni) || empty($nFin) || empty($xJust)) {
            throw new RuntimeException('Não foram passados todos os dados necessários.');
        }
Linha 397
        if (empty($chave) || empty($xCorrecao)) {
            throw new RuntimeException('Não foram passados todos os dados necessários.');
        }
 Linha 481
        if (empty($chave) || empty($nProt)) {
            throw new RuntimeException('Não foram passados todos os dados necessários.');
        }
dentre outros...

Obs: o XML gerado não possui nenhum erro, apenas Não consegue ser assinado.

## Solução possível
Talvez algo na estruturação (no ambiente de Produção) antes da assinatura do documento. Ou algo com o endereço de Produção para o Estado do Pará.

O Envio da NFC-e (mod 65), no ambiente de Produção está sendo autorizada Normalmente.

**Comment by profjuliooliveira** [comment]
retorno do sefaz:
Array
(
    [attributes] => Array
        (
            [versao] => 4.00
        )

    [tpAmb] => 1
    [verAplic] => SVAN_1.0.8
    [cStat] => 410
    [xMotivo] => Rejeicao: UF informada no campo cUF nao e atendida pelo Web Service
    [cUF] => 15
    [dhRecbto] => 2020-09-05T12:33:51-03:00
)

**Comment by robmachado** [comment]
Revise seu código está fazendo algo incorreto ai !

**Comment by profjuliooliveira** [comment]
Era o Webservice do Pará, que consta no arquivo (mesmo baixando com composer), está errado, foi mudado em 2018 para o Webservice do RS.
