### ISSUE TITLE
[bug] infCIOT

### ISSUE THREAD

**Issue by fabioselau077** [nfephp-org/sped-nfe#781]
Caros, na criação da XML estou recebendo o objeto com a tag infCIOT dentro da tag infANTT, que tá dentro da tag rodo.
Porém me retorna "Call to undefined method NFePHP\MDFe\Make::taginfCIOT()".
O que pode tá ocorrendo?

**Comment by robmachado** [comment]
Essa pergunta deveria ser direcionada ao sped-mdfe e não ao sped-nfe !! aqui você nunca terá uma resposta.
