### ISSUE TITLE
Passo ultNSU mas mesmo assim retorna documentos de numeração inferior

### ISSUE THREAD

**Issue by rmp1985** [nfephp-org/sped-nfe#788]
- [ ] bug

 - Versão do leiaute: "nfephp-org/sped-nfe" : "5.0.90"

## Comportamento esperado
Chamar sped-nfe/docs/metodos/DistDFe.md

Se eu passar ultNSU como 0 volta os NSU: 46, 47, 48, 49, 50
->sefazDistDFe(0);

Agora se eu passar ultNSU como 50 volta os NSU: 46, 47, 48, 49, 50
->sefazDistDFe(50);
Não deveria voltar um lote em branco?

Passar o ultNSU ou não não esta mudando nada.

**Comment by rmp1985** [comment]
A Sefaz gosta de deixar a  gente louco. Ontem direto isto que falei. Hoje funcionou como esperado. Não alterei nada no código.

**Comment by rmp1985** [comment]
Vou deixar minha contribuição. Eu estava usando o código de exemplo e descobri o que acontecia. 

Código esta na página:
https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/DistDFe.md

**while ($ultNSU <= $maxNSU) {**
    $iCount++;
    if ($iCount >= $loopLimit) {
        break;
    }
    try {
        //executa a busca pelos documentos
        $resp = $tools->sefazDistDFe($ultNSU);
    } catch (\Exception $e) {
        echo $e->getMessage();
        //tratar o erro
    }
 
    //extrair e salvar os retornos
    $dom = new \DOMDocument();
    $dom->loadXML($resp);
    $node = $dom->getElementsByTagName('retDistDFeInt')->item(0);
    $tpAmb = $node->getElementsByTagName('tpAmb')->item(0)->nodeValue;
    $verAplic = $node->getElementsByTagName('verAplic')->item(0)->nodeValue;
    $cStat = $node->getElementsByTagName('cStat')->item(0)->nodeValue;
    $xMotivo = $node->getElementsByTagName('xMotivo')->item(0)->nodeValue;
    $dhResp = $node->getElementsByTagName('dhResp')->item(0)->nodeValue;
    $ultNSU = $node->getElementsByTagName('ultNSU')->item(0)->nodeValue;
    $maxNSU = $node->getElementsByTagName('maxNSU')->item(0)->nodeValue;
    $lote = $node->getElementsByTagName('loteDistDFeInt')->item(0);
    if (empty($lote)) {
        //lote vazio
        **continue;**
    }
    //essas tags irão conter os documentos zipados
    $docs = $lote->getElementsByTagName('docZip');
    foreach ($docs as $doc) {
        $numnsu = $doc->getAttribute('NSU');
        $schema = $doc->getAttribute('schema');
        //descompacta o documento e recupera o XML original
        $content = gzdecode(base64_decode($doc->nodeValue));
        //identifica o tipo de documento
        $tipo = substr($schema, 0, 6);
        //processar o conteudo do NSU, da forma que melhor lhe interessar
        //esse processamento depende do seu aplicativo
    }
    sleep(2);
}

O problema esta na verificação do lote vazio com **continue**.

Pois ultNSU = 50 e maxNSU = 50 então quando vai pro while entra de novo gerando um loop infinito.

Acredito que alterar **continue** para **break** seja a solução.

**Comment by robmachado** [comment]
O código deveria ser algo assim:
`
$ultnsu = 100;
$maxnsu = $ultnsu + 1; //valor inicial apenas para forçar entrar no loop
while ($ultnsu < $maxnsu) {

.......
}

`

**Comment by rmp1985** [comment]
Bom dia Roberto,

Então eu usei break e esta indo bem. Apenas informo que é bom atualizar a página de exemplo aqui no github pois se a galera copiar vai entrar em um loop infinito...

Obrigado

**Comment by robmachado** [comment]
Alterei a doc

**Comment by robmachado** [comment]
Eu mesmo valido com o BREAK no codigo para evitar o loop infinito
