### ISSUE TITLE
Erro de formatação do campo "pICMSInter"

### ISSUE THREAD

**Issue by jheizerwandel** [nfephp-org/sped-nfe#796]
Ao preencher o campo "pICMSInter" na tag "ICMSUFDest"  automaticamente o  campo  é formatado para ter 4 casas decimais , assim retorna o seguinte erro : 

"This XML is not valid. Element '{http://www.portalfiscal.inf.br/nfe}pICMSInter': [facet 'enumeration'] The value '12.0000' is not an element of the set {'4.00', '7.00', '12.00'}. 
Element '{http://www.portalfiscal.inf.br/nfe}pICMSInter': '12.0000' is not a valid value of the local atomic type."

Como descrito na msg o campo só aceita 2 casas decimais .

**Comment by robmachado** [comment]
UEBA!! Erro meu corrigido !! Obrigado
