### ISSUE TITLE
Formatação do campo pICMSInter

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-nfe#797]
* **Estou enviando um ...**
  - [x ] bug

## Descrição detalhada
Estou com uma duvida, o campo **pICMSInter** começou a falhar na validação da formatação do valor desse campo, examinando o código percebi que no commit:
https://github.com/nfephp-org/sped-nfe/commit/e7ff6fa6fa58c3a711829f4055576ec24c9d4c98
O número de casas decimais foi de 2 para 4 o que acredito que o correto é 2 por ter visto este commit mais antigo
https://github.com/nfephp-org/sped-nfe/commit/76753291c77d5cb3710b503f367047712023a381
Então gostaria de saber se isso foi algum ajuste para se adequar para uma nova regra da SPED ou isso foi um bug mesmo?

**Comment by robmachado** [comment]
UEBA!! Erro meu corrigido !! Obrigado
