### ISSUE TITLE
Sugestão para leitura de certificado pfx.

### ISSUE THREAD

**Issue by FagnerQueiroz** [nfephp-org/sped-nfe#802]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.00
  - Linux  Debian 10.4
  - PHP 7.4

## Possível implementação
Recebi um certificado PFX com base_64 ao invés do binário então tive que alterar a função abaixo:
Detalhe: tenho os 2 tipos de certificado em produção .
vendor\nfephp-org\sped-common\src\Certificate.php

public static function readPfx($content, $password)
    {
        $certs = [];
        if (!openssl_pkcs12_read($content, $certs, $password)) {
           //throw CertificateException::unableToRead();  
         /****************substituir a linha acima por **************/
            $content = base64_decode($content);
            if(!openssl_pkcs12_read($content, $certs, $password)){
                 throw CertificateException::unableToRead();
            }
          /*********************Fim ******************************/
        }
        $chain = '';
        if (!empty($certs['extracerts'])) {
            foreach ($certs['extracerts'] as $ec) {
                $chain .= $ec;
            }
        }
        return new static(
            new PrivateKey($certs['pkey']),
            new PublicKey($certs['cert']),
            new CertificationChain($chain)
        );
    }

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Fagner !! PFX é um arquivo BINARIO e não um base64. Se você recebe um base64 é tarefa do seu sistema transformar isso em um binario PFX

**Comment by FagnerQueiroz** [comment]
Roberto obrigado pela resposta. Pra mim foi algo inesperado. Não achei nada semelhante no forum. Mas é no minimo esquisito vc receber um PFX em base 64; Pela sua experiência é comum isso acontecer?

**Comment by robmachado** [comment]
Pois é Fagner, a cada dia temos uma SURPRESA, mas sim eu já isso e muitas outras do "arco da velha", com relação a certificados digitais, **mas não isso não é uma coisa comum**.
Esse não é o primeiro imbróglio com certificados e nem será o último, tem muitas coisas que podem falhar.
Lembre-se que normalmente os certificados são gerados pela web e tem inúmeras certificadoras com aplicativos diferentes,  alem disso o windows normalmente é exigido para fazer esse processo e sabe lá como estão as configurações da maquina (bichos e outros) que está fazendo esse processo. São muitas variáveis.
