### ISSUE TITLE
Gerar XML de NFe cancelada

### ISSUE THREAD

**Issue by MarconWillian** [nfephp-org/sped-nfe#806]
Pessoal, alguém pode me dizer se é possível eu atualizar um XML após o cancelamento, adicionando o evento nele?

**Comment by robmachado** [comment]
veja o metodo cancelRegister() https://github.com/nfephp-org/sped-nfe/blob/master/docs/Complements.md

**Comment by MarconWillian** [comment]
Maravilha, Nota 10 para vocês, quando peguei o projeto todo bagunçado que estou trabalhando, a sorte minha é que ele usa como base este pacote inclivel de vocês! Muito obrigado por tudo!
