### ISSUE TITLE
Erro ao gerar o documento da NFCe com PHP 8

### ISSUE THREAD

**Issue by rjlfurtado** [nfephp-org/sped-nfe#807]
* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - "nfephp-org/sped-da": "^0.2.6",
  - "nfephp-org/sped-nfe": "^5.0",
  - "PHP 8"
  - "Laravel 8"
  
## Comentário
Aparentemente a NFCe é gerada mais não imprime o documento da mesma.
Isso aconteceu após uma atualização da versão do PHP para a versão citada acima.
OBS: Isso não é uma grande coisa, mas espero ajudar com isso.
## Passos para reproduzir

```
message: "Call to undefined function NFePHP\DA\NFe\Traits\imagefontheight()", exception: "Error",…}
exception: "Error"
file: "D:\project201\vendor\nfephp-org\sped-da\src\NFe\Traits\TraitBlocoIII.php"
line: 147
message: "Call to undefined function NFePHP\DA\NFe\Traits\imagefontheight()"
```

**Comment by robmachado** [comment]
Você lançou essa ISSUE no projeto ERRADO !!
esse é um erro aparentemente do sped-da e não do sped-nfe

**Comment by robmachado** [comment]
Além disso, nenhum dos projetos está sendo testado para php 8.0 até esse momento, mas vamos investigar a causa, assim que possível, por favor registre essa ISSUE no projeto correto.

**Comment by robmachado** [comment]
NOTA: verifique se php80-gd está instalada GD module for PHP

**Comment by rjlfurtado** [comment]
Resolvido com sucesso após adicionar a extensão php80-gd.
Desculpe por não ter notado o projeto NFE.
OBS: estou gerando e imprimindo normalmente com o PHP 8.
