### ISSUE TITLE
Estrutura de arquivos e pastas não estão completos no download.

### ISSUE THREAD

**Issue by cristianocds** [nfephp-org/sped-nfe#813]
Amigos,

A estrutura de arquivos e pastas não esta completas no ZIP do download. Toda vez que faço o download a estrutura que esta dentro do ZIP é diferente da estrutura mostrada aqui no painel do github:
![image](https://user-images.githubusercontent.com/79229107/108274153-4479f680-7153-11eb-818e-b4684d695527.png)

**Comment by robmachado** [comment]
Baixe usando o GIT que trará todo o conteúdo do repositório, o ZIP é feito pelo GitHUB e não por nós

**Comment by joaoroyosilva** [comment]
roda git clone https://github.com/nfephp-org/sped-nfe.git
