### ISSUE TITLE
Atualização dos campos

### ISSUE THREAD

**Issue by lucaspelle1909** [nfephp-org/sped-nfe#816]
Uma nova atualização exige o campo "indIntermed" para a emissão da NF, conforme o seguinte trecho:

"A obrigatoriedade de informar o campo de indicativo da operação com intermediador/marketplace, que será obrigatório informar quando o indicador de presença for 1=Operação presencial; 2=Operação não presencial, pela Internet; 3=Operação não presencial, Teleatendimento; 4=NFC-e em operação com entrega a domicílio; ou 9=Operação não presencial, outros."

Em: https://blog.tecnospeed.com.br/nota-tecnica-2020-006-versao-1-10-da-nf-e-e-nfc-e/

Esse campo ainda não está disponível nessa lib né?

**Comment by robmachado** [comment]
Na biblioteca está e esta sendo usado em homologação !!
Mas em produção apenas depois da data indicada pela SEFAZ

**Comment by lucaspelle1909** [comment]
Ah bom, é que eu não havia encontrado esse campo no Make.md
