### ISSUE TITLE
O código do tipo de evento informado não corresponde a nenhum evento estabelecido

### ISSUE THREAD

**Issue by GlauberF** [nfephp-org/sped-nfe#820]
* **Estou enviando um ...**
  - [ ] bug
  - [x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

Estamos tentando manifestar uma CT-e, cujo  manifestação é **Prestação do Serviço em Desacordo**, código do evento é **610110**
Porem pelo que verifiquei não tem esse evento mapeado.

**Comment by robmachado** [comment]
Então CTe é outro pacote sped-cte este serve apenas para NFe.
Por favor coloque a ISSUE no pacote correto que algum mantenedor vai processa-lo 
Obrigado
