### ISSUE TITLE
Xml de inutilização não passou em validação externa por conta do valor "procInutNFe"

### ISSUE THREAD

**Issue by MarconWillian** [nfephp-org/sped-nfe#821]
* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

## Comportamento esperado
De acordo com o https://www.sefaz.rs.gov.br/nfe/nfe-val.aspx, espera ProcInutNFe 

## Comportamento Atual
Esta retornando procInutNFe no xml.

## Contexto (Ambiente)
Estou fazendo em homologação do Distrito Federal.

## Descrição detalhada
Estava implementando aqui a inutilização da NF, e achei uma coisa estranha, não é bem no sped-nfe.
Gerei o xml normal da inutilização e coloquei ele no https://www.sefaz.rs.gov.br/nfe/nfe-val.aspx para verificar se fiz tudo correto. Porem ali apareceu o seguinte:
![image](https://user-images.githubusercontent.com/34342635/110842491-ea69de00-8285-11eb-88eb-dbf3b4811841.png)

Fui dar uma olhada e alterando direto no xml de procInutNFe para ProcInutNFe passou na validação.

O estranho é que no evento a chave inicial ali é minúsculo, mas na inutilização ele esta pedindo maiúsculo.

**Comment by robmachado** [comment]
Ajustado em MASTER, teste ai por favor e ma avise se está correto !

**Comment by MarconWillian** [comment]
Tudo correto :)
![image](https://user-images.githubusercontent.com/34342635/110848036-5f401680-828c-11eb-84c4-12eb0da569ba.png)
