### ISSUE TITLE
NFc-e com URL começando com hom.

### ISSUE THREAD

**Issue by GlauberF** [nfephp-org/sped-nfe#826]
- [ ] bug
  - [x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

Estamos implementando a NFC-e em Santa catarina e me parece que em produção a url deveria começar sem **hom.**, até por que se tirar o **hom** da frente, existe uma url válida.
- URl atual utilizada em produção: http://hom.sat.sef.sc.gov.br/nfce/consulta
- Como acredito que deveria estar a URl de Produção: http://sat.sef.sc.gov.br/nfce/consulta

**Comment by robmachado** [comment]
Verifiquei o arquivo e as URLS
https://hom.sat.sef.sc.gov.br/nfce/consulta
e
https://sat.sef.sc.gov.br/nfce/consulta
Ambas existem e respondem
