### ISSUE TITLE
Ambiente informado diverge do Ambiente de recebimento

### ISSUE THREAD

**Issue by izacximenes** [nfephp-org/sped-nfe#827]
* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

 Eu estava testando usando o ambiente de homologação estava funcionando tudo normal, troquei o ambiente para produção e agora estou recebendo o erro:
 
 Rejeição 252: Ambiente informado diverge do Ambiente de recebimento
 
 config:
 
  ```
 $this->config =  [
            "atualizacao" => "2021-01-28 16:30:21",
            "tpAmb" => intval($empresa['ambiente']) // 1,
            "razaosocial" => $empresa['razaoSocial'] // nome da empresa,
            "siglaUF" => $empresa['uf'] // CE,
            "cnpj" => $empresa['cnpj'] // cnpj da empresa,
            "schemes" => "PL_008i2",
            "versao" => "4.00",
            "tokenIBPT" => "AAAAAAA",
   ];
```

**Comment by robmachado** [comment]
Caro colega !
Não basta alterar na configuração, isso fará com que as solicitações sejam direcionadas para os servidores de homologação da SEFAZ.

Esse erro é causado, pois o tpAmb na NFe (dentro do xml) está indicando uma coisa e o servidor é outro.[
Ex. tpAmb (do XML) == 2 e tpAmb (do config) == 1 isso vai dar esse erro

**Comment by izacximenes** [comment]
@robmachado , obrigado
