### ISSUE TITLE
Make - getErrors() Não funcionando Propriamente.

### ISSUE THREAD

**Issue by cchimbooo** [nfephp-org/sped-nfe#834]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:

<! --- Apague as linhas abaixo, 13-42 caso não esteja enviando um bug  ->

## Comportamento esperado
Ao usar a função getErrors() do Make deveria ser retornado todos os erros constantes no XML.

## Comportamento Atual

Alguns erros não aparecem no getErrors() e estouram no getXML().

## Passos para reproduzir

1 - Criei todas as tags corretamente (menos o vCOFINS que recebeu o valor null).
2 - No final da criação chamei  $this->makeNfe->getErrors() e me retornou uma lista vazia. 
3 - No controller: 
 

```
        $nfeService = new GerarNfService($id, $configFiscal);
        //$tools = $this->getTools($configFiscal, $nfeService->getModeloDoc(), $nfeService->getUfEmit());

        dd($makeNfe->getErrors());
        $makeNfe = $nfeService->gerarXml();
        //O dd($makeNfe->getErrors() retorna um array vazio. 
```

4 - Se eu removo o dd a função nfeService->geraXml() atira uma runtime exception:
`RuntimeException('Existem erros nas tags. Obtenha os erros com getErrors().');`

5 - Para fins de teste alterei  o Make.php

```
        if (count($this->errors) > 0) {
            dd($this->errors, 'Existem erros nas tags. Obtenha os erros com getErrors().');
            throw new RuntimeException('Existem erros nas tags. Obtenha os erros com getErrors().');
        }
```

O output: 
```
     array:2 [
  0 => "Preenchimento Obrigatório! [vCOFINS] Valor da COFINS"
  1 => "Preenchimento Obrigatório! [vCOFINS] [item 1] Valor da COFINS"
]
"Existem erros nas tags. Obtenha os erros com getErrors()."`
```

## Contexto (Ambiente)
Problema com o tratamento de erro.

**Comment by robmachado** [comment]
Não saber usar corretamente ou não entender como fazer, não significa que o código esteja errado!!
```php
try {
    //aqui coloca a construção da make
} catch  (\Exception $e) {
    echo "<pre>";
   print_r($make->getErrors());
    echo "</pre>";
}
```

**Comment by cchimbooo** [comment]
Desculpa. Muito Obrigado.

**Comment by robmachado** [comment]
Sem problema colega !
