### ISSUE TITLE
Calculo de impostos

### ISSUE THREAD

**Issue by DevNF** [nfephp-org/sped-nfe#897]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 5.0

Bom Dia! tudo bem com vocês? Meu nome é Diego, trabalho na NFService e utilizamos a bastante tempo a biblioteca! Atualmente estamos desenvolvendo uma nova aplicação para renovar e modernizar nossa marca, com isso estamos tentando simplificar tudo que for possível. Ai queríamos saber se é possível (ou se já existe algo) implementarmos uma funcionalidade (onde o usuário passando todas as alíquotas e valores bases) que calcule os totais de uma nota! Pois o problema é não termos mão de obra suficiente e especializada para esses cálculos, então manter os mesmo sozinhos é difícil, ai pensamos que se fosse possível adicionar essa funcionalidade a Biblioteca (que tem uma comunidade considerada) seria mais fácil de manter essa função funcional e mais redonda o possível com a possibilidade de ter pessoas mais especializadas nessa parte trabalhando junto conosco! Teria possibilidade disso (ou caso já exista também)? Caso não seja possível, saberia me dizer qual o maior problema em implementar? Desde já agradeço e fico no aguardo! ^^

**Comment by robmachado** [comment]
Diego; Se o problema é a TOTALIZAÇÃO da NFe, então está resolvido.
A classe Make é capaz de realizar a totalização dos valores da NFe, basta não passar dados no método tagICMSTot()
Se você não passar informações nesse método a classe entende que deve totalizar sozinha.

**Comment by DevNF** [comment]
Hmmm, entendi, não sabiamos disso ainda, vou realizar os testes para ver se é oque precisamos, qualquer coisa entro em contato novamente. Mas muito obrigado Roberto!

**Comment by robmachado** [comment]
No caso de NFe conjugadas (NFse de Brasilia) ainda tem a totalização do ISSQN, lembre-se disso

**Comment by DevNF** [comment]
Ah sim, entendi! Okay
Uma ultima pergunta, o nosso sistema possibilita a pessoa ver os totais antes de transmitir a nota, consigo usar o totalizador do biblioteca para realizar essa calculo, para exibir para meu usuário, antes mesmo dele transmitir a nota, no momento em que ele salvar o registro (mas sem transmissão)?

**Comment by DevNF** [comment]
Bom pelo que vi acho que não é exatamente isso, se entendi bem tirando essa tag, para que a biblioteca some sozinha, ela só vai pegar as informações de imposto e totais individuais de cada produto e somar para gerar o ICMSTot, porem o que preciso é exatamente o passo anterior, o calculo dos impostos com reduções e tudo que for preciso calcular em cada produto(passando as aliquotas e bases de cada produto e sendo calculado os valores para depois gerar os totais do ICMSTot). Seria mais o calculo tributário em si, e não apenas o totalizador (porém as aliquotas sendo fornecidas pelo próprio usuário)

**Comment by robmachado** [comment]
Diego; nesse caso em particular entramos num terreno perigoso !!
A complexidade da legislação fiscal brasileira (um entulho de "malucos") faz com que uma solução desse tipo seja "EXTREMAMENTE" difícil de ser feita e eu diria até MUITO PERIGOSA.

Não é atribuição da biblioteca lidar com regras de negócios (dentre elas as regras fiscais), pois são muitas variáveis.

A biblioteca deve atender QUALQUER emitente de QUALQUER porte, de QUALQUER uf e QUALQUER operação fiscal, então ela teria de ter uma inteligência fiscal complexa demais. As coisas pode ser bem simples para fazer uma venda com NFCe mas extremamente complicada em outras centenas de casos.

Se está necessitando de auxilio no estabelecimento de regras fiscais sugiro que fale com o Marco Polo pelo https://www.sacfiscal.com.br/ ele tem algumas soluções que podem ser úteis para você.

**Comment by DevNF** [comment]
Ahh sim, entendi, é o que nos falam bastante hueuehuheu, não custava perguntar! É justamente por ser complicado que estamos buscando ver se conseguimos ajuda nisso, pois é algo bem chato de mexer, mas tudo bem, obrigado pelo seu tempo, vo olhar oque me mandou e ver se acho alguma solução! Mas muito obrigado mesmo, e desculpe perturbar com isso heuhehheuhe. Uma ótima tarde ai e até mais ^^
