### ISSUE TITLE
Requisição SOAP Inválida

### ISSUE THREAD

**Issue by xGreatSoulx** [nfephp-org/sped-nfe#902]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **
PHP 7.2
Windows
APACHE
Obs: Projeto inicialmente foi feito no AdiantiBuilder

## Comportamento Atual
Estava tentando fazer a transmissão do XML para o SEFAZ, porém ele me retorna o seguinte aviso:

![image](https://user-images.githubusercontent.com/82913812/142490691-205d3da9-7a46-4e84-be7c-cc52e298a758.png)

E também os seguintes textos:

Warning: Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP) in C:\Users\Programador02\Desktop\testenfe2\vendor\nfephp-org\sped-nfe\src\Common\Tools.php on line 525

Notice: Undefined index: SOAP_1_2 in C:\Users\Programador02\Desktop\testenfe2\vendor\nfephp-org\sped-common\src\Soap\SoapBase.php on line 419

## Solução possível
Não achei algo parecido

## Passos para reproduzir
Preencher os dados da nota e utilizar a função "sefazEnviaLote"

## Contexto (Ambiente)
Tentando transmitir XML para o SEFAZ.
Obs: Já verifiquei a nota em dois verificadores e em ambos me retornam um XML Válido.

**Comment by joaoroyosilva** [comment]
Chegou a conferir se as extensões necessárias estão habilitadas no php?

 "ext-zlib": "*",
  "ext-dom": "*",
  "ext-openssl": "*",
  "ext-soap": "*",
  "ext-json": "*",
  "ext-simplexml": "*",
  "ext-libxml": "*"

**Comment by robmachado** [comment]
Isso é causado por alguma **falha no seu ambiente PHP**, já ocorreu com outros, mas não me recordo o motivo.

**Comment by xGreatSoulx** [comment]
> Chegou a conferir se as extensões necessárias estão habilitadas no php?
> 
> "ext-zlib": "_", "ext-dom": "_", "ext-openssl": "_", "ext-soap": "_", "ext-json": "_", "ext-simplexml": "_", "ext-libxml": "*"

Provavelmente não, como faço para verificar?

**Comment by robmachado** [comment]
Uma coisa provável é que a extensão SOAP não esteja instalada ou habilitada.
**NOTA: Eu NUNCA e em hipótese alguma, uso Windows, nem mesmo em desenvolvimento, para rodar aplicações PHP, recomendo que você use o Docker para isso.**

**Comment by xGreatSoulx** [comment]
> Uma coisa provável é que a extensão SOAP não esteja instalada ou habilitada. **NOTA: Eu NUNCA e em hipótese alguma, uso Windows, nem mesmo em desenvolvimento, para rodar aplicações PHP, recomendo que você use o Docker para isso.**

Essa habilitação da extensão SOAP, seria fazer isso?

PHP.ini
![image](https://user-images.githubusercontent.com/82913812/142493267-e59c3716-2f40-462f-95ab-53067fdf31b0.png)

**Comment by robmachado** [comment]
Provavelmente, mas eu apenas uso LINUX a mais de 20 anos, e no linux é um pouco diferente, mas pode ser é só olhar na documentação do php para Ruindows.

**Comment by joaoroyosilva** [comment]
Faz um tempo que eu também não uso no windows. Até onde u sei é só tirar o ";" do php.ini e reiniciar o servidor apache (wamp ou outro que vc esteja usando). Se estiver usando o apache no linux via wls2 ou no docker, é só instalar via apt mesmo.

**Comment by xGreatSoulx** [comment]
> Faz um tempo que eu também não uso no windows. Até onde u sei é só tirar o ";" do php.ini e reiniciar o servidor apache (wamp ou outro que vc esteja usando). Se estiver usando o apache no linux via wls2 ou no docker, é só instalar via apt mesmo.

Certo, então isso foi feito com a extensão SOAP, mas com as demais eu não consegui acha-las no meu PHP.ini

**Comment by xGreatSoulx** [comment]
Consegui habilitar a extensão SOAP e resolveu o problema.
Issue Fechada

**Comment by fabioselau077** [comment]
Caros, para NFC-e para o Paraná estamos recebemos "Erro de comunicação via SOAP. Erro interno do SERVIDOR.".
Porém no site da SEFAZ o PR tá como verde e não encontrei ninguém reclamando disso.
Sabem se é alguma instabilidade?
Obrigado

**Comment by robmachado** [comment]
Sim PR já caiu várias vezes e RS também, estão com instabilidades

Roberto
