### ISSUE TITLE
Busca por notas liberadas através de certificado

### ISSUE THREAD

**Issue by PivaTafarel** [nfephp-org/sped-nfe#904]
Estou tentando fazer a consulta por notas que o certificado digital tem liberação.
Consigo fazer a consulta das notas que estão no mesmo CPF que o certificado, utilizo a função sefazDistDFe para isso, teria uma forma de consultar as notas de outra pessoa que este certificado tem acesso? existe alguma documentação que me auxilie fazer isso?
Olhei as perguntas e deu uma passada na documentação mas não achei.

**Comment by robmachado** [comment]
As NFe são restritas aos envolvidos ou seja:
- Destinatário
- Transportador
- Autorizados por declaração na própria NFe
Apenas esses podem acessar a NFe pelo webservice

**Comment by PivaTafarel** [comment]
Sendo assim mesmo que via sistema do Sefaz possa acessar a NFe, via webservice no PHP não tem como pegar essas notas?
Que pena iria facilitar bastante a vida de nossos clientes no preenchimento das informações para o eSocial, obrigado @robmachado

**Comment by devsabrinaelias** [comment]
Olá, gostaria de saber se a API tem limite de notas em cada lote enviado? Por exemplo se eu quiser emitir 1000 (mil) notas de uma vez, eu consigo? Estou ciente que a validação de cada nota é individual, só quero saber se consigo enviar mil de uma vez.

**Comment by robmachado** [comment]
Não Sabina, existem DOIS limites no lote

- um lote deve conter menos de 50 notas
- um lote não pode ter mais de 500 KB

Roberto
