### ISSUE TITLE
Limite de notas 

### ISSUE THREAD

**Issue by devsabrinaelias** [nfephp-org/sped-nfe#905]
Olá, gostaria de saber se a API tem limite de notas em cada lote enviado? Por exemplo se eu quiser emitir 1000 (mil) notas de uma vez, eu consigo? Estou ciente que a validação de cada nota é individual, só quero saber se consigo enviar mil de uma vez.

**Comment by robmachado** [comment]
Não ... existem limites e que são até um pouco difíceis  de controlar, mensagem enviada aos WebServices para autorização não deve ultrapassar o tamanho de **500 KB**, senão será rejeitada.

Esse é o tamanho total do envelope SOAP que é aceito pelas SEFAZ.

Outro detalhe é o tempo de processamento de lotes grandes, você corre um enorme risco de dar timeout além de ser bem mais complexo administrar os retornos e as consulta de um grande numero de notas em um mesmo lote.

**Comment by robmachado** [comment]
Complementando, como **cada NFe tem em média cerca de 10KB** então em um lote poderiam ter em tese **até 50 NFe** (desde que o envelope resultante não ultrapasse 500KB)
