### ISSUE TITLE
Várias alterações para 2022

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-nfe#906]

**Comment by gersonfs** [comment]
Fala Roberto!
Uma das ideias é adicionar suporte a PHP 8.0 e 8.1. Tentei fazer isso mas tive dificuldade em manter o suporte ao php 7.0. 
A versão atual do PHPUnit não funciona com o php 8.0 e depois de atualizar a dependência, ela não funcionava com o PHP 7.0 :confused: Parei por aí, pode ter mais inconsistências.

**Comment by rabraga** [comment]
Boas!
Acho q o Roberto se refere a obrigações fiscais, certo?

**Comment by robmachado** [comment]
É isso ai .. temos várias alterações entrando em operação em 2022, mas eu vou também alterar o código para suportar PHP 8.*. Enquanto mantiver compatibilidade com o php7 teremos de deixar os testes unitários  compatíveis mas provavelmente ainda esse ano deixaremos essa compatibilidade e passando para o PHP8 definitivamente.

**Comment by gersonfs** [comment]
Olhando o histórico de instalações, acho interessante manter a compatibilidade com 7.4 pelo menos, ideal o 7.2. ( https://packagist.org/packages/nfephp-org/sped-nfe/php-stats ). Não sei o motivo, mas deu um boom de instalações com PHP 7.1 de novembro para cá, é algo fora da curva que deve ser temporário.

No PHPCS eu já fiz a verificação de compatibilidade com PHP 8.0 usando o php-compatibility: 
https://github.com/nfephp-org/sped-nfe/blob/master/phpcs.xml

O código em si é compatível, mas algumas dependências não.

Se você aprovar, posso fazer um PR removendo php 7.0 e 7.1 e incluindo o 8.0.

**Comment by robmachado** [comment]
Então Gerson acho melhor esperar um pouco mais, pois temos de rever todo o echo sistema primeiro quando fizermos isso, será um branch especifico e não no branch master

**Comment by gersonfs** [comment]
Até lá vou tentar incorporar mais testes e aumentar a cobertura.

**Comment by robmachado** [comment]
Isso sim seria bom Gerson
