### ISSUE TITLE
Valor de FCP

### ISSUE THREAD

**Issue by devsabrinaelias** [nfephp-org/sped-nfe#919]
Olá, quando vou fazer a emissão de uma nota com 2 ou mais produtos, esta me retornando a seguinte rejeição: Rejeição 861 - Total do FCP difere do somatório dos itens. Eu já fiz o calculo repetidas vezes e os valores estão corretos, o que acontece é que a classe make arredonda o valor. Será que poderiam me ajudar, por que quando eu faço o teste com um produto a nota é autorizada de primeira.

**Comment by joaoroyosilva** [comment]
Você pode informar o cálculo do total em vez de deixar a lib calcular.

**Comment by robmachado** [comment]
@devsabrinaelias Voce pode mandar detalhes sobre essa ocorrencia passando os dados da mesma maneira que você passou para ver o que pode estar acontecendo com o totalizador.
