### ISSUE TITLE
Detalhar produtos de uma nota. 

### ISSUE THREAD

**Issue by ipewebsistemas** [nfephp-org/sped-nfe#934]
Meu sistema precisa consultar a nota fiscal de diversos produtores rurais pela chave. 
Tenho que validar se a quantidade de dose da nota é superior à dos animais declarados. 
É possível?

**Comment by robmachado** [comment]
Meu amigo não entendi nada !!
Qual NFe emitidas pelos produtos rurais ou recebidas pelos produtores rurais ?
Se forem as notas RECEBIDAS pelos produtores rurais ai depende de alguns fatores e regras da SEFAZ.
O download pela chave está restrita a um pequeno numero de NFe por hora e os produtores devem ter CNPJ não sei se já liberaram a consulta quando o produtor tem apenas CPF.
