### ISSUE TITLE
Atualização de pacote sped-nfe e php 7.2.12

### ISSUE THREAD

**Issue by izaque** [nfephp-org/sped-nfe#935]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [ ] requisição de funcionalidade
  - [x] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute:

## Contexto (Ambiente)

Estou com PHP 7.2.12, e o sistema foi feito com Laravel. Na documentação do Readme diz que é recomendável php 7.2, porém o composer do pacote requer php >= 7.4. Gostaria de saber se esta versão do PHP é compativel com as últimas atualizações do Sped-nfe e seus pacotes dependentes? 

Atualização de pacote sped-nfe e php 7.2.12

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by robmachado** [comment]
Versão MINIMA PHP 7.4 !!!
Esse campo no readme foi um esquecimento

**Comment by izaque** [comment]
> Versão MINIMA PHP 7.4 !!! Esse campo no readme foi um esquecimento

Muito obrigado
