### ISSUE TITLE
Nota Técnica 2022.001 - v.1.00 - Publicada em 31/05/2022

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-nfe#938]
Boas!
Divulga especificação do Web Service de consulta pública do GTIN.

01. Resumo
O Ajuste SINIEF 07/05 e o Ajuste SINIEF 19/16 obrigam o preenchimento dos campos cEAN e
cEANTrib na Nota Fiscal Eletrônica (NF-e) e na Nota Fiscal de Consumidor Eletrônica (NFC-e)
quando o produto comercializado possuir código de barras com GTIN.
Os Ajustes SINIEF citados também estipulam que os sistemas autorizadores da NF-e e NFC-e
deverão validar as informações descritas nos campos cEAN e cEANTrib junto ao Cadastro
Centralizado de GTIN (CCG), devendo as notas serem rejeitadas em caso de não conformidade
com as informações contidas no CCG.
Estes Ajustes SINIEF podem ser encontrados seguintes endereços:
https://www.confaz.fazenda.gov.br/legislacao/ajustes/2005/AJ007_05
https://www.confaz.fazenda.gov.br/legislacao/ajustes/2016/AJ_019_16
A Consulta dos dados reduzidos do GTIN está disponível na Internet no “Portal dos Documentos
Fiscais Eletrônicos – SVRS”, para os Sistemas da Nota Fiscal Eletrônica (NF-e, NFC-e).
O objetivo desta Nota Técnica é viabilizar a consulta aos dados reduzidos do GTIN via Web Service,
permitindo a consulta automatizada pelas empresas que desejarem usar essa funcionalidade.

**Comment by rabraga** [comment]
Também já está disponível os esquemas XML. 

VERSÕES OFICIAIS (em uso)

[Esquemas XML NF-e/NFC-e - Pacote de Liberação da consulta GTIN (NT 2022.001 v.1.00). Publicado em 31/05/22](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=xJdTH687/8s=)

**Comment by rabraga** [comment]
@robmachado , eu não conhecia a sped-gtin, nunca usei. Dei uma olhada e acho que seria mais coerente mesmo implementar lá do que aqui na sped-nfe.

**Comment by robmachado** [comment]
Pois é, eu implementei ontem mesmo. Assim que fizer uma limpeza no código ou subir e voce pode me ajudar testando !

**Comment by rabraga** [comment]
@robmachado claro! já estou aqui implementando a sped-gtin no meu sistema.
