### ISSUE TITLE
Validação do XML - not accepted by the pattern

### ISSUE THREAD

**Issue by Geissr** [nfephp-org/sped-nfe#940]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 5.1.3 
  - OS: Linux 
  - PHP7.4

## Comportamento esperado
 Ele devia permitir a passagem de dados para o tipo string na hora de preencher algumas classes da NFe.

## Comportamento Atual
Está dando erros no pattern para strings, parecido com a issue #394 . Aparentemente na versão 5.1.3 o schema ainda está com o pattern antigo.

![image](https://user-images.githubusercontent.com/39568633/171919702-302bb33c-d34c-4ada-9da7-aa8a33b8c9a8.png)

## Solução possível
Substituir o pattern antigo pelo mencionado na issue sitada

**Comment by robmachado** [comment]
Não faço a menor ideia !1 do que você está falando !!
nro não tem pattern nem nenhum dos campos aos quais você se refere

**Comment by Brunnn** [comment]
@robmachado  creio que ele está se referindo ao arquivo localizado [aqui](https://github.com/nfephp-org/sped-nfe/blob/dd3c13ac0c4ee4e3f85ec0315f070575c4e2c4ea/schemes/PL_009_V4/tiposBasico_v4.00.xsd#L515), o schema responsável por campos validar os do tipo `string genérico` do XML, que foi mencionado após o issue #394.
Percebe-se que na tag [^v5.1.2](https://github.com/nfephp-org/sped-nfe/blob/4e170cf4485cf797e1cb2d26cdc41df4e589255c/schemes/PL_009_V4/tiposBasico_v4.00.xsd#L515) o pattern difere da versão anterior ([v5.1.1](https://github.com/nfephp-org/sped-nfe/blob/70019b1db776f3da11dbe40d1158ef3d97e8b112/schemes/PL_009_V4/tiposBasico_v4.00.xsd#L515)):
Isso foi intencional?

Aqui está o [compare entre as versões 5.1.2 e 5.1.1 ](https://github.com/nfephp-org/sped-nfe/compare/v5.1.1...v5.1.2#diff-9ea0772f1daa6855f743a316a98d91159b3fcc4ef3d08b9b128136644e6255b0), pesquise o arquivo no ctrl+f "tiposBasico_v4.00".

![image](https://user-images.githubusercontent.com/42523274/172166348-eb9bfdae-903e-4a95-82a3-7423a8b8db8d.png)


O problema ocorreu aqui também, somente no ambiente amazon linux 2, php ^7.4.

**Comment by NettoPassaro** [comment]
@Brunnn Exatamente o mesmo problema aqui.

Ambiente: Amazon Linux 2, php 7.4.29

```
Este XML não é válido. Element '{http://www.portalfiscal.inf.br/nfe}uCom': [facet 'pattern'] The value 'UN' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}uCom': 'UN' is not a valid value of the local atomic type.

Element '{http://www.portalfiscal.inf.br/nfe}uTrib': [facet 'pattern'] The value 'UN' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

Element '{http://www.portalfiscal.inf.br/nfe}uTrib': 'UN' is not a valid value of the local atomic type.
```

**Comment by Brunnn** [comment]
> @Brunnn Exatamente o mesmo problema aqui.
> 
> Ambiente: Amazon Linux 2, php 7.4.29
> 
> ```
> Este XML não é válido. Element '{http://www.portalfiscal.inf.br/nfe}uCom': [facet 'pattern'] The value 'UN' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.
> 
> Element '{http://www.portalfiscal.inf.br/nfe}uCom': 'UN' is not a valid value of the local atomic type.
> 
> Element '{http://www.portalfiscal.inf.br/nfe}uTrib': [facet 'pattern'] The value 'UN' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.
> 
> Element '{http://www.portalfiscal.inf.br/nfe}uTrib': 'UN' is not a valid value of the local atomic type.
> ```

Pois é, por enquanto minha solução foi o downgrade (creio que não há problemas no downgrade). Aparentemente pelo pouco que pesquisei no histórico de commits/releases do repositório, creio que o rollback do pattern no XML não foi intencional.

Alguma noticia @robmachado ?
