### ISSUE TITLE
Ambiente de emissão incorreto após iteração no timeout do soap

### ISSUE THREAD

**Issue by gabrieI-santos** [nfephp-org/sped-nfe#941]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 4.00
  - PHP 8.1
  - Servidor linux

## Comportamento esperado

O tpAmb deve permanecer o do construct

## Comportamento Atual
O tpAmb é redefinido pelo padrão = 2

## Passos para reproduzir

<img src="https://i.ibb.co/7SJ6xNz/Screen-Shot-2022-06-14-at-20-53-26.png"/>

## Contexto (Ambiente)
Após setar o timeout do soap, não foi mais possível emitir em produção. o XML gerado pela lib tinha o tpAmb = 1, porém sempre envia para o ambiente de homologação.

## Descrição detalhada
Estava tendo alguns problemas com timeout do soap com a lib para emitir NF-e modelo 55. Após algumas pesquisas e testes, encontrei a issue <a href="https://github.com/nfephp-org/sped-nfe/issues/587">https://github.com/nfephp-org/sped-nfe/issues/587</a> respondida pelo @robmachado.

Conforme a resposta do rob, uma solução rápida seria alterar o timeout do sopa, conforme: 
```
$tools = new Tools($config, $certificate);
$tools->soap->timeout(40); //tempo para timeout em segundos
```
Porém ao definir o timeout do soap, a lib do sped-nfe volta a setar o tpAmb como 2, ao invés de manter "1" como setado anteriormente.

## Solução encontrada utilizando recursos da biblioteca
<img src="https://i.ibb.co/ZGQPf2y/Screen-Shot-2022-06-14-at-21-03-36.png"></a>

Para mais informações, consulte o guia de CONTRIBUTING.

**Comment by gabrieI-santos** [comment]
No meu caso, eu instanciei a Tools primeiro, pode ter sido isso. Vou seguir seu exemplo e fazer mais testes

**Comment by robmachado** [comment]
Me avise, se o problema ocorrer novamente
