### ISSUE TITLE
ultNSU preenchido mas maxNSU zerado

### ISSUE THREAD

**Issue by rmp1985** [nfephp-org/sped-nfe#945]
Olha consultando um CNPJ que já viemos consultando a tempos (mais de 1 ano) sempre retornou normal ultNSU e maxNSU.

Mas desde ontem (pelo menos o percebido) esta retornando assim:

< ultNSU >000000000001678< /ultNSU >< maxNSU >000000000000000< /maxNSU >

Como pode o ambiente nacional retornar ultNSU preenchido e maxNSU zerado.

Alguém já passou por isso?

**Comment by guiffvii** [comment]
Geralmente isso acontece quando o cStat = 656 (Consumo indevido).

No caso você deve enviar outra requisição passando o ultNSU retornado na última consulta.

**Comment by nagahshi** [comment]
Eu não utilizo a lib pra isso, mas tive um problema parecido só que no meu
caso era o 656 como o Guilherme disse mas estava ocorrendo pois o contador
tinha uma plataforma e estava rodando junto com o sistema do cliente o que
começou a dar direto o 656 pois o NSU sempre estava incorreto

**Comment by guiffvii** [comment]
Exatamete o meu caso @nagahshi.
Tive que utilizar a consulta por nsu individual para preencher as lacunas que ficam na sequência por causa desse consumo em múltiplos softwares.

**Comment by robmachado** [comment]
Colegas, sempre antes de usar o retorno da sefaz é OBRIGATÒRIO usar o cSTAT se fizer isso não terá esse tipo de problema

**Comment by rmp1985** [comment]
Ola,

Muito obrigado pelas considerações. Realmente é Consumo Indevido.

Muito provavelmente devem ter outros softwares no mesmo CNPJ rodando.

Vocês tem alguma documentação do Ambiente Nacional que eu possa entender melhor este processo?

Tentei a dica do @guiffvii mas mesmo consultando individualmente: (seria isso ??)
< distDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.01" > < tpAmb > 1 < /tpAmb > < cUFAutor > 41 < /cUFAutor >< CNPJ > xxxxxxxxxxxxx < /CNPJ > < consNSU > < NSU > 000000000006681 < /NSU > < /consNSU > < /distDFeInt >

Retorna 137 - Nenhum documento.

Fiz esta individual para 20 NSU... e tudo veio 137

Agora consultando o cnpj no ambiente nacional estão la as notas (com menos de 90 dias).

Não sei o que posso estar errando...!!

**Comment by guiffvii** [comment]
Vou tentar explicar o meu caso em específico.
Suponhamos que sua úlitma consulta retornou o ultNSU=100 e outro sistema faz a consulta em lote e retornou lá pra ele o ultNSU=105.
O seu sistema não sabe dessa informação, mas o webservice da receita tem essa informação lá armazenada.
Quando sua aplicação consulta em lote novamente passando o ultNSU=100 você recebe o cStat=656 com a informação do ultNSU atual e um softblock de 1 hora nas consultas.
Na sua próxima consulta passando o ultNSU=105 você vai receber os eventos a partir do nsu 105 e sua sequencia vai ficar furada pois os eventos de 101 até 104 foram entregues para outra aplicação que não a sua.
Nesses caso você faz a consulta específica pelos nsus que estão faltando para completar sua sequência.

**Comment by rmp1985** [comment]
@guiffvii 

Muito obrigado, explicação perfeita!

No meu caso usando seu exemplo, mesmo tentando consultar individualmente o 101, depois 102, 103 e 104 esta me retornando 137 - Nenhum documento localizado apesar de estar me retornando ultNSU 105.

Ou seja não estou tendo softblock mas também não estou tendo o conteúdo 138.

A gente gerencia vários CNPJs (e todos funcionando normalmente), o que ocorre é que veio uns 3 CNPJs "novos" para gerenciar e estes me parecem ter muitos documentos. Em um dos CNPJs veio alguns (muito poucos) documentos com lacunas e outros 2 não vem nenhum. Da tudo 137. Ai eu tô tentando entender porque a AN não esta liberando (e já confirmei e é a AN mesmo e não RS).
