### ISSUE TITLE
- Links WS desatualizados homologação GO

### ISSUE THREAD

**Issue by michelfs** [nfephp-org/sped-nfe#950]
- [x] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: Homologação

## Comportamento esperado
Emitir uma NFe em ambiente de homologação.

## Comportamento Atual
Erro de comunicação via soap,  SSL peer was unable to negotiate an acceptable set of security parameters. [https://homolog.sefaz.go.gov.br/nfe/services/NFeStatusServico4]

## Solução possível
Com isso aparentemente o link do WS estava errado ou algum problema, no entanto fui buscar no site da Sefaz e realmente os links estão desatualizados.

Segue os novos WS:

Manual atual homologação:
https://hom.nfe.fazenda.gov.br/portal/webServices.aspx?AspxAutoDetectCookieSupport=1

Novos Links WS:

Sefaz Goias - (GO)

Serviço	Versão	URL
NfeInutilizacao	4.00	https://homolog.sefaz.go.gov.br/nfe/services/NFeInutilizacao4?wsdl
NfeConsultaProtocolo	4.00	https://homolog.sefaz.go.gov.br/nfe/services/NFeConsultaProtocolo4?wsdl
NfeStatusServico	4.00	https://homolog.sefaz.go.gov.br/nfe/services/NFeStatusServico4?wsdl
NfeConsultaCadastro	4.00	https://homolog.sefaz.go.gov.br/nfe/services/CadConsultaCadastro4?wsdl
RecepcaoEvento	4.00	https://homolog.sefaz.go.gov.br/nfe/services/NFeRecepcaoEvento4?wsdl
NFeAutorizacao	4.00	https://homolog.sefaz.go.gov.br/nfe/services/NFeAutorizacao4?wsdl
NFeRetAutorizacao	4.00	https://homolog.sefaz.go.gov.br/nfe/services/NFeRetAutorizacao4?wsdl

## Passos para reproduzir

Ao tentar emitir uma NFe 55 em ambiente de homologação acontece o problema.

**Comment by robmachado** [comment]
Cuidado com suposições quando erros ocorrem, é importante investigar e entender a mensagem de erro !!
Não estabeleça uma causa sem minimamente conferir antes, isso pode induzir a mais erros e desviar a atenção de quem pode te ajudar para o local errado.

**Comment by michelfs** [comment]
Muito obrigado, irei fazer o teste. 

abraços
