### ISSUE TITLE
BUG sefazCadastro quando UF é MT

### ISSUE THREAD

**Issue by rmp1985** [nfephp-org/sped-nfe#957]
Versão da biblioteca (mas ja conferi e a última versão esta assim também): 5.0.122

Apenas para a UF MT

Verifiquei que para MT realmente precisa adicionar a tag nfeDadosMsg como esta no código:

![image](https://user-images.githubusercontent.com/52454226/197253361-559894ee-210f-4320-97e5-b54e10e9d990.png)

Porém a validação seguinte (isValid) gera um throw

Este XML não é válido. Element 'nfeDadosMsg': No matching global declaration available for the validation root. 

Porém MT precisa desta TAG realmente, eu comentei este isValid e funcionou tudo como o esperado.

Acontece que este isValid consulta um schemme consCad_v2.00.xsd ( o mesmo para os outros estados ) então acredito que o problema esta ai.

Teria que criar um schemme específico para MT.

No momento tive de deixar assim para funcionar em nfephp-org\sped-nfe\src\Tools.php:

if (strtoupper($uf) == 'MT') {
  $request = "<nfeDadosMsg>$request</nfeDadosMsg>" ;
} else {
  $this->isValid($this->urlVersion, $request, 'consCad');
}

no lugar de 

if (strtoupper($uf) == 'MT') {
  $request = "<nfeDadosMsg>$request</nfeDadosMsg>" ;
}
$this->isValid($this->urlVersion, $request, 'consCad');

**Comment by rabraga** [comment]
Complicado né @rmp1985...

**Comment by robmachado** [comment]
A solução mais simples é essa indicada, não valida o XSD quando consultar cadastros em MT.

A outra solução é mais complexa pois teríamos de criar um XSD especifico e chavear quando for MT e consulta de cadastro.

**Comment by robmachado** [comment]
Na verdade a solução mais simples de todas é mudar a posição do validador

```
if (strtoupper($uf) == 'MT') {
     $request = "<nfeDadosMsg>$request</nfeDadosMsg>" ;
}
$this->isValid($this->urlVersion, $request, 'consCad');

```
Para 

```
$this->isValid($this->urlVersion, $request, 'consCad');
if (strtoupper($uf) == 'MT') {
      $request = "<nfeDadosMsg>$request</nfeDadosMsg>" ;
}

```

**Comment by robmachado** [comment]
Já foi ajustado !

**Comment by rmp1985** [comment]
robmachado você é um gênio kkkk muito obrigado!!!
