### ISSUE TITLE
Erro ao transmitir NF-e estado UF CE

### ISSUE THREAD

**Issue by MarquesFS** [nfephp-org/sped-nfe#970]
Pessoal, estou com um erro ao enviar uma NFe para sefaz da UF CE, o erro que me retornar e esse ( Servico [NfeConsultaCadastro] indisponivel UF [CE] ou modelo [55]{} ), recentemente no inicio de 2022 as (URL dos Web Services) mudaram, mais eu ainda não localizei a solução. alguém pode me ajudar por favor!

**Comment by robmachado** [comment]
Não entendi absolutamente nada do que você descreve ! 
O autorizador de NFe (mod 55) para o CE é o SVRS o CE não tem webservice para modelo 55
