### ISSUE TITLE
Erro ao tentar emitir NFC-e  Failed to connect to nfce-homologacao.svrs.rs.gov.br port 443: Connection refused

### ISSUE THREAD

**Issue by joaolenosi** [nfephp-org/sped-nfe#991]
Consultei a sefaz e todos os serviços estão funcionando.
Esse erro comecou a ocorrer hoje, sem nenhuma alteração realizada no código fonte

An error occurred while trying to communication via soap, Failed to connect to nfce-homologacao.svrs.rs.gov.br port 443: Connection refused [https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx]

**Comment by robmachado** [comment]
Esse tipo de duvida deve ser tirada no grupo https://groups.google.com/g/nfephp
Não se trata de problemas ou bugs no código

**Comment by joaolenosi** [comment]
Ah, desculpas!
Vou postar no grupo, obrigado por avisar.
Mas só para ver outras análises, aí ta funcionando normalmente?

**Comment by robmachado** [comment]
Eu não testo regularmente homologação no RS, portanto não sei !
