### ISSUE TITLE
XSD de tiposBasico faltando TLatitude e TLongitude

### ISSUE THREAD

**Issue by rabraga** [nfephp-org/sped-nfe#996]
Boas!
Está fatando TLatitude e TLongitude nos arquivos tiposBasicosXXX.xsd. 
Tinha no arquivo tiposBasico_v1.03.xsd. Na versão atual não existe mais. Quem controla esses arquivos é a SEFAZ?
Ao tentar executar o método sefazComprovanteEntrega retorna:
element decl. latGPS, attribute type: The QName value TLatitude does not resolve to a(n) type definition.element decl. longGPS, attribute type: The QName value TLongitude does not resolve to a(n) type definition.

**Comment by robmachado** [comment]
Isso está em [e110130_v1.00.xsd](https://github.com/nfephp-org/sped-nfe/blob/master/schemes/PL_009_V4/e110130_v1.00.xsd), não houve nenhuma alteração nesse processo.

**Comment by robmachado** [comment]
Mas por algum motivo o XSD não está capturando todos os schemas para validação

**Comment by robmachado** [comment]
Achei o erro ! por algum motivo estão faltando esses campos em tiposBasico _v1.03 vou corrigir

**Comment by robmachado** [comment]
Ramon essa ISSUE acabou de ser corrigida !! mas não me pergunte porque tinha sumido esses dados no arquivo tiposBasico _v1.03.xsd pois quando eu criei o método testei e funcionava perfeitamente, em algum momento durante alguma atualização esse arquivo foi substituído. Mas agora deve passar na validação do XML.

**Comment by robmachado** [comment]
O interessante é eu mesmo substitui esse arquivo por duas vezes, por uma versão sem esses campos, porque vieram no dentro do pacote de xsd zipado, distribuído dos schemas oficiais do portal nfe. Ou seja eles mesmos deixaram esse XSD sem esses campos mas não alteraram em nada o evento em si.
